<?php
/**
 * V12.20 Morning Email + Deliverables Gallery
 * Upload: /public_html/lead-engine/build-morning-executive-brief.php
 *
 * Optional send:
 * ?send=1
 */

ini_set('display_errors', 0);
error_reporting(E_ALL);
require_once __DIR__ . '/config.php';
header('Content-Type: application/json; charset=utf-8');

try {
  $key = $_GET['key'] ?? '';
  if (!defined('AFTER_HOURS_CRON_KEY') || !AFTER_HOURS_CRON_KEY || !hash_equals(AFTER_HOURS_CRON_KEY, $key)) {
    http_response_code(403); echo json_encode(['success'=>false,'error'=>'Invalid key']); exit;
  }

  function sb201($method,$endpoint,$payload=null){
    $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($endpoint,'/'));
    $headers=['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json'];
    $headers[]=$method==='POST'?'Prefer: return=representation':'Prefer: return=representation';
    curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers,CURLOPT_TIMEOUT=>45]);
    if($payload!==null) curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($payload));
    $b=curl_exec($ch); $http=curl_getinfo($ch,CURLINFO_HTTP_CODE); $err=curl_error($ch); curl_close($ch);
    $d=json_decode($b,true);
    return ['ok'=>$http>=200&&$http<300,'http'=>$http,'body'=>$b,'error'=>$err,'data'=>is_array($d)?$d:[]];
  }
  function rows201($table,$query){ $r=sb201('GET',$table.'?'.$query); return $r['ok']?$r['data']:[]; }
  function jarr201($v){ if(is_string($v)){ $d=json_decode($v,true); return is_array($d)?$d:[]; } return is_array($v)?$v:[]; }

  function send_resend201($to,$subject,$html,$text){
    if(!defined('RESEND_API_KEY') || !RESEND_API_KEY){
      return ['ok'=>false,'reason'=>'RESEND_API_KEY not defined'];
    }
    $from = defined('RESEND_FROM_EMAIL') ? RESEND_FROM_EMAIL : 'Mark Pires <no-reply@markpires.com>';
    $payload=[
      'from'=>$from,
      'to'=>[$to],
      'subject'=>$subject,
      'html'=>$html,
      'text'=>$text
    ];
    $ch=curl_init('https://api.resend.com/emails');
    curl_setopt_array($ch,[
      CURLOPT_RETURNTRANSFER=>true,
      CURLOPT_POST=>true,
      CURLOPT_HTTPHEADER=>[
        'Authorization: Bearer '.RESEND_API_KEY,
        'Content-Type: application/json'
      ],
      CURLOPT_POSTFIELDS=>json_encode($payload),
      CURLOPT_TIMEOUT=>30
    ]);
    $b=curl_exec($ch); $http=curl_getinfo($ch,CURLINFO_HTTP_CODE); $err=curl_error($ch); curl_close($ch);
    $d=json_decode($b,true);
    return ['ok'=>$http>=200&&$http<300,'http'=>$http,'body'=>$b,'error'=>$err,'data'=>is_array($d)?$d:[]];
  }

  $today=date('Y-m-d');
  $deliverables=[];

  $command=rows201('daily_command_center_snapshots','select=*&order=created_at.desc&limit=1');
  $cmd=$command[0]??[];

  $queueBrief=rows201('queue_intelligence_briefings','select=*&order=created_at.desc&limit=1');
  $queue=$queueBrief[0]??[];

  $contactBrief=rows201('approved_contact_pipeline_briefings','select=*&order=created_at.desc&limit=1');
  $contacts=$contactBrief[0]??[];

  $execBrief=rows201('executive_call_briefings','select=*&order=created_at.desc&limit=1');
  $exec=$execBrief[0]??[];

  $learnBrief=rows201('conversation_learning_briefings_v2','select=*&order=created_at.desc&limit=1');
  $learn=$learnBrief[0]??[];

  $ads=rows201('live_ad_launch_checklists','select=*&launch_status=eq.ready&order=created_at.desc&limit=25');
  foreach($ads as $a){
    $deliverables[]=[
      'deliverable_date'=>$today,'deliverable_type'=>'ad','title'=>$a['campaign_name']??'Ready Ad',
      'town'=>'','market'=>'Paid Ads','priority_score'=>90,'status'=>$a['launch_status']??'ready',
      'action_url'=>$a['final_url']??'','summary'=>'Ready ad launch checklist with UTM URL.',
      'recommended_action'=>'Launch one small-budget test first, $10-$20/day.',
      'raw_payload'=>$a,'created_at'=>date('c'),'updated_at'=>date('c')
    ];
  }

  $content=rows201('seo_aeo_content_opportunities','select=*&order=priority_score.desc,created_at.desc&limit=50');
  foreach($content as $c){
    $deliverables[]=[
      'deliverable_date'=>$today,'deliverable_type'=>'content','title'=>$c['title']??'Content Opportunity',
      'town'=>$c['town']??'','market'=>$c['market']??'','priority_score'=>(int)($c['priority_score']??75),'status'=>'ready_for_review',
      'action_url'=>'/blog/'.($c['slug']??''),'summary'=>'SEO/AEO content opportunity generated by Jessica.',
      'recommended_action'=>'Create or approve this content and connect CTA to home valuation.',
      'raw_payload'=>$c,'created_at'=>date('c'),'updated_at'=>date('c')
    ];
  }

  $queueRows=rows201('daily_action_queue','select=*&status=eq.open&order=priority_rank.asc,priority_score.desc&limit=50');
  foreach($queueRows as $q){
    $deliverables[]=[
      'deliverable_date'=>$today,'deliverable_type'=>'queue','title'=>$q['action_title']??'Queue Action',
      'town'=>$q['town']??'','market'=>$q['market']??'','priority_score'=>(int)($q['priority_score']??0),'status'=>$q['status']??'open',
      'action_url'=>'/dashboard/queue-intelligence.php','summary'=>$q['action_reason']??'',
      'recommended_action'=>$q['recommended_script']??'',
      'raw_payload'=>$q,'created_at'=>date('c'),'updated_at'=>date('c')
    ];
  }

  $appts=rows201('appointment_intelligence_queue','select=*&appointment_status=eq.pending&order=appointment_priority.desc,created_at.desc&limit=25');
  foreach($appts as $a){
    $deliverables[]=[
      'deliverable_date'=>$today,'deliverable_type'=>'appointment','title'=>($a['caller_name']?:$a['caller_phone']?:'Appointment Follow-up'),
      'town'=>$a['town']??'','market'=>'Appointments','priority_score'=>(int)($a['appointment_priority']??0),'status'=>$a['appointment_status']??'pending',
      'action_url'=>'/dashboard/conversation-learning.php','summary'=>$a['appointment_reason']??'',
      'recommended_action'=>'Schedule or confirm follow-up with Mark.',
      'raw_payload'=>$a,'created_at'=>date('c'),'updated_at'=>date('c')
    ];
  }

  $execCalls=rows201('executive_call_inbox','select=*&status=eq.new&order=call_date.desc&limit=25');
  foreach($execCalls as $e){
    $score=($e['urgency']??'')==='urgent'?100:(($e['urgency']??'')==='high'?85:60);
    $deliverables[]=[
      'deliverable_date'=>$today,'deliverable_type'=>'executive_call','title'=>($e['caller_name']?:$e['caller_phone']?:'Forwarded Call'),
      'town'=>'','market'=>'Executive Inbox','priority_score'=>$score,'status'=>$e['status']??'new',
      'action_url'=>'/dashboard/executive-inbox.php','summary'=>$e['summary']??'',
      'recommended_action'=>$e['recommended_action']??'Review forwarded call.',
      'raw_payload'=>$e,'created_at'=>date('c'),'updated_at'=>date('c')
    ];
  }

  usort($deliverables,function($a,$b){return ($b['priority_score']<=>$a['priority_score']);});

  $inserted=[];$errors=[];
  foreach(array_chunk(array_slice($deliverables,0,500),100) as $chunk){
    $r=sb201('POST','jessica_daily_deliverables',$chunk);
    if($r['ok']) $inserted[]=['count'=>count($chunk),'http'=>$r['http']];
    else $errors[]=['http'=>$r['http'],'body'=>$r['body']];
  }

  $topTowns=jarr201($cmd['top_towns']??[]);
  $recs=jarr201($cmd['jessica_recommendations']??[]);
  $readiness=jarr201($cmd['readiness']??[]);

  $subject="Jessica Daily Brief — ".date('M j')." — ".($topTowns[0]['town']??'Mark Pires');
  $text="Jessica Daily Brief — {$today}\n\n";
  $text.="Top town: ".($topTowns[0]['town']??'n/a')."\n";
  $text.="Live ads ready: ".($cmd['live_ad_ready']??0)."\n";
  $text.="SEO/AEO opportunities: ".($cmd['seo_opportunities']??0)."\n";
  $text.="Queue actions: ".($queue['total_actions']??0)."\n";
  $text.="Call eligible contacts: ".($contacts['call_eligible']??0)."\n";
  $text.="Executive callbacks: ".($exec['callbacks_needed']??0)."\n";
  $text.="Appointments/follow-ups: ".($learn['appointments_detected']??0)." / ".($learn['followups_detected']??0)."\n\n";
  $text.="Recommended actions:\n";
  foreach($recs as $i=>$r){ $text.=($i+1).". ".$r."\n"; }
  $text.="\nTop deliverables:\n";
  foreach(array_slice($deliverables,0,15) as $i=>$d){ $text.=($i+1).". [".$d['deliverable_type']."] ".$d['title']." — ".$d['recommended_action']."\n"; }

  $html='<div style="font-family:Arial,sans-serif;background:#f5f3ef;padding:24px;color:#111"><div style="max-width:760px;margin:auto;background:#fff;border-radius:16px;overflow:hidden"><div style="background:#10101a;color:white;padding:24px"><h1 style="margin:0;color:#c8a96e">Jessica Daily Brief</h1><p>'.htmlspecialchars($today).'</p></div><div style="padding:24px">';
  $html.='<h2>Executive Snapshot</h2><ul>';
  $html.='<li><b>Top town:</b> '.htmlspecialchars($topTowns[0]['town']??'n/a').'</li>';
  $html.='<li><b>Live ads ready:</b> '.htmlspecialchars((string)($cmd['live_ad_ready']??0)).'</li>';
  $html.='<li><b>SEO/AEO opportunities:</b> '.htmlspecialchars((string)($cmd['seo_opportunities']??0)).'</li>';
  $html.='<li><b>Queue actions:</b> '.htmlspecialchars((string)($queue['total_actions']??0)).'</li>';
  $html.='<li><b>Call eligible contacts:</b> '.htmlspecialchars((string)($contacts['call_eligible']??0)).'</li>';
  $html.='<li><b>Executive callbacks:</b> '.htmlspecialchars((string)($exec['callbacks_needed']??0)).'</li>';
  $html.='</ul><h2>Jessica Recommends</h2><ol>';
  foreach($recs as $r){ $html.='<li>'.htmlspecialchars($r).'</li>'; }
  $html.='</ol><h2>Top Deliverables</h2><ol>';
  foreach(array_slice($deliverables,0,15) as $d){ $html.='<li><b>'.htmlspecialchars($d['deliverable_type']).':</b> '.htmlspecialchars($d['title']).'<br><span style="color:#666">'.htmlspecialchars($d['recommended_action']).'</span></li>'; }
  $html.='</ol><p><a href="https://markpires.com/dashboard/jessica-deliverables.php" style="display:inline-block;background:#c8a96e;color:#111;padding:12px 16px;border-radius:8px;text-decoration:none;font-weight:bold">Open Deliverables Gallery</a></p></div></div></div>';

  $sendStatus='drafted'; $sendResponse=null;
  if(isset($_GET['send']) && $_GET['send']=='1'){
    $sendResponse=send_resend201('mark@markpires.com',$subject,$html,$text);
    $sendStatus=$sendResponse['ok']?'sent':'failed';
  }

  $log=[[
    'email_date'=>$today,
    'recipient'=>'mark@markpires.com',
    'subject'=>$subject,
    'email_body'=>$text,
    'send_status'=>$sendStatus,
    'resend_response'=>$sendResponse,
    'created_at'=>date('c'),
    'updated_at'=>date('c')
  ]];
  $lr=sb201('POST','jessica_morning_email_logs',$log);

  echo json_encode([
    'success'=>empty($errors),
    'deliverables_created'=>count($deliverables),
    'inserted'=>$inserted,
    'email_status'=>$sendStatus,
    'email_subject'=>$subject,
    'email_preview'=>$text,
    'send_response'=>$sendResponse,
    'log_http'=>$lr['http'],
    'errors'=>$errors
  ],JSON_PRETTY_PRINT);

} catch(Throwable $e){
  http_response_code(500);
  echo json_encode(['success'=>false,'error'=>'PHP exception','message'=>$e->getMessage(),'line'=>$e->getLine()],JSON_PRETTY_PRINT);
}
?>