<?php
if(!function_exists('g93_table_exists')){function g93_table_exists($t){try{$r=gdb_one("SELECT COUNT(*) c FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?",[$t]);return ((int)($r['c']??0))>0;}catch(Throwable $e){return false;}}}
if(!function_exists('g93_col_exists')){function g93_col_exists($t,$c){try{$r=gdb_one("SELECT COUNT(*) c FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=? AND column_name=?",[$t,$c]);return ((int)($r['c']??0))>0;}catch(Throwable $e){return false;}}}
if(!function_exists('g93_uid')){function g93_uid($p='id'){return function_exists('gdb_uid')?gdb_uid($p):$p.'_'.date('YmdHis').'_'.bin2hex(random_bytes(5));}}
if(!function_exists('g93_json')){function g93_json($v){return json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}}
if(!function_exists('g93_safe_insert')){function g93_safe_insert($t,$row){if(!g93_table_exists($t))return null;$s=[];foreach($row as $k=>$v){if(g93_col_exists($t,$k))$s[$k]=$v;}return $s?gdb_insert($t,$s):null;}}
if(!function_exists('g93_safe_update')){function g93_safe_update($t,$id,$row){if(!g93_table_exists($t)||!$id)return false;$s=[];foreach($row as $k=>$v){if(g93_col_exists($t,$k))$s[$k]=$v;}if(!$s)return false;gdb_update($t,$s,'id=:id',['id'=>(int)$id]);return true;}}
if(!function_exists('g93_log_failure')){function g93_log_failure($leadUid,$service,$message,$payload=[],$severity='warning'){try{g93_safe_insert('goliath_revenue_engine_failures',['failure_uid'=>g93_uid('failure'),'lead_uid'=>$leadUid,'service'=>$service,'severity'=>$severity,'message'=>$message,'payload'=>g93_json($payload),'created_at'=>gdb_now()]);}catch(Throwable $e){}}}
if(!function_exists('g93_timeline')){function g93_timeline($leadUid,$crmId,$actor,$type,$title,$details='',$metadata=[],$status='complete'){return g93_safe_insert('goliath_lead_timeline',['event_uid'=>g93_uid('event'),'lead_uid'=>$leadUid,'crm_contact_id'=>$crmId,'actor'=>$actor,'event_type'=>$type,'title'=>$title,'details'=>$details,'status'=>$status,'metadata'=>g93_json($metadata),'created_at'=>gdb_now()]);}}
if(!function_exists('g93_score_lead')){function g93_score_lead($lead){$score=20;if(!empty($lead['email']))$score+=10;if(!empty($lead['phone']))$score+=15;if(!empty($lead['address']))$score+=20;$blob=strtolower(json_encode($lead));foreach(['asap','now','today','immediate','urgent','active','interviewing agents'] as $term){if(strpos($blob,$term)!==false){$score+=20;break;}}foreach(['westport','new canaan','darien','greenwich','fairfield','wilton','weston'] as $town){if(strpos($blob,$town)!==false){$score+=10;break;}}$money=preg_replace('/[^0-9]/','',(string)($lead['estimated_value']??$lead['budget']??$lead['price_range']??''));if($money&&(int)$money>=600000)$score+=20;return min(100,$score);}}
if(!function_exists('g93_clean')){function g93_clean($v){if(is_array($v))return trim(strip_tags(implode(', ',array_filter(array_map('strval',$v)))));return trim(strip_tags((string)$v));}}
if(!function_exists('g93_normalize_lead')){function g93_normalize_lead($data){$lead=['lead_uid'=>g93_uid('lead'),'name'=>g93_clean($data['name']??$data['full_name']??''),'email'=>strtolower(g93_clean($data['email']??'')),'phone'=>g93_clean($data['phone']??$data['mobile']??''),'address'=>g93_clean($data['address']??$data['property_address']??''),'town'=>g93_clean($data['town']??$data['towns']??$data['target_towns']??$data['city']??''),'type'=>g93_clean($data['type']??$data['lead_type']??$data['form_type']??'website_lead'),'timeline'=>g93_clean($data['timeline']??''),'goal'=>g93_clean($data['goal']??''),'message'=>g93_clean($data['message']??$data['notes']??$data['comments']??''),'budget'=>g93_clean($data['budget']??''),'estimated_value'=>g93_clean($data['estimated_value']??$data['value_range']??''),'price_range'=>g93_clean($data['price_range']??''),'source'=>g93_clean($data['source']??(defined('SITE_DOMAIN')?SITE_DOMAIN:'markpires.com')),'page_url'=>g93_clean($data['page_url']??($_SERVER['HTTP_REFERER']??'')),'utm_source'=>g93_clean($data['utm_source']??''),'utm_medium'=>g93_clean($data['utm_medium']??''),'utm_campaign'=>g93_clean($data['utm_campaign']??''),'utm_content'=>g93_clean($data['utm_content']??''),'utm_term'=>g93_clean($data['utm_term']??''),'visitor_id'=>g93_clean($data['visitor_id']??''),'session_id'=>g93_clean($data['session_id']??''),'referrer'=>g93_clean($data['referrer']??($_SERVER['HTTP_REFERER']??'')),'created_at'=>date('c')];$lead['lead_score']=g93_score_lead($lead);$lead['route']=$lead['lead_score']>=75?'mark_priority':'standard_followup';return $lead;}}
if(!function_exists('g93_save_internal_crm')){function g93_save_internal_crm($lead,$raw=[]){$crmId=null;try{if(g93_table_exists('internal_crm_contacts')){$existing=null;if(!empty($lead['email']))$existing=gdb_one("SELECT id FROM internal_crm_contacts WHERE COALESCE(email,'')=? OR COALESCE(existing_email,'')=? LIMIT 1",[$lead['email'],$lead['email']]);if(!$existing&&!empty($lead['phone']))$existing=gdb_one("SELECT id FROM internal_crm_contacts WHERE COALESCE(phone,'')=? OR COALESCE(existing_phone,'')=? LIMIT 1",[$lead['phone'],$lead['phone']]);$row=['contact_uid'=>$lead['lead_uid'],'lead_uid'=>$lead['lead_uid'],'source_type'=>'website_form','lead_type'=>$lead['type'],'name'=>$lead['name'],'owner_name'=>$lead['name'],'email'=>$lead['email'],'existing_email'=>$lead['email'],'phone'=>$lead['phone'],'existing_phone'=>$lead['phone'],'property_address'=>$lead['address'],'address'=>$lead['address'],'town'=>$lead['town'],'city'=>$lead['town'],'status'=>'new','relationship_status'=>'new_lead','research_status'=>'queued','priority'=>max(1,(int)ceil(($lead['lead_score']??50)/20)),'lead_score'=>$lead['lead_score'],'route'=>$lead['route'],'notes'=>$lead['message'],'evidence'=>'Website form captured by Goliath Revenue Engine V93.1 at '.date('c'),'raw_json'=>g93_json($raw),'metadata'=>g93_json(['lead'=>$lead,'internal_first'=>true,'no_voice_call'=>true]),'created_at'=>gdb_now(),'updated_at'=>gdb_now()];if($existing){$crmId=(int)$existing['id'];g93_safe_update('internal_crm_contacts',$crmId,$row);}else{$crmId=g93_safe_insert('internal_crm_contacts',$row);}}g93_timeline($lead['lead_uid'],$crmId,'Revenue Engine','lead_created','Lead captured and saved internally','Internal CRM is the source of truth.',$lead);}catch(Throwable $e){g93_log_failure($lead['lead_uid'],'internal_crm',$e->getMessage(),$lead,'critical');}return $crmId;}}
?>
