<?php
ini_set('display_errors',0); header('Content-Type: application/json; charset=utf-8');
try{require_once __DIR__.'/config.php';require_once __DIR__.'/goliath-db.php';
$key=$_GET['key']??'';$expected=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:(defined('RETELL_WEBHOOK_KEY')?RETELL_WEBHOOK_KEY:'timetomakethedonuts');
if(!hash_equals((string)$expected,(string)$key)){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'bad_key']);exit;}
function uid107($p){return function_exists('gdb_uid')?gdb_uid($p):$p.'_'.date('YmdHis').'_'.bin2hex(random_bytes(4));} function one107($s,$p=[]){try{return gdb_one($s,$p)?:null;}catch(Throwable $e){return null;}} function all107($s,$p=[]){try{return gdb_all($s,$p)?:[];}catch(Throwable $e){return [];}}
function col107($t,$c){$r=one107("SELECT COUNT(*) c FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=? AND column_name=?",[$t,$c]);return ((int)($r['c']??0))>0;} function ins107($t,$row){$safe=[];foreach($row as $k=>$v){if(col107($t,$k))$safe[$k]=$v;}return $safe?gdb_insert($t,$safe):null;} function upd107($t,$where,$params,$row){$safe=[];foreach($row as $k=>$v){if(col107($t,$k))$safe[$k]=$v;}if($safe)gdb_update($t,$safe,$where,$params);}
$session=one107("SELECT * FROM goliath_council_sessions WHERE status='open' ORDER BY id DESC LIMIT 1"); if(!$session){$uid=uid107('council');ins107('goliath_council_sessions',['session_uid'=>$uid,'session_type'=>'executive_council','title'=>'Executive Council '.date('Y-m-d H:i'),'status'=>'open','summary'=>'V107 council session opened. Mark is Executive #13.','created_at'=>gdb_now()]);$session=one107("SELECT * FROM goliath_council_sessions WHERE session_uid=?",[$uid]);}
$sid=$session['session_uid'];$opps=all107("SELECT * FROM goliath_opportunity_marketplace WHERE status='proposed' ORDER BY priority_score DESC,confidence_score DESC LIMIT 12");$names=['goliath'=>'Goliath','scout'=>'Scout','einstein'=>'Einstein','shakespeare'=>'Shakespeare','scorsese'=>'Scorsese','jessica'=>'Jessica','sherlock'=>'Sherlock','rockefeller'=>'Rockefeller','pandora'=>'Pandora','mozart'=>'Mozart','chief_of_staff'=>'Chief of Staff'];
$msg=0;$votes=0;foreach($opps as $o){$team=json_decode($o['recommended_team_json']??'[]',true)?:['goliath'];foreach($team as $exec){$text=($exec==='goliath')?'This should be evaluated against Founder Vision, revenue, and project fit.':(($exec==='rockefeller')?'Revenue view: prioritize if ROI justifies effort.':(($exec==='scorsese')?'Media view: this can become video, shorts, thumbnails and captions.':(($exec==='shakespeare')?'Authority view: one idea should become a full content package.':(($exec==='jessica')?'Relationship view: I can turn this into outreach and follow-up.':'I can contribute if my department improves the outcome.'))));ins107('goliath_council_messages',['session_uid'=>$sid,'speaker_key'=>$exec,'speaker_name'=>$names[$exec]??ucfirst($exec),'message_type'=>'recommendation','message_text'=>$text,'confidence_score'=>(int)$o['confidence_score'],'opportunity_uid'=>$o['opportunity_uid'],'created_at'=>gdb_now()]);$msg++;ins107('goliath_council_votes',['session_uid'=>$sid,'opportunity_uid'=>$o['opportunity_uid'],'executive_key'=>$exec,'vote'=>((int)$o['priority_score']>=70?'approve':'debate'),'score'=>(int)$o['priority_score'],'reason'=>'Priority '.$o['priority_score'].' / confidence '.$o['confidence_score'],'created_at'=>gdb_now()]);$votes++;}upd107('goliath_opportunity_marketplace','id=:id',['id'=>$o['id']],['status'=>'council','updated_at'=>gdb_now()]);}
ins107('goliath_council_messages',['session_uid'=>$sid,'speaker_key'=>'mark','speaker_name'=>'Chairman Mark Pires','message_type'=>'chairman_prompt','message_text'=>'Executive #13 panel is open. Mark can approve, reject, reprioritize, request debate, or add a new idea at any time.','confidence_score'=>100,'created_at'=>gdb_now()]);
echo json_encode(['ok'=>true,'version'=>'V107.0 Executive Council','session_uid'=>$sid,'opportunities_moved_to_council'=>count($opps),'messages_created'=>$msg,'votes_created'=>$votes,'next'=>'Open /dashboard/executive-council-v107.php','time'=>date('c')],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);
}catch(Throwable $e){echo json_encode(['ok'=>false,'error'=>$e->getMessage(),'file'=>$e->getFile(),'line'=>$e->getLine()],JSON_PRETTY_PRINT);}
?>