<?php
ini_set('display_errors',0); header('Content-Type: application/json; charset=utf-8');
try{
require_once __DIR__.'/config.php'; require_once __DIR__.'/goliath-db.php';
$key=$_GET['key']??''; $expected=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:(defined('RETELL_WEBHOOK_KEY')?RETELL_WEBHOOK_KEY:'timetomakethedonuts');
if(!hash_equals((string)$expected,(string)$key)){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'bad_key']);exit;}
function ex($sql){if(function_exists('gdb_exec'))return gdb_exec($sql);return gdb()->exec($sql);}
function one($s,$p=[]){try{return gdb_one($s,$p)?:null;}catch(Throwable $e){return null;}}
function col($t,$c){try{$r=gdb_one("SELECT COUNT(*) c FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=? AND column_name=?",[$t,$c]);return ((int)($r['c']??0))>0;}catch(Throwable $e){return false;}}
function ins($t,$row){$safe=[];foreach($row as $k=>$v){if(col($t,$k))$safe[$k]=$v;}return $safe?gdb_insert($t,$safe):null;}
function uid($p){return function_exists('gdb_uid')?gdb_uid($p):$p.'_'.date('YmdHis').'_'.bin2hex(random_bytes(4));}

ex("CREATE TABLE IF NOT EXISTS goliath_core_charter(id INT AUTO_INCREMENT PRIMARY KEY,charter_key VARCHAR(80) UNIQUE,version VARCHAR(40),title VARCHAR(255),charter_text MEDIUMTEXT,laws_json JSON NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
ex("CREATE TABLE IF NOT EXISTS executive_dna_profiles(id INT AUTO_INCREMENT PRIMARY KEY,executive_key VARCHAR(80) UNIQUE,executive_name VARCHAR(120),title VARCHAR(180),identity_text MEDIUMTEXT,mission_text MEDIUMTEXT,constitution_text MEDIUMTEXT,responsibilities_json JSON NULL,knowledge_sources_json JSON NULL,kpis_json JSON NULL,daily_routine_json JSON NULL,initiative_rules_json JSON NULL,collaboration_rules_json JSON NULL,quality_standards_json JSON NULL,improvement_loop_json JSON NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
ex("CREATE TABLE IF NOT EXISTS goliath_missions(id INT AUTO_INCREMENT PRIMARY KEY,mission_uid VARCHAR(100) UNIQUE,title VARCHAR(255),mission_type VARCHAR(80),source VARCHAR(120),priority INT DEFAULT 50,revenue_potential DECIMAL(12,2) DEFAULT 0,status VARCHAR(60) DEFAULT 'proposed',owner_executive VARCHAR(80) DEFAULT 'goliath',assigned_executives_json JSON NULL,mission_packet_json JSON NULL,outcome_goal MEDIUMTEXT NULL,next_action MEDIUMTEXT NULL,due_at DATETIME NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(status),INDEX(priority),INDEX(owner_executive)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
ex("CREATE TABLE IF NOT EXISTS executive_mission_assignments(id INT AUTO_INCREMENT PRIMARY KEY,mission_uid VARCHAR(100),executive_key VARCHAR(80),assignment_type VARCHAR(80),status VARCHAR(60) DEFAULT 'assigned',instructions MEDIUMTEXT NULL,requested_help_json JSON NULL,output_summary MEDIUMTEXT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(mission_uid),INDEX(executive_key),INDEX(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
ex("CREATE TABLE IF NOT EXISTS executive_initiatives(id INT AUTO_INCREMENT PRIMARY KEY,initiative_uid VARCHAR(100) UNIQUE,executive_key VARCHAR(80),title VARCHAR(255),reason MEDIUMTEXT,expected_impact MEDIUMTEXT,recommended_mission_packet_json JSON NULL,status VARCHAR(60) DEFAULT 'recommended',priority INT DEFAULT 50,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(executive_key),INDEX(status),INDEX(priority)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
ex("CREATE TABLE IF NOT EXISTS executive_council_reports(id INT AUTO_INCREMENT PRIMARY KEY,report_uid VARCHAR(100) UNIQUE,council_date DATE,executive_key VARCHAR(80),completed_today MEDIUMTEXT NULL,learned_today MEDIUMTEXT NULL,recommends_next MEDIUMTEXT NULL,needs_help MEDIUMTEXT NULL,proposed_missions_json JSON NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,INDEX(council_date),INDEX(executive_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
ex("CREATE TABLE IF NOT EXISTS executive_org_memory(id INT AUTO_INCREMENT PRIMARY KEY,memory_uid VARCHAR(100) UNIQUE,scope VARCHAR(80),executive_key VARCHAR(80) NULL,memory_type VARCHAR(80),title VARCHAR(255),memory_text MEDIUMTEXT,evidence_json JSON NULL,confidence INT DEFAULT 70,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(scope),INDEX(executive_key),INDEX(memory_type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

$laws=['Always pursue the highest impact opportunity.','Never work alone if collaboration materially improves the result.','Verify before publishing.','Finished means delivered to its destination, not merely created.','Measure everything.','Every mission produces another mission.','Protect the founder’s time.','Leave the organization stronger than yesterday.','Respect healthy disagreement.','Beauty matters.','Legacy over convenience.'];
$charter="GOLIATH OMNI CORE CHARTER V1.0\n\nGoliath Omni is an autonomous executive organization. Every executive owns an outcome, not a task. The organization exists to continuously create measurable value for Mark Pires through intelligence, creativity, collaboration, integrity, beauty, and relentless execution.\n\nEvery executive begins each day by asking: What can I accomplish today that measurably improves Mark's businesses, reputation, relationships, or legacy?\n\nFinished means delivered. Rendering is not completion. Writing is not completion. Planning is not completion. Delivery is completion.";
$r=one("SELECT id FROM goliath_core_charter WHERE charter_key='core_v1' LIMIT 1");
$row=['version'=>'V101.0','title'=>'Goliath Omni Core Charter','charter_text'=>$charter,'laws_json'=>json_encode($laws,JSON_UNESCAPED_SLASHES),'updated_at'=>gdb_now()];
if($r)gdb_update('goliath_core_charter',$row,'id=:id',['id'=>$r['id']]); else {$row['charter_key']='core_v1';ins('goliath_core_charter',$row);}
$profiles=[
'goliath'=>['Goliath','CEO / Chief Executive OS','Owns priorities, mission allocation, council decisions, and final authority.'],
'scout'=>['Scout','Chief Revenue Intelligence Officer','Owns lead discovery, dossiers, seller opportunities, and speed-to-lead intelligence.'],
'jessica'=>['Jessica','Chief of Staff & Relationship Manager','Owns communication, follow-up, calendar coordination, reminders, and relationship momentum.'],
'shakespeare'=>['Shakespeare','Chief Content & Authority Officer','Owns campaigns, authority articles, story, voice, SEO content, and content packages.'],
'scorsese'=>['Scorsese','Chief Creative Production Director','Owns video direction, visual briefs, storyboards, production quality, thumbnails, and media delivery.'],
'sherlock'=>['Sherlock','Chief Verification & Strategy Officer','Owns fact verification, claims, sources, market truth, risk detection, and strategy QA.'],
'einstein'=>['Einstein','Chief Intelligence & Conversion Scientist','Owns analytics, SEO/AEO, heatmaps, conversion improvement, experiments, and performance learning.'],
'pandora'=>['Pandora','Chief Trend & Creative Strategy Officer','Owns trends, timing, creative angles, design opportunities, seasonal hooks, and market mood.'],
'mozart'=>['Mozart','Chief Audio & Voice Director','Owns music, voice, sound design, motifs, podcast/audio assets, and emotional audio branding.'],
'columbo'=>['Columbo','Chief Archive & YouTube Intelligence Officer','Owns historical content, archives, YouTube opportunities, and long-tail content mining.'],
'prospector'=>['Prospector','Chief Opportunity Miner','Owns new opportunity categories, market gaps, partnerships, booking targets, and hidden revenue sources.'],
'rockefeller'=>['Rockefeller','Chief Revenue Optimization Officer','Owns monetization, pricing, ROI, pipeline math, referral revenue, and financial strategy.']];
foreach($profiles as $k=>$p){$base=['Own outcomes, not tasks','Create proactive missions','Collaborate before delivery','Report learnings nightly'];
$row=['executive_key'=>$k,'executive_name'=>$p[0],'title'=>$p[1],'identity_text'=>$p[2],'mission_text'=>$p[0].' exists to make Mark more money, save time, increase authority, deepen relationships, and improve the Goliath organization.','constitution_text'=>'Inherit the Core Charter. Own outcomes. Create work. Request collaboration. Verify where needed. Deliver finished work to Mission Control.','responsibilities_json'=>json_encode($base),'knowledge_sources_json'=>json_encode(['Goliath database','Mission packets','Executive memory','Council reports','Founder prompts']),'kpis_json'=>json_encode(['Revenue influenced','Founder time saved','Deliverables completed','Missions advanced','Quality score','Learning captured']),'daily_routine_json'=>json_encode(['Observe signals','Recommend initiatives','Advance missions','Request help','Report council summary']),'initiative_rules_json'=>json_encode(['Create high-impact work without waiting for Mark']),'collaboration_rules_json'=>json_encode(['Ask other executives when they can materially improve the result']),'quality_standards_json'=>json_encode(['Useful','Beautiful','Measurable','Delivered','Trustworthy']),'improvement_loop_json'=>json_encode(['What did I complete?','What did I learn?','What should I improve tomorrow?']),'updated_at'=>gdb_now()];
$r=one("SELECT id FROM executive_dna_profiles WHERE executive_key=? LIMIT 1",[$k]); if($r)gdb_update('executive_dna_profiles',$row,'id=:id',['id'=>$r['id']]); else ins('executive_dna_profiles',$row);}
echo json_encode(['ok'=>true,'version'=>'V101.0 Executive Organization Core Installer','next'=>'Run /lead-engine/executive-initiative-engine-v101.php?key='.$key.'&limit=36','time'=>date('c')],JSON_PRETTY_PRINT);
}catch(Throwable $e){echo json_encode(['ok'=>false,'error'=>$e->getMessage(),'file'=>$e->getFile(),'line'=>$e->getLine()],JSON_PRETTY_PRINT);}
?>