<?php
ini_set('display_errors',0); header('Content-Type: application/json; charset=utf-8');
try{ require_once __DIR__.'/config.php'; require_once __DIR__.'/goliath-db.php'; require_once __DIR__.'/gbi-helpers.php';
$key=$_GET['key']??''; $expected=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:(defined('RETELL_WEBHOOK_KEY')?RETELL_WEBHOOK_KEY:'timetomakethedonuts');
if(!hash_equals((string)$expected,(string)$key)){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'bad_key']);exit;}
$limit=max(1,min(100,(int)($_GET['limit']??20)));
$rows=gdb_all("SELECT d.*, c.owner_name c_owner,c.property_address c_address,c.town c_town,c.state c_state,c.zip c_zip FROM scout_intel_dossiers d LEFT JOIN internal_crm_contacts c ON c.id=d.contact_id WHERE d.handoff_status<>'ready_for_mark' AND NOT EXISTS (SELECT 1 FROM goliath_browser_jobs b WHERE b.executive_key='scout' AND b.job_type='contact_enrichment' AND b.status IN ('queued','working','complete') AND b.prompt LIKE CONCAT('%Dossier ID: ',d.id,'%')) ORDER BY d.confidence_score DESC,d.id ASC LIMIT {$limit}")?:[];
$created=[];
foreach($rows as $r){$owner=$r['owner_name']?:($r['c_owner']??'');$address=$r['property_address']?:($r['c_address']??'');$town=$r['town']?:($r['c_town']??'');$urls=[gbi_qurl('"'.$owner.'" "'.$address.'" phone'),gbi_qurl('"'.$owner.'" "'.$town.'" CT phone email'),gbi_qurl('"'.$address.'" "'.$town.'" owner phone')];$prompt="Dossier ID: {$r['id']}\nContact ID: {$r['contact_id']}\nOwner: {$owner}\nProperty Address: {$address}\nTown: {$town}\nOpen a real browser. Search web. Return visible phone/email only with evidence URL.";$jobId=gbi_insert('goliath_browser_jobs',['job_uid'=>gbi_uid('gbj'),'executive_key'=>'scout','job_type'=>'contact_enrichment','target_name'=>$owner,'target_address'=>$address,'target_town'=>$town,'prompt'=>$prompt,'search_urls'=>gbi_json($urls),'status'=>'queued','progress'=>0,'current_step'=>'Queued for browser intelligence','priority'=>600,'created_at'=>gdb_now(),'updated_at'=>gdb_now()]);gbi_update('scout_intel_dossiers',(int)$r['id'],['research_status'=>'queued_for_browser_intelligence','next_action'=>'Queued for GBI job #'.$jobId,'updated_at'=>gdb_now()]);$created[]=['browser_job_id'=>$jobId,'dossier_id'=>(int)$r['id'],'contact_id'=>(int)$r['contact_id'],'owner'=>$owner,'address'=>$address];}
echo json_encode(['ok'=>true,'version'=>'V94 Scout Browser Seed','created_count'=>count($created),'created'=>$created,'time'=>date('c')],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);
}catch(Throwable $e){echo json_encode(['ok'=>false,'error'=>$e->getMessage(),'file'=>$e->getFile(),'line'=>$e->getLine()],JSON_PRETTY_PRINT);}
?>