<?php
require_once __DIR__.'/config.php';header('Content-Type: application/json; charset=utf-8');
$data=json_decode(file_get_contents('php://input'),true) ?: $_POST;
$agent=preg_replace('/[^A-Za-z]/','',$data['agent']??'Rockefeller');$command=trim($data['command']??'');
$valid=['Scout','Jessica','Scorsese','Shakespeare','Einstein','Rockefeller','Prospector','Columbo'];if(!in_array($agent,$valid,true))$agent='Rockefeller';if($command===''){echo json_encode(['success'=>false,'error'=>'Missing command']);exit;}
function sb_insert($table,$rows){$ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.$table);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>json_encode($rows),CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json','Prefer: return=representation'],CURLOPT_TIMEOUT=>20]);$body=curl_exec($ch);$http=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);return [$http,$body];}
$directive=['Scout'=>'Research data, owner signals, MLS/market movement, source intelligence.','Jessica'=>'Follow up with leads warmly through approved call/email/text workflows.','Scorsese'=>'Create, critique, revise and route media with quality gates.','Shakespeare'=>'Write content, hooks, blogs, captions and campaign language.','Einstein'=>'Analyze data, funnels, AEO/SEO, conversion and patterns.','Rockefeller'=>'Prioritize money, ROI, pipeline and executive decisions.','Prospector'=>'Mine new opportunities, find lead sources, identify referral/auction candidates.','Columbo'=>'Content archaeologist. Seek and source Mark Pires original archive gold from YouTube/long-form content. Find songs, comedy, powerful moments, CT moments, and send only high-scoring shorts candidates to Scorsese with timestamps, titles, descriptions, tags and posting windows.'][$agent];
$task=['task_type'=>'agent_command','model'=>'qwen2.5:7b','prompt'=>$agent.' directive: '.$directive."\n\nCommand: ".$command,'status'=>'queued','priority'=>$agent==='Columbo'?98:90,'metadata'=>['agent'=>$agent,'command'=>$command,'source'=>$data['source']??'mission_control','contact_mode'=>($agent==='Columbo'&&stripos($command,'text')!==false)?'text':'default']];
[$http,$body]=sb_insert('local_ai_tasks',[$task]);
$event=['department'=>$agent,'event_type'=>'agent_command','title'=>$agent.' command created','detail'=>$command,'roi_estimate'=>$agent==='Rockefeller'?2500:1000,'confidence'=>88,'status'=>'queued','link_url'=>'/dashboard/goliath-agent-detail.php?department='.rawurlencode($agent),'metadata'=>['agent'=>$agent,'command'=>$command]];sb_insert('goliath_events',[$event]);
echo json_encode(['success'=>$http>=200&&$http<300,'message'=>$agent.' is queued: '.$command,'http'=>$http]);
