<?php
declare(strict_types=1);ini_set('display_errors','0');header('Content-Type: application/json; charset=utf-8');header('Cache-Control:no-store');
require_once __DIR__.'/config.php';require_once __DIR__.'/goliath-db.php';
function tf_all($s,$p=[]){try{return gdb_all($s,$p)?:[];}catch(Throwable $e){return [];}}
function tf_one($s,$p=[]){try{return gdb_one($s,$p)?:[];}catch(Throwable $e){return [];}}
function tf_table($t){$r=tf_one("SELECT COUNT(*) c FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?",[$t]);return (int)($r['c']??0)>0;}
$key=(string)($_GET['key']??'');$expected=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:(defined('RETELL_WEBHOOK_KEY')?RETELL_WEBHOOK_KEY:'timetomakethedonuts');
if(!hash_equals((string)$expected,$key)){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'bad_key']);exit;}
$items=[];$today=date('Y-m-d');
if(tf_table('goliath_live_events_v111'))foreach(tf_all("SELECT id,executive_key,title,details,status,created_at FROM goliath_live_events_v111 ORDER BY id DESC LIMIT 30") as $r)$items[]=['key'=>'event:'.$r['id'],'kind'=>'event','icon'=>'⚡','executive'=>$r['executive_key']?:'goliath','title'=>$r['title'],'detail'=>$r['details'],'status'=>$r['status'],'created_at'=>$r['created_at'],'time_label'=>substr((string)$r['created_at'],11,5)];
if(tf_table('jessica_email_drafts'))foreach(tf_all("SELECT * FROM jessica_email_drafts WHERE status IN ('pending_approval','approved') ORDER BY id DESC LIMIT 12") as $r)$items[]=['key'=>'jessica:'.$r['id'],'kind'=>'email','icon'=>'✉️','executive'=>'jessica','title'=>$r['subject']??'Email draft ready','detail'=>'Campaign or contact message awaiting review','status'=>$r['status']??'pending','created_at'=>$r['created_at']??'','time_label'=>'REVIEW'];
if(tf_table('shakespeare_content_packages'))foreach(tf_all("SELECT * FROM shakespeare_content_packages ORDER BY id DESC LIMIT 12") as $r)$items[]=['key'=>'shakespeare:'.$r['id'],'kind'=>'content','icon'=>'✒️','executive'=>'shakespeare','title'=>$r['title']??'Authority package','detail'=>($r['content_type']??'content').' · '.($r['approval_status']??$r['status']??''),'status'=>$r['approval_status']??$r['status']??'working','created_at'=>$r['created_at']??'','time_label'=>'CONTENT'];
if(tf_table('scout_intel_dossiers'))foreach(tf_all("SELECT * FROM scout_intel_dossiers ORDER BY id DESC LIMIT 10") as $r)$items[]=['key'=>'scout:'.$r['id'],'kind'=>'lead','icon'=>'🕵️','executive'=>'scout','title'=>$r['owner_name']??'Lead dossier','detail'=>trim(($r['property_address']??'').' · '.($r['town']??''),' ·'),'status'=>$r['handoff_status']??'working','created_at'=>$r['updated_at']??'','time_label'=>'LEAD'];
if(tf_table('scorsese_comfy_jobs'))foreach(tf_all("SELECT * FROM scorsese_comfy_jobs WHERE status IN ('complete','completed','ready','working','rendering') ORDER BY id DESC LIMIT 10") as $r)$items[]=['key'=>'scorsese:'.$r['id'],'kind'=>'video','icon'=>'🎬','executive'=>'scorsese','title'=>$r['title']??'Media job','detail'=>($r['status']??'').' · '.($r['progress']??0).'%','status'=>$r['status']??'working','created_at'=>$r['updated_at']??'','time_label'=>strtoupper((string)($r['status']??'VIDEO'))];
if(tf_table('goliath_council_messages'))foreach(tf_all("SELECT * FROM goliath_council_messages ORDER BY id DESC LIMIT 15") as $r)$items[]=['key'=>'council:'.$r['id'],'kind'=>'council','icon'=>'🏛️','executive'=>$r['speaker_key']??'goliath','title'=>($r['speaker_name']??'Council').' — '.($r['message_type']??'update'),'detail'=>mb_substr((string)($r['message_text']??''),0,220),'status'=>'council','created_at'=>$r['created_at']??'','time_label'=>'COUNCIL'];
usort($items,fn($a,$b)=>strcmp((string)$b['created_at'],(string)$a['created_at']));
$active=tf_table('goliath_missions')?tf_one("SELECT COUNT(*) c FROM goliath_missions WHERE status NOT IN ('complete','completed','delivered','archived','canceled')"):['c'=>0];
$brief=['title'=>date('G')<12?'GOOD MORNING, MARK':(date('G')<17?'GOOD AFTERNOON, MARK':'GOOD EVENING, MARK'),'subtitle'=>($active['c']??0).' active missions · live updates from '.date('F j, Y')];
echo json_encode(['ok'=>true,'version'=>'V111.2 Living TV Feed','brief'=>$brief,'items'=>array_slice($items,0,60),'time'=>date('c')],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);
?>