<?php
require_once __DIR__.'/config.php'; header('Content-Type: application/json; charset=utf-8');
function sbq($ep){$ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json'],CURLOPT_TIMEOUT=>25]);$b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];}
function item($d,$type,$title,$summary,$status,$url,$score=0,$payload=[]){return ['department'=>$d,'type'=>$type,'title'=>$title,'summary'=>$summary,'status'=>$status,'url'=>$url,'score'=>$score,'payload'=>$payload];}
$dept=$_GET['department']??$_GET['dept']??'All'; $items=[];
$q='goliath_deliverables?select=*&order=priority.desc,created_at.desc&limit=80'; if($dept!=='All')$q='goliath_deliverables?select=*&department=eq.'.rawurlencode($dept).'&order=priority.desc,created_at.desc&limit=80';
foreach(sbq($q) as $r){$items[]=item($r['department']??$dept,$r['deliverable_type']??'deliverable',$r['title']??'Deliverable',$r['summary']??'',$r['status']??'ready',$r['review_url']?:($r['media_url']?:'/dashboard/goliath-review-center.php'),(int)($r['score']??0),$r);} 
if($dept==='Scorsese'||$dept==='All'){foreach(sbq('media_projects?select=*&order=created_at.desc&limit=80') as $r){$items[]=item('Scorsese','media',$r['title']??'Completed Media',$r['source_url']??'Ready for review',$r['status']??'review_ready','/dashboard/goliath-completed-media.php?id='.rawurlencode($r['id']??''),(int)($r['viral_score']??90),$r);}}
if($dept==='Rockefeller'||$dept==='All'){foreach(sbq('hunter_priority_rankings?select=*&order=hunter_score.desc,created_at.desc&limit=80') as $r){$items[]=item('Rockefeller','opportunity',$r['name']??($r['address']??'Opportunity'),trim(($r['town']??'').' · '.($r['call_recommendation']??'').' · $'.($r['expected_value']??0)),$r['status']??'active','/dashboard/goliath-opportunity-center.php?id='.rawurlencode($r['id']??''),(int)($r['hunter_score']??0),$r);}}
if($dept==='Scout'||$dept==='All'){foreach(sbq('scout_research_queue?select=*&order=created_at.desc&limit=80') as $r){$items[]=item('Scout','research',($r['owner_name']??'Owner').' · '.($r['found_phone']??'No phone yet'),($r['property_address']??'').' · '.($r['town']??''),$r['status']??'queued','/dashboard/scout-intelligence.php?id='.rawurlencode($r['id']??''),(int)($r['confidence']??0),$r);}}
if($dept==='Prospector'||$dept==='All'){foreach(sbq('prospector_opportunities?select=*&order=opportunity_score.desc,created_at.desc&limit=80') as $r){$items[]=item('Prospector','prospect',$r['owner_name']??($r['address']??'Prospect'),trim(($r['opportunity_type']??'').' · '.($r['town']??'').' · '.($r['phone']??'phone needed')),$r['status']??'review','/dashboard/prospector-opportunities.php?id='.rawurlencode($r['id']??''),(int)($r['opportunity_score']??0),$r);}}
if($dept==='Columbo'||$dept==='All'){foreach(sbq('columbo_content_finds?select=*&order=repurpose_score.desc,created_at.desc&limit=80') as $r){$items[]=item('Columbo','content_find',$r['title']??'Content Find',trim(($r['platform']??'').' · '.($r['recommended_format']??'').' · '.($r['recommended_hook']??'')),$r['status']??'found','/dashboard/columbo-content-vault.php?id='.rawurlencode($r['id']??''),(int)($r['repurpose_score']??0),$r);}}
if($dept==='Shakespeare'||$dept==='All'){foreach(sbq('seo_aeo_content_opportunities?select=*&order=priority_score.desc,created_at.desc&limit=80') as $r){$items[]=item('Shakespeare','content',$r['title']??($r['keyword_primary']??'Content Opportunity'),$r['meta_description']??($r['search_intent']??''),$r['status']??'draft','/dashboard/goliath-review-center.php?type=content&id='.rawurlencode($r['id']??''),(int)($r['priority_score']??0),$r);}}
echo json_encode(['success'=>true,'department'=>$dept,'count'=>count($items),'items'=>$items],JSON_PRETTY_PRINT);
?>