<?php
declare(strict_types=1);ini_set('display_errors','0');header('Content-Type: application/json; charset=utf-8');header('Cache-Control:no-store');
require_once __DIR__.'/config.php';require_once __DIR__.'/goliath-db.php';
function td_one($s,$p=[]){try{return gdb_one($s,$p)?:null;}catch(Throwable $e){return null;}}
$key=(string)($_GET['key']??'');$expected=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:(defined('RETELL_WEBHOOK_KEY')?RETELL_WEBHOOK_KEY:'timetomakethedonuts');
if(!hash_equals((string)$expected,$key)){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'bad_key']);exit;}
$parts=explode(':',(string)($_GET['item_key']??''),2);$type=$parts[0]??'';$id=(int)($parts[1]??0);$item=null;
if($type==='jessica'){$r=td_one("SELECT * FROM jessica_email_drafts WHERE id=?",[$id]);if($r)$item=['executive'=>'Jessica','kind'=>'Email Draft','status'=>$r['status']??'review','title'=>$r['subject']??'Email Draft','content'=>$r['body_text']??$r['body']??$r['message']??json_encode($r,JSON_PRETTY_PRINT),'created_at'=>$r['created_at']??'','actions'=>[['label'=>'Open Jessica Center','url'=>'/dashboard/jessica-relationship-center.php#draft-'.$id]]];}
elseif($type==='shakespeare'){$r=td_one("SELECT * FROM shakespeare_content_packages WHERE id=?",[$id]);if($r)$item=['executive'=>'Shakespeare','kind'=>'Authority Content','status'=>$r['approval_status']??$r['status']??'working','title'=>$r['title']??'Content Package','content'=>strip_tags((string)($r['content']??$r['html_content']??$r['content_html']??$r['outline']??json_encode($r,JSON_PRETTY_PRINT))),'created_at'=>$r['created_at']??'','actions'=>[['label'=>'Open Workshop','url'=>'/dashboard/shakespeare-authority-center.php#pkg-'.$id]]];}
elseif($type==='scout'){$r=td_one("SELECT * FROM scout_intel_dossiers WHERE id=?",[$id]);if($r)$item=['executive'=>'Scout','kind'=>'Lead Dossier','status'=>$r['handoff_status']??'working','title'=>($r['owner_name']??'Lead').' — '.($r['property_address']??''),'content'=>"Town: ".($r['town']??'')."\nPhone: ".($r['best_phone']??$r['phone_1']??'')."\nEmail: ".($r['best_email']??$r['email_1']??'')."\n\n".($r['research_summary']??$r['notes']??json_encode($r,JSON_PRETTY_PRINT)),'created_at'=>$r['updated_at']??'','actions'=>[['label'=>'Open Contact','url'=>'/dashboard/scout-ready-contacts.php#contact-'.$id]]];}
elseif($type==='scorsese'){$r=td_one("SELECT * FROM scorsese_comfy_jobs WHERE id=?",[$id]);if($r)$item=['executive'=>'Scorsese','kind'=>'Media Job','status'=>$r['status']??'working','title'=>$r['title']??'Media Job','content'=>"Progress: ".($r['progress']??0)."%\n\n".($r['prompt']??$r['error_message']??'Media production update.'),'created_at'=>$r['updated_at']??'','actions'=>array_values(array_filter([['label'=>'Open Studio','url'=>'/dashboard/scorsese-studio-pro.php#job-'.$id],!empty($r['output_url'])?['label'=>'Play Video','url'=>$r['output_url']]:null]))];}
elseif($type==='council'){$r=td_one("SELECT * FROM goliath_council_messages WHERE id=?",[$id]);if($r)$item=['executive'=>$r['speaker_name']??'Council','kind'=>'Executive Council','status'=>'council','title'=>$r['message_type']??'Council Update','content'=>$r['message_text']??'','created_at'=>$r['created_at']??'','actions'=>[['label'=>'Open Council','url'=>'/dashboard/executive-council-v107.php']]];}
elseif($type==='event'){$r=td_one("SELECT * FROM goliath_live_events_v111 WHERE id=?",[$id]);if($r)$item=['executive'=>$r['executive_key']??'Goliath','kind'=>$r['event_type']??'Event','status'=>$r['status']??'live','title'=>$r['title']??'Update','content'=>$r['details']??'','created_at'=>$r['created_at']??'','actions'=>!empty($r['url'])?[['label'=>'Open Full Workspace','url'=>$r['url']]]:[]];}
if(!$item){http_response_code(404);echo json_encode(['ok'=>false,'error'=>'item_not_found']);exit;}
echo json_encode(['ok'=>true,'item'=>$item],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);
?>