<?php
ini_set('display_errors',0); error_reporting(E_ALL);
require_once __DIR__.'/config.php';
header('Content-Type: application/json; charset=utf-8');
function sb($m,$ep,$p=null){$ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$m,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json','Prefer: return=representation'],CURLOPT_TIMEOUT=>90]);if($p!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($p));$b=curl_exec($ch);$h=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$d=json_decode($b,true);return['ok'=>$h>=200&&$h<300,'http'=>$h,'body'=>$b,'data'=>is_array($d)?$d:[]];}
function norm($s){return strtolower(trim(preg_replace('/[^a-z0-9]+/i',' ',(string)$s)));}
function getv($row,$keys){foreach($keys as $k){foreach($row as $rk=>$v){if(norm($rk)===norm($k)&&trim((string)$v)!=='')return trim((string)$v);}}return'';}
function num($v){$x=(float)preg_replace('/[^0-9.\-]/','',(string)$v);return($x>9999999999||$x<-1)?0:$x;}
function datev($v){$t=strtotime((string)$v);return$t?date('Y-m-d',$t):null;}
try{$in=json_decode(file_get_contents('php://input'),true);if(!is_array($in))$in=$_POST;$key=$in['key']??'';if(!defined('AFTER_HOURS_CRON_KEY')||!hash_equals(AFTER_HOURS_CRON_KEY,$key)){http_response_code(403);echo json_encode(['success'=>false,'error'=>'Invalid key']);exit;}$dataset=$in['dataset']??'failed';$batch=$in['batch']??('MLS '.date('YmdHis'));$replace=$in['replace']??'append';$chunk=(int)($in['chunk_index']??0);$rows=$in['rows']??[];if($chunk===0&&$replace==='replace_dataset')sb('DELETE','mls_status_records?status_type=eq.'.rawurlencode($dataset));$payload=[];$bad=[];foreach($rows as $i=>$row){if(!is_array($row))continue;$sn=getv($row,['Street Number']);$street=getv($row,['Street Name']);$addr=getv($row,['Address','Property Address','Street Address','Full Address']);if(!$addr&&($sn||$street))$addr=trim($sn.' '.$street);$town=getv($row,['City','Town','Municipality']);if(!$addr){$bad[]=['row'=>$i,'reason'=>'missing address'];continue;}$payload[]=['import_batch'=>$batch,'source_name'=>'MLS '.ucfirst($dataset).' Export','status_type'=>$dataset,'status'=>getv($row,['Status','Listing Status']),'address'=>$addr,'town'=>$town,'state'=>getv($row,['State']),'county'=>getv($row,['County']),'zip_code'=>getv($row,['Zip Code']),'owner_name'=>getv($row,['Owner Name']),'list_price'=>num(getv($row,['List Price','Price','Original List Price'])),'close_price'=>num(getv($row,['Close Price','Sold Price'])),'close_date'=>datev(getv($row,['Close Date','Sold Date'])),'expiration_date'=>datev(getv($row,['Expiration Date','Expired Date'])),'days_on_market'=>(int)num(getv($row,['DOM','Days On Market','CDOM'])),'bedrooms'=>num(getv($row,['Bedrooms','Beds Total','Beds'])),'bathrooms'=>num(getv($row,['Bathrooms','Baths Total','Baths Full'])),'sqft'=>num(getv($row,['SQFT Est Heated Above Grade','Sq Ft Total','Sqft','Square Feet'])),'acres'=>num(getv($row,['Acres'])),'year_built'=>(int)num(getv($row,['Year Built'])),'property_tax'=>num(getv($row,['Property Tax','Taxes','Tax Amount'])),'assessed_value'=>num(getv($row,['Assessed Value'])),'style'=>getv($row,['Style']),'subdivision'=>getv($row,['Subdivision/Complex','Subdivision']),'property_type'=>getv($row,['Property Type']),'raw'=>$row,'created_at'=>date('c'),'updated_at'=>date('c')];}if(!$payload){echo json_encode(['success'=>true,'dataset'=>$dataset,'inserted'=>0,'bad_rows'=>$bad]);exit;}$r=sb('POST','mls_status_records',$payload);if(!$r['ok']){http_response_code(500);echo json_encode(['success'=>false,'dataset'=>$dataset,'chunk_index'=>$chunk,'attempted'=>count($payload),'details'=>$r['body'],'bad_rows'=>$bad],JSON_PRETTY_PRINT);exit;}echo json_encode(['success'=>true,'dataset'=>$dataset,'chunk_index'=>$chunk,'inserted'=>count($payload),'batch'=>$batch,'bad_rows'=>$bad],JSON_PRETTY_PRINT);}catch(Throwable $e){http_response_code(500);echo json_encode(['success'=>false,'error'=>$e->getMessage(),'line'=>$e->getLine()],JSON_PRETTY_PRINT);}
?>