<?php
ini_set('display_errors',0); header('Content-Type: application/json; charset=utf-8');
try{require_once __DIR__.'/config.php';require_once __DIR__.'/goliath-db.php';
$key=$_GET['key']??'';$expected=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:(defined('RETELL_WEBHOOK_KEY')?RETELL_WEBHOOK_KEY:'timetomakethedonuts');
if(!hash_equals((string)$expected,(string)$key)){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'bad_key']);exit;}
function uid107($p){return function_exists('gdb_uid')?gdb_uid($p):$p.'_'.date('YmdHis').'_'.bin2hex(random_bytes(4));}
function one107($s,$p=[]){try{return gdb_one($s,$p)?:null;}catch(Throwable $e){return null;}} function all107($s,$p=[]){try{return gdb_all($s,$p)?:[];}catch(Throwable $e){return [];}}
function table107($t){$r=one107("SELECT COUNT(*) c FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?",[$t]);return ((int)($r['c']??0))>0;}
function col107($t,$c){$r=one107("SELECT COUNT(*) c FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=? AND column_name=?",[$t,$c]);return ((int)($r['c']??0))>0;}
function ins107($t,$row){$safe=[];foreach($row as $k=>$v){if(col107($t,$k))$safe[$k]=$v;}return $safe?gdb_insert($t,$safe):null;}
function opp107($exec,$title,$type,$unit,$details,$scores,$team,$source='generated',$sourceId=0){if(one107("SELECT id FROM goliath_opportunity_marketplace WHERE title=? AND status IN ('proposed','council','approved') LIMIT 1",[$title]))return null;$priority=max(1,min(100,(int)(($scores['revenue']??0)*.32+($scores['authority']??0)*.22+($scores['relationship']??0)*.18+($scores['media']??0)*.13+($scores['confidence']??0)*.15-($scores['difficulty']??0)*.15)));return ins107('goliath_opportunity_marketplace',['opportunity_uid'=>uid107('opp'),'source'=>$source,'source_id'=>$sourceId,'executive_key'=>$exec,'title'=>$title,'opportunity_type'=>$type,'business_unit'=>$unit,'details'=>$details,'priority_score'=>$priority,'confidence_score'=>(int)($scores['confidence']??75),'revenue_score'=>(int)($scores['revenue']??50),'authority_score'=>(int)($scores['authority']??50),'relationship_score'=>(int)($scores['relationship']??50),'media_score'=>(int)($scores['media']??50),'difficulty_score'=>(int)($scores['difficulty']??20),'recommended_team_json'=>json_encode($team,JSON_UNESCAPED_SLASHES),'status'=>'proposed','created_at'=>gdb_now(),'updated_at'=>gdb_now()]);}
$created=[];
if(table107('mls_scout_opportunities')){$c=one107("SELECT COUNT(*) c,AVG(opportunity_score) avgscore FROM mls_scout_opportunities WHERE status='open'")?:['c'=>0,'avgscore'=>0];if((int)$c['c']>0)$created[]=opp107('scout','Work the never-sold MLS opportunity pipeline','seller_pipeline','Mark Pires Real Estate',"Scout found {$c['c']} open expired/withdrawn/canceled opportunities that are not active and not sold.",['revenue'=>95,'authority'=>45,'relationship'=>80,'media'=>35,'confidence'=>(int)$c['avgscore'],'difficulty'=>35],['goliath','scout','sherlock','jessica','rockefeller'],'mls_scout_opportunities');}
if(table107('shakespeare_campaign_packages'))foreach(all107("SELECT id,title,authority_score FROM shakespeare_campaign_packages ORDER BY authority_score DESC,id DESC LIMIT 5") as $p)$created[]=opp107('shakespeare','Compound authority package: '.$p['title'],'authority_compound','Mark Pires Real Estate','One authority package should become page, FAQ, video, shorts, email, social, newsletter, and sponsor pitch.',['revenue'=>70,'authority'=>(int)$p['authority_score'],'relationship'=>65,'media'=>80,'confidence'=>88,'difficulty'=>35],['goliath','einstein','sherlock','shakespeare','scorsese','jessica','rockefeller'],'shakespeare_campaign_packages',(int)$p['id']);
if(table107('scorsese_raw_projects'))foreach(all107("SELECT id,title,brand_style FROM scorsese_raw_projects ORDER BY id DESC LIMIT 5") as $r)$created[]=opp107('scorsese','Repurpose raw footage: '.$r['title'],'media_repurpose',$r['brand_style']?:'Discover Connecticut','Raw footage should become shorts, reels, TikToks, YouTube clips, captions, titles, thumbnails, and sponsor-friendly cuts.',['revenue'=>65,'authority'=>60,'relationship'=>70,'media'=>95,'confidence'=>90,'difficulty'=>30],['goliath','scorsese','shakespeare','mozart','jessica'],'scorsese_raw_projects',(int)$r['id']);
$created[]=opp107('rockefeller','Create Discover Connecticut monthly sponsor pitch','sponsorship','Discover Connecticut','Package local businesses into a $500/month recurring sponsorship offer attached to interviews, reels, newsletters, and community authority content.',['revenue'=>82,'authority'=>76,'relationship'=>90,'media'=>85,'confidence'=>84,'difficulty'=>40],['goliath','rockefeller','jessica','shakespeare','scorsese','scout'],'standing_strategy');
echo json_encode(['ok'=>true,'version'=>'V107.0 Opportunity Engine','created_or_skipped'=>count($created),'next'=>'Run executive-council-v107.php','time'=>date('c')],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);
}catch(Throwable $e){echo json_encode(['ok'=>false,'error'=>$e->getMessage(),'file'=>$e->getFile(),'line'=>$e->getLine()],JSON_PRETTY_PRINT);}
?>