<?php
ini_set('display_errors',1); error_reporting(E_ALL); require_once __DIR__.'/config.php'; header('Content-Type:text/plain');
$key=$_GET['key']??''; if(!defined('AFTER_HOURS_CRON_KEY')||!hash_equals(AFTER_HOURS_CRON_KEY,$key)){http_response_code(403);exit('Invalid key');}
$index=__DIR__.'/../index.html'; if(!file_exists($index))exit('index.html not found');
$html=file_get_contents($index); file_put_contents(__DIR__.'/../index.v21_1_backup_'.date('Ymd_His').'.html',$html);
$html=preg_replace('/href=["\']#about["\']/i','href="/about-mark-pires.php"',$html);
$html=preg_replace('/href=["\']\/#about["\']/i','href="/about-mark-pires.php"',$html);
if(strpos($html,'id="goliath-funnel-strip"')===false){$f='<section id="goliath-funnel-strip" style="background:#0f172a;padding:34px 22px;border-top:1px solid rgba(212,175,55,.18);border-bottom:1px solid rgba(212,175,55,.18)"><div style="max-width:1200px;margin:auto;display:grid;grid-template-columns:repeat(3,1fr);gap:10px"><a href="/#home-value" style="text-decoration:none;color:#f0ebe1;background:#080c14;border:1px solid rgba(212,175,55,.25);padding:22px;border-radius:14px"><strong style="color:#d4af37;font-size:24px">Selling?</strong><br>Get a real local home value review.</a><a href="/buyer-funnel.php" style="text-decoration:none;color:#f0ebe1;background:#080c14;border:1px solid rgba(212,175,55,.25);padding:22px;border-radius:14px"><strong style="color:#d4af37;font-size:24px">Buying?</strong><br>Tell Mark what you are looking for.</a><a href="/buyer-funnel.php?type=relocation" style="text-decoration:none;color:#f0ebe1;background:#080c14;border:1px solid rgba(212,175,55,.25);padding:22px;border-radius:14px"><strong style="color:#d4af37;font-size:24px">Relocating to CT?</strong><br>Compare towns, commute, lifestyle and budget.</a></div></section><style>@media(max-width:768px){#goliath-funnel-strip>div{grid-template-columns:1fr!important}}</style>'; $html=str_ireplace('<footer',$f.'<footer',$html);}
if(strpos($html,'id="mark-nap-seo"')===false){$nap='<div id="mark-nap-seo" style="font-family:Arial,sans-serif;font-size:12px;color:rgba(240,235,225,.45);line-height:1.7;margin-top:22px">Mark Pires · Coldwell Banker Realty · 1508 Post Rd, Fairfield, CT 06824 · Cell 203-247-2655 · mark.pires@cbrealty.com · Serving Fairfield, Westport, Greenwich, Old Greenwich, Stamford, Darien, New Canaan, Wilton, Easton, Norwalk and lower Fairfield County.</div>'; $html=str_ireplace('</footer>',$nap.'</footer>',$html);}
file_put_contents($index,$html); echo "Patched index.html. About links and three funnel strip added.\n";
?>