<?php
ini_set('display_errors',0); header('Content-Type: application/json; charset=utf-8');
try{require_once __DIR__.'/config.php';require_once __DIR__.'/goliath-db.php';
$key=$_GET['key']??'';$expected=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:(defined('RETELL_WEBHOOK_KEY')?RETELL_WEBHOOK_KEY:'timetomakethedonuts');
if(!hash_equals((string)$expected,(string)$key)){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'bad_key']);exit;}
function uid107($p){return function_exists('gdb_uid')?gdb_uid($p):$p.'_'.date('YmdHis').'_'.bin2hex(random_bytes(4));} function all107($s,$p=[]){try{return gdb_all($s,$p)?:[];}catch(Throwable $e){return [];}} function one107($s,$p=[]){try{return gdb_one($s,$p)?:null;}catch(Throwable $e){return null;}}
function col107($t,$c){$r=one107("SELECT COUNT(*) c FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=? AND column_name=?",[$t,$c]);return ((int)($r['c']??0))>0;} function ins107($t,$row){$safe=[];foreach($row as $k=>$v){if(col107($t,$k))$safe[$k]=$v;}return $safe?gdb_insert($t,$safe):null;}
$approved=all107("SELECT * FROM goliath_opportunity_marketplace WHERE status='approved' OR (status='council' AND priority_score>=82 AND confidence_score>=80) ORDER BY priority_score DESC LIMIT 10");$made=[];
foreach($approved as $o){if(!col107('goliath_projects','project_uid'))continue;$title='Opportunity Project: '.$o['title'];$exists=one107("SELECT project_uid FROM goliath_projects WHERE title=? LIMIT 1",[$title]);$puid=$exists['project_uid']??uid107('project');if(!$exists)ins107('goliath_projects',['project_uid'=>$puid,'title'=>$title,'project_type'=>$o['opportunity_type'],'business_unit'=>$o['business_unit'],'status'=>'active','owner_executive'=>'goliath','priority'=>$o['priority_score'],'health_score'=>$o['confidence_score'],'revenue_potential'=>$o['revenue_score']*1000,'authority_score'=>$o['authority_score'],'media_score'=>$o['media_score'],'promotion_score'=>$o['relationship_score'],'sales_score'=>$o['revenue_score'],'analytics_score'=>50,'current_phase'=>'opportunity','genome_json'=>json_encode($o,JSON_UNESCAPED_SLASHES),'why_text'=>$o['details'],'next_action'=>'Build through department collaboration.','created_at'=>gdb_now(),'updated_at'=>gdb_now()]);gdb()->exec("UPDATE goliath_opportunity_marketplace SET status='project_created', project_uid=".gdb()->quote($puid).", updated_at=NOW() WHERE id=".(int)$o['id']);$made[]=$puid;}
echo json_encode(['ok'=>true,'version'=>'V107.0 Promote Opportunities','projects_created_or_linked'=>count($made),'project_uids'=>$made,'time'=>date('c')],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);
}catch(Throwable $e){echo json_encode(['ok'=>false,'error'=>$e->getMessage(),'file'=>$e->getFile(),'line'=>$e->getLine()],JSON_PRETTY_PRINT);}
?>