<?php
require_once __DIR__.'/config.php'; require_once __DIR__.'/goliath-db.php';
if(file_exists(__DIR__.'/goliath-v77-1-knowledge-loader.php')) require_once __DIR__.'/goliath-v77-1-knowledge-loader.php';
header('Content-Type: application/json; charset=utf-8');
$key=$_POST['key']??$_GET['key']??''; $expected=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
if(!hash_equals($expected,(string)$key)){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'bad_key']);exit;}
function col($t,$c){try{$r=gdb_one("SELECT COUNT(*) c FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=? AND column_name=?",[$t,$c]);return ((int)($r['c']??0))>0;}catch(Throwable $e){return false;}}
function tbl($t){try{$r=gdb_one("SELECT COUNT(*) c FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?",[$t]);return ((int)($r['c']??0))>0;}catch(Throwable $e){return false;}}
function uid($p){return function_exists('gdb_uid')?gdb_uid($p):$p.'_'.date('YmdHis').'_'.bin2hex(random_bytes(4));}
function js($v){return json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}
function ins($t,$row){$safe=[];foreach($row as $k=>$v){if(col($t,$k))$safe[$k]=$v;}return $safe?gdb_insert($t,$safe):null;}
function promptx($exec,$title,$body,$meta=[]){return function_exists('gv771_prompt')?gv771_prompt($exec,$title,$body,$meta):$body;}
$type=trim($_POST['production_type']??'Custom');$goal=trim($_POST['goal']??'Brand Awareness');$platform=trim($_POST['platform']??'All Platforms');$aspect=trim($_POST['aspect_ratio']??'9:16');$duration=trim($_POST['duration']??'15 seconds');$style=trim($_POST['style_pack']??'Luxury Commercial');$brief=trim($_POST['brief']??'');$cta=trim($_POST['cta']??'');$title="Scorsese Studio Pro: {$type} — {$goal}";
$projectId=null;if(tbl('scorsese_studio_projects')){$projectId=ins('scorsese_studio_projects',['project_uid'=>uid('ssp'),'title'=>$title,'production_type'=>$type,'goal'=>$goal,'platform'=>$platform,'aspect_ratio'=>$aspect,'duration'=>$duration,'style_pack'=>$style,'brief'=>$brief,'cta'=>$cta,'status'=>'queued','progress'=>5,'metadata'=>js(['source'=>'Scorsese Studio Pro Wizard']),'created_at'=>gdb_now(),'updated_at'=>gdb_now()]);}
$mission="Create a ContentCreator-style production workflow for {$type}. Goal: {$goal}. Platform: {$platform}. Format: {$aspect}. Duration: {$duration}. Style: {$style}. Brief: {$brief}. CTA: {$cta}. Work as a production team: research, script, hook, storyboard, prompts, render package, thumbnails, asset factory outputs. No filler.";
$commissionId=null;if(tbl('executive_commissions')){$commissionId=ins('executive_commissions',['commission_uid'=>uid('commission'),'executive_key'=>'scorsese','executive'=>'Scorsese','title'=>$title,'description'=>$mission,'prompt'=>$mission,'status'=>'queued','priority'=>360,'progress'=>0,'current_step'=>'Studio production created','metadata'=>js(['project_id'=>$projectId,'style_pack'=>$style,'aspect_ratio'=>$aspect]),'created_at'=>gdb_now(),'updated_at'=>gdb_now()]);}
$team=['scout'=>'Research facts, proof, audience, examples, and source links for the video.','einstein'=>'Define goal logic, SEO/AEO terms, audience intent, and conversion path.','shakespeare'=>'Write script, narration, captions, and CTA copy.','columbo'=>'Create hook, title, thumbnail, retention critique, and virality score.','mozart'=>'Recommend music/audio mood, pacing, intro/outro, and sound design.','scorsese'=>'Create storyboard, cinematic prompts, render plan, thumbnail visual plan, and ComfyUI direct job if ready.','goliath'=>'Coordinate final review and mark production ready for Mark.'];
$tasks=[];foreach($team as $exec=>$role){$body="SCORSESE STUDIO PRO PRODUCTION\n\nCOMMISSION ID: {$commissionId}\nPROJECT ID: {$projectId}\nTITLE: {$title}\n\nPRODUCTION BRIEF:\n{$mission}\n\nYOUR ROLE:\n{$role}\n\nOUTPUT MUST BE ACTIONABLE AND PRODUCTION-READY. No invented facts. If tool/data is needed, say NEEDS_TOOL_ACCESS or NEEDS_VERIFIED_DATA.";$taskId=ins('local_ai_tasks',['task_uid'=>uid('lat'),'commission_id'=>$commissionId,'agent'=>ucfirst($exec),'task_type'=>'v90_scorsese_studio_pro','model'=>'goliath-local-worker','prompt'=>promptx($exec,$title,$body,['commission_id'=>$commissionId,'project_id'=>$projectId,'style_pack'=>$style,'aspect_ratio'=>$aspect]),'status'=>'queued','priority'=>($exec==='goliath'?250:360),'progress'=>0,'metadata'=>js(['commission_id'=>$commissionId,'project_id'=>$projectId,'production_type'=>$type,'expected_role'=>$role]),'created_at'=>gdb_now(),'updated_at'=>gdb_now()]);$tasks[]=['executive'=>$exec,'task_id'=>$taskId,'commission_id'=>$commissionId];}
if($projectId && $commissionId && tbl('scorsese_studio_projects') && col('scorsese_studio_projects','commission_id')){gdb_update('scorsese_studio_projects',['commission_id'=>$commissionId],'id=:id',['id'=>$projectId]);}
echo json_encode(['ok'=>true,'version'=>'V90 Scorsese Studio Pro Create','project_id'=>$projectId,'commission_id'=>$commissionId,'tasks'=>$tasks,'next'=>'Run local worker. Review Scorsese Studio Pro dashboard.','time'=>date('c')],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);
?>