<?php
require_once __DIR__.'/config.php';
require_once __DIR__.'/goliath-db.php';
$key=$_POST['key']??$_GET['key']??'';
$expected=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
if(!hash_equals($expected,(string)$key)){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'bad_key']);exit;}
function st($t){try{$r=gdb_one("SELECT COUNT(*) c FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?",[$t]);return ((int)($r['c']??0))>0;}catch(Throwable $e){return false;}}
function sc($t,$c){try{$r=gdb_one("SELECT COUNT(*) c FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=? AND column_name=?",[$t,$c]);return ((int)($r['c']??0))>0;}catch(Throwable $e){return false;}}
function si($t,$row){$safe=[];foreach($row as $k=>$v){if(sc($t,$k))$safe[$k]=$v;}return $safe?gdb_insert($t,$safe):null;}
function su($t,$id,$row){$safe=[];foreach($row as $k=>$v){if(sc($t,$k))$safe[$k]=$v;}if($safe)gdb_update($t,$safe,'id=:id',['id'=>(int)$id]);}
function sj($v){return json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}
function sn($s){return trim(preg_replace('/\s+/',' ',(string)$s));}
function sg($row,$names){foreach($names as $n){foreach($row as $k=>$v){$kk=strtolower(trim($k)); if($kk===strtolower($n) || strpos($kk,strtolower($n))!==false)return sn($v);}}return '';}
function suid($p){return function_exists('gdb_uid')?gdb_uid($p):$p.'_'.date('YmdHis').'_'.bin2hex(random_bytes(4));}
header('Content-Type: application/json; charset=utf-8');
$uploadDir=dirname(__DIR__).'/data/scout_uploads'; if(!is_dir($uploadDir))mkdir($uploadDir,0755,true);
if(empty($_FILES['csv_file'])||!is_uploaded_file($_FILES['csv_file']['tmp_name'])){http_response_code(400);echo json_encode(['ok'=>false,'error'=>'csv_file_required']);exit;}
$orig=$_FILES['csv_file']['name']??'upload.csv';$ext=strtolower(pathinfo($orig,PATHINFO_EXTENSION));
if(!in_array($ext,['csv','txt'])){http_response_code(400);echo json_encode(['ok'=>false,'error'=>'csv_or_txt_only']);exit;}
$safeName=preg_replace('/[^a-zA-Z0-9._-]/','_',pathinfo($orig,PATHINFO_FILENAME));$fileName=date('Ymd-His').'-'.$safeName.'.'.$ext;$dest=$uploadDir.'/'.$fileName;
if(!move_uploaded_file($_FILES['csv_file']['tmp_name'],$dest)){http_response_code(500);echo json_encode(['ok'=>false,'error'=>'upload_failed']);exit;}
$title=sn($_POST['dataset_title']??$safeName);$type=sn($_POST['dataset_type']??'custom');$desc=sn($_POST['description']??'');$priority=(int)($_POST['priority']??3);
$sourceId=null;if(st('internal_contact_sources')){$sourceId=si('internal_contact_sources',['source_uid'=>suid('source'),'title'=>$title,'source_name'=>$title,'dataset_type'=>$type,'source_type'=>$type,'file_name'=>$fileName,'file_path'=>$dest,'relative_path'=>'/data/scout_uploads/'.$fileName,'description'=>$desc,'priority'=>$priority,'status'=>'queued','metadata'=>sj(['uploaded_from'=>'mission_control','original_file'=>$orig,'type'=>$type]),'created_at'=>gdb_now(),'updated_at'=>gdb_now()]);}
$rowsSeen=0;$imported=0;$duplicates=0;$errors=[];
if(($handle=fopen($dest,'r'))!==false){$headers=fgetcsv($handle);if($headers){$headers=array_map(fn($h)=>trim((string)$h),$headers);while(($data=fgetcsv($handle))!==false){$rowsSeen++;if(count(array_filter($data,fn($x)=>trim((string)$x)!==''))===0)continue;$row=[];foreach($headers as $i=>$h){$row[$h]=$data[$i]??'';}$owner=sg($row,['owner_name','owner','name','full name','taxpayer','seller']);$property=sg($row,['property_address','property address','address','site address','situs','listing address']);$mailing=sg($row,['mailing_address','mailing address','owner address','tax bill address']);$town=sg($row,['town','city','municipality']);$state=sg($row,['state']);$zip=sg($row,['zip','postal']);$phone=sg($row,['phone','mobile','cell','telephone']);$email=sg($row,['email','e-mail']);$listPrice=sg($row,['list price','price','original price','expired price']);$expiredDate=sg($row,['expired','expiration','off market','cancelled','withdrawn']);if($owner===''&&$property==='')continue;if(st('internal_crm_contacts')){try{$existing=null;if($property!==''||$owner!=='')$existing=gdb_one("SELECT id FROM internal_crm_contacts WHERE COALESCE(property_address,'')=? AND COALESCE(owner_name,'')=? LIMIT 1",[$property,$owner]);if($existing){$duplicates++;continue;}$id=si('internal_crm_contacts',['contact_uid'=>suid('contact'),'source_id'=>$sourceId,'source_file'=>$fileName,'source_type'=>$type,'owner_name'=>$owner,'name'=>$owner,'property_address'=>$property,'mailing_address'=>$mailing,'town'=>$town,'city'=>$town,'state'=>$state,'zip'=>$zip,'phone'=>$phone,'existing_phone'=>$phone,'email'=>$email,'existing_email'=>$email,'previous_list_price'=>$listPrice,'expired_date'=>$expiredDate,'lead_type'=>$type,'status'=>'queued','research_status'=>'queued','relationship_status'=>'new','priority'=>$priority,'evidence'=>'Uploaded via Mission Control Scout Intake from /data/scout_uploads/'.$fileName.' row '.($rowsSeen+1),'raw_json'=>sj($row),'metadata'=>sj(['dataset_title'=>$title,'dataset_type'=>$type,'upload_file'=>$fileName]),'created_at'=>gdb_now(),'updated_at'=>gdb_now()]);if($id)$imported++;}catch(Throwable $e){$errors[]='row '.$rowsSeen.': '.$e->getMessage();}}}}else{$errors[]='No CSV headers found.';}fclose($handle);}
if($sourceId&&st('internal_contact_sources'))su('internal_contact_sources',$sourceId,['rows_seen'=>$rowsSeen,'imported_count'=>$imported,'duplicate_count'=>$duplicates,'status'=>'queued','updated_at'=>gdb_now()]);
$commissionId=null;$taskId=null;if(st('executive_commissions')){$goal="Complete at least 20 homeowner dossiers from dataset '{$title}' before moving to a new major research commission.";$commissionId=si('executive_commissions',['commission_uid'=>suid('commission'),'executive_key'=>'scout','executive'=>'Scout','title'=>'Scout Dossier Sprint: '.$title,'description'=>$goal,'prompt'=>$goal,'status'=>'queued','priority'=>320+$priority,'progress'=>0,'current_step'=>'Dataset uploaded and queued for 20 dossier sprint','metadata'=>sj(['source_id'=>$sourceId,'dataset_title'=>$title,'dataset_type'=>$type,'daily_dossier_goal'=>20]),'created_at'=>gdb_now(),'updated_at'=>gdb_now()]);}
if(st('local_ai_tasks')){$prompt="SCOUT INTELLIGENCE ENGINE — 20 DOSSIER SPRINT\n\nDATASET: {$title}\nSOURCE ID: {$sourceId}\nTYPE: {$type}\nDESCRIPTION: {$desc}\n\nDo not move to another major research commission until at least 20 homeowner dossiers from this dataset are ready for Mark. Include available contact info, listing/property context, neighborhood intelligence, evidence, confidence, suggested opening, and status READY_FOR_MARK or NEEDS_MORE_RESEARCH. No invented personal facts.";$taskId=si('local_ai_tasks',['task_uid'=>suid('lat'),'commission_id'=>$commissionId,'agent'=>'Scout','task_type'=>'v82_2_scout_20_dossier_sprint','model'=>'goliath-local-worker','prompt'=>$prompt,'status'=>'queued','priority'=>350+$priority,'progress'=>0,'metadata'=>sj(['source_id'=>$sourceId,'dataset_title'=>$title,'dataset_type'=>$type,'daily_dossier_goal'=>20,'file'=>'/data/scout_uploads/'.$fileName]),'created_at'=>gdb_now(),'updated_at'=>gdb_now()]);}
if(strpos($_SERVER['HTTP_ACCEPT']??'','text/html')!==false){header('Location: /dashboard/goliath-mission-control.php?scout_upload=success&source_id='.urlencode((string)$sourceId));exit;}
echo json_encode(['ok'=>true,'version'=>'V82.2 Scout CSV Intake','source_id'=>$sourceId,'commission_id'=>$commissionId,'task_id'=>$taskId,'file'=>'/data/scout_uploads/'.$fileName,'rows_seen'=>$rowsSeen,'imported'=>$imported,'duplicates'=>$duplicates,'errors'=>$errors,'next'=>'Scout has been queued for a 20-dossier sprint.','time'=>date('c')],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);
?>
