<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function money($n){return '$'.number_format((float)$n,0);}
function sb152d($m,$ep,$p=null){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$m,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json','Prefer: return=representation'],CURLOPT_TIMEOUT=>25]);
  if($p!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($p));
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$rows=sb152d('GET','traffic_performance?select=*&order=traffic_date.desc,traffic_score.desc&limit=200');
$briefs=sb152d('GET','traffic_scaling_briefings?select=*&order=created_at.desc&limit=5');
$brief=$briefs[0]??[];
$latestDate=$rows[0]['traffic_date']??date('Y-m-d');
$today=array_values(array_filter($rows,fn($r)=>($r['traffic_date']??'')===$latestDate));
$stats=['sources'=>count($today),'leads'=>0,'calls'=>0,'appointments'=>0,'commission'=>0];
foreach($today as $r){$stats['leads']+=(int)($r['lead_count']??0);$stats['calls']+=(int)($r['call_count']??0);$stats['appointments']+=(int)($r['appointment_count']??0);$stats['commission']+=(float)($r['estimated_commission']??0);}
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>V15.2 Traffic Scaling Director PRO</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:38px}.wrap{max-width:1800px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:26px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{border:0;display:inline-block;background:#c8a96e;color:#111;text-decoration:none;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px;cursor:pointer}.light{background:#f2efe8;color:#111}.layout{display:grid;grid-template-columns:1fr .34fr;gap:18px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:12px;border-bottom:1px solid #eee;font-size:14px;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:#777;background:#faf9f6}.muted{color:#777;font-size:13px}pre{white-space:pre-wrap;background:#111;color:#fff;padding:16px;border-radius:12px}.score{font-size:30px;font-weight:900;color:#c8a96e}.scale{font-weight:900;color:#087b30}.optimize{font-weight:900;color:#9a6200}.watch,.seed{font-weight:900;color:#666}@media(max-width:1000px){.grid,.layout{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">V15.2 PRO Traffic Scaling Director</div><div>Jessica measures which funnels, creative, calls, and seller sources deserve more effort or budget</div></div><main class="wrap">
<p><a class="btn" target="_blank" href="/lead-engine/build-traffic-scaling-director.php?key=<?=h($cronKey)?>">Build Traffic Brief</a><a class="btn light" href="/dashboard/seller-acquisition-director.php">Seller Director</a><a class="btn light" href="/dashboard/creative-intelligence-director.php">Creative Director</a><a class="btn light" href="/dashboard/voice-concierge-center.php">Voice Concierge</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=h($stats['sources'])?></div>Sources</div><div class="kpi"><div class="n"><?=h($stats['leads'])?></div>Leads</div><div class="kpi"><div class="n"><?=h($stats['calls'])?></div>Calls</div><div class="kpi"><div class="n"><?=h($stats['appointments'])?></div>Appointments</div><div class="kpi"><div class="n"><?=money($stats['commission'])?></div>Commission</div></section>
<div class="layout"><section class="panel"><h2>Traffic Source Rankings</h2><table><tr><th>Score</th><th>Source</th><th>Signals</th><th>Revenue</th><th>Recommendation</th></tr><?php foreach($today as $r):?><tr><td><div class="score"><?=h($r['traffic_score'])?></div><div class="<?=h($r['scale_recommendation'])?>"><?=h($r['scale_recommendation'])?></div></td><td><strong><?=h($r['source_name'])?></strong><div class="muted"><?=h($r['source_type'])?><br><?=h($r['traffic_date'])?></div></td><td class="muted">Leads <?=h($r['lead_count'])?><br>Qualified <?=h($r['qualified_count'])?><br>Calls <?=h($r['call_count'])?><br>Appts <?=h($r['appointment_count'])?><br>Ready <?=h($r['ready_to_contact_count'])?><br>Publish Ready <?=h($r['publish_ready_count'])?></td><td><?=money($r['pipeline_value'])?><div class="muted">Commission <?=money($r['estimated_commission'])?><br>Expected <?=money($r['expected_value'])?></div></td><td><?=h($r['recommended_action'])?></td></tr><?php endforeach;?></table></section><section class="panel"><h2>Jessica Traffic Brief</h2><div style="padding:16px"><pre><?=h($brief['briefing_text']??'Run Build Traffic Brief to create summary.')?></pre></div></section></div>
</main></body></html>