<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function money($n){return '$'.number_format((float)$n,0);}
function sb154d($m,$ep,$p=null){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$m,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json','Prefer: return=representation'],CURLOPT_TIMEOUT=>25]);
  if($p!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($p));
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $id=$_POST['id']??''; $status=$_POST['status']??'';
  if($id && in_array($status,['approved','launched','paused','archived','draft'],true)){
    sb154d('PATCH','ad_launch_campaigns?id=eq.'.rawurlencode($id),['status'=>$status,'approved_for_launch'=>in_array($status,['approved','launched'],true),'updated_at'=>date('c')]);
    $msg='Campaign updated.';
  }
}
$rows=sb154d('GET','ad_launch_campaigns?select=*&status=in.(draft,approved,launched)&order=launch_score.desc,created_at.desc&limit=300');
$briefs=sb154d('GET','ad_launch_briefings?select=*&order=created_at.desc&limit=5');
$brief=$briefs[0]??[];
$stats=['total'=>count($rows),'launch'=>0,'improve'=>0,'hold'=>0,'approved'=>0,'budget'=>0];
foreach($rows as $r){if(($r['launch_recommendation']??'')==='launch'){$stats['launch']++;$stats['budget']+=(float)($r['recommended_budget']??0);}if(($r['launch_recommendation']??'')==='improve')$stats['improve']++;if(($r['launch_recommendation']??'')==='hold')$stats['hold']++;if(!empty($r['approved_for_launch']))$stats['approved']++;}
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>V15.4 Ad Launch Director</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:38px}.wrap{max-width:1800px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:26px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{border:0;display:inline-block;background:#c8a96e;color:#111;text-decoration:none;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px;cursor:pointer}.light{background:#f2efe8;color:#111}.layout{display:grid;grid-template-columns:1fr .34fr;gap:18px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:12px;border-bottom:1px solid #eee;font-size:14px;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:#777;background:#faf9f6}.muted{color:#777;font-size:13px}pre{white-space:pre-wrap;background:#111;color:#fff;padding:16px;border-radius:12px}.score{font-size:30px;font-weight:900;color:#c8a96e}.launch{color:#087b30;font-weight:900}.improve{color:#9a6200;font-weight:900}.hold,.reject{color:#9a0000;font-weight:900}@media(max-width:1000px){.grid,.layout{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">V15.4 Ad Launch Director</div><div>Jessica converts Creative Intelligence, Content Mine, Traffic Scaling, and Seller Acquisition into launch-ready ad campaigns</div></div><main class="wrap"><?php if($msg):?><div class="panel" style="padding:16px"><?=h($msg)?></div><?php endif;?>
<p><a class="btn" target="_blank" href="/lead-engine/build-ad-launch-director.php?key=<?=h($cronKey)?>">Build Ad Launch Brief</a><a class="btn light" href="/dashboard/creative-intelligence-director.php">Creative</a><a class="btn light" href="/dashboard/content-mine-director.php">Content Mine</a><a class="btn light" href="/dashboard/traffic-scaling-director.php">Traffic</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=h($stats['total'])?></div>Campaigns</div><div class="kpi"><div class="n"><?=h($stats['launch'])?></div>Launch</div><div class="kpi"><div class="n"><?=h($stats['improve'])?></div>Improve</div><div class="kpi"><div class="n"><?=h($stats['hold'])?></div>Hold</div><div class="kpi"><div class="n"><?=h($stats['approved'])?></div>Approved</div><div class="kpi"><div class="n"><?=money($stats['budget'])?></div>/day</div></section>
<div class="layout"><section class="panel"><h2>Campaign Queue</h2><table><tr><th>Score</th><th>Campaign</th><th>Copy</th><th>Creative Direction</th><th>Action</th></tr><?php foreach($rows as $r):?><tr><td><div class="score"><?=h($r['launch_score'])?></div><div class="<?=h($r['launch_recommendation'])?>"><?=h($r['launch_recommendation'])?></div><div class="muted"><?=money($r['recommended_budget'])?>/day</div></td><td><strong><?=h($r['campaign_name'])?></strong><div class="muted"><?=h($r['campaign_type'])?> / <?=h($r['brand_pillar'])?><br><?=h($r['target_town'])?><br>Status: <?=h($r['status'])?></div></td><td><strong><?=h($r['headline'])?></strong><div class="muted"><?=h($r['primary_text'])?><br>CTA: <?=h($r['cta'])?></div></td><td><?=h($r['image_direction'])?><div class="muted">Prompt: <?=h($r['creative_prompt'])?></div></td><td><form method="post"><input type="hidden" name="id" value="<?=h($r['id'])?>"><button class="btn" name="status" value="approved">Approve</button><button class="btn light" name="status" value="launched">Launched</button><button class="btn light" name="status" value="paused">Pause</button><button class="btn light" name="status" value="archived">Archive</button></form></td></tr><?php endforeach;?></table></section><section class="panel"><h2>Jessica Ad Brief</h2><div style="padding:16px"><pre><?=h($brief['briefing_text']??'Run Build Ad Launch Brief to create briefing.')?></pre></div></section></div>
</main></body></html>