<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sb1110d($ep){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPGET=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY],CURLOPT_TIMEOUT=>25]);
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$responses=sb1110d('appointment_response_inbox?select=*&order=created_at.desc&limit=100');
$appts=sb1110d('appointment_requests?select=*&status=in.(offered,confirmed,requested)&order=created_at.desc&limit=100');
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Appointment Response Intake V11.10</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:36px}.wrap{max-width:1450px;margin:auto;padding:26px}.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001;margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{display:inline-block;background:#c8a96e;color:#111;text-decoration:none;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px}.light{background:#f2efe8;color:#111}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:11px;border-bottom:1px solid #eee;font-size:14px;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:#777;background:#faf9f6}.layout{display:grid;grid-template-columns:1fr 1fr;gap:18px}.muted{color:#777;font-size:13px}@media(max-width:900px){.layout{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">Appointment Response Intake V11.10</div><div>Parses Option 1 / 2 / 3 replies and prepares appointments for calendar booking</div></div><main class="wrap">
<p><a class="btn" target="_blank" href="/lead-engine/test-google-calendar.php">Test Calendar Patch</a><a class="btn light" href="/dashboard/appointment-automation.php">Appointment Automation</a></p>
<div class="layout"><section class="panel"><h2>Recent Client Responses</h2><table><tr><th>Time</th><th>Client</th><th>Message</th><th>Parsed</th><th>Status</th></tr><?php foreach($responses as $r):?><tr><td><?=h($r['created_at'])?></td><td><?=h($r['name'])?><div class="muted"><?=h($r['phone'])?><br><?=h($r['email'])?></div></td><td><?=h($r['raw_message'])?></td><td><?=h($r['parsed_intent'])?><br>Option <?=h($r['parsed_option'])?><br><?=h($r['confidence'])?>%</td><td><?=h($r['status'])?></td></tr><?php endforeach;?></table></section><section class="panel"><h2>Offered / Active Appointments</h2><table><tr><th>Lead</th><th>Status</th><th>Response</th><th>Manual Intake Test</th></tr><?php foreach($appts as $a):?><tr><td><strong><?=h($a['name'])?></strong><div class="muted"><?=h($a['phone'])?><br><?=h($a['email'])?></div></td><td><?=h($a['status'])?><br><?=h($a['automation_status']??'')?></td><td><?=h($a['last_client_response']??'')?><div class="muted"><?=h($a['response_intake_status']??'')?></div></td><td><a class="btn light" target="_blank" href="/lead-engine/appointment-response-intake.php?key=<?=h($cronKey)?>&phone=<?=h(urlencode($a['phone']??''))?>&message=Option%201">Test Option 1</a></td></tr><?php endforeach;?></table></section></div>
</main></body></html>