<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sb116perf($ep){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPGET=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY],CURLOPT_TIMEOUT=>25]);
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$profiles=sb116perf('builder_performance_profiles?select=*&order=expected_referral_value.desc,response_rate.desc&limit=300');
$stats=['tier1'=>0,'tier2'=>0,'tier3'=>0,'expected'=>0,'closed'=>0];
foreach($profiles as $p){$t=strtolower(str_replace(' ','',$p['tier']??'Tier 3'));if(isset($stats[$t]))$stats[$t]++;$stats['expected']+=(float)($p['expected_referral_value']??0);$stats['closed']+=(float)($p['closed_referral_value']??0);}
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Builder Performance V11.6</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:36px}.wrap{max-width:1450px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:34px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{display:inline-block;background:#c8a96e;color:#111;text-decoration:none;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:11px;border-bottom:1px solid #eee;font-size:14px;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:#777;background:#faf9f6}.muted{color:#777;font-size:13px}@media(max-width:900px){.grid{grid-template-columns:1fr}.wrap{padding:14px}}
</style></head><body><div class="header"><div class="brand">Builder Performance V11.6</div><div>Builder memory, response rates, tiers, preferences, and revenue history</div></div><main class="wrap">
<p><a class="btn" target="_blank" href="/lead-engine/build-builder-performance.php?key=<?=h($cronKey)?>">Build Performance Profiles</a> <a class="btn" href="/dashboard/builder-followups.php">Builder Followups</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=h(count($profiles))?></div>Builders</div><div class="kpi"><div class="n"><?=h($stats['tier1'])?></div>Tier 1</div><div class="kpi"><div class="n"><?=h($stats['tier2'])?></div>Tier 2</div><div class="kpi"><div class="n">$<?=h(number_format($stats['expected']))?></div>Expected</div><div class="kpi"><div class="n">$<?=h(number_format($stats['closed']))?></div>Closed</div></section>
<section class="panel"><h2>Builder Profiles</h2><table><tr><th>Builder</th><th>Tier</th><th>Activity</th><th>Rates</th><th>Revenue</th><th>Preferences</th></tr><?php foreach($profiles as $p):$towns=is_string($p['preferred_towns']??null)?json_decode($p['preferred_towns'],true):($p['preferred_towns']??[]);$types=is_string($p['preferred_opportunity_types']??null)?json_decode($p['preferred_opportunity_types'],true):($p['preferred_opportunity_types']??[]);if(!is_array($towns))$towns=[];if(!is_array($types))$types=[];?><tr><td><strong><?=h($p['builder_name'])?></strong><div class="muted"><?=h($p['company'])?><br><?=h($p['phone'])?><br><?=h($p['email'])?></div></td><td><strong><?=h($p['tier'])?></strong></td><td>Matches <?=h($p['total_matches'])?><br>Intros <?=h($p['total_intros'])?><br>Responses <?=h($p['total_responses'])?><br>Active <?=h($p['active_pipeline'])?><br>Closed <?=h($p['total_closed'])?></td><td>Response <?=h(round(((float)$p['response_rate'])*100,1))?>%<br>Conversion <?=h(round(((float)$p['conversion_rate'])*100,1))?>%<br>Close <?=h(round(((float)$p['close_rate'])*100,1))?>%</td><td>Expected $<?=h(number_format((float)$p['expected_referral_value']))?><br>Potential $<?=h(number_format((float)$p['total_referral_potential']))?><br>Closed $<?=h(number_format((float)$p['closed_referral_value']))?></td><td><strong>Towns</strong><br><?php foreach(array_slice($towns,0,4) as $t):?><?=h($t['name']??'')?> (<?=h($t['count']??0)?>)<br><?php endforeach;?><br><strong>Types</strong><br><?php foreach(array_slice($types,0,4) as $t):?><?=h($t['name']??'')?> (<?=h($t['count']??0)?>)<br><?php endforeach;?><div class="muted"><?=h($p['performance_notes'])?></div></td></tr><?php endforeach;?></table></section>
</main></body></html>