<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sb155($ep){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPGET=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY],CURLOPT_TIMEOUT=>25]);
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$calls=sb155('conversation_intelligence_calls?select=*&order=call_date.desc&limit=200');
$scripts=sb155('conversation_script_variants?select=*&active=eq.true&order=lead_type.asc,performance_score.desc&limit=100');
$briefs=sb155('conversation_learning_briefings?select=*&order=created_at.desc&limit=10');
$brief=$briefs[0]??[];
$stats=['calls'=>count($calls),'appts'=>0,'followups'=>0,'positive'=>0,'negative'=>0];
foreach($calls as $c){if(!empty($c['appointment_set']))$stats['appts']++;if(!empty($c['follow_up_needed']))$stats['followups']++;if(($c['sentiment']??'')==='positive')$stats['positive']++;if(($c['sentiment']??'')==='negative')$stats['negative']++;}
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Conversation Intelligence V12.15</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:38px}.wrap{max-width:1600px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:30px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{display:inline-block;background:#c8a96e;color:#111;text-decoration:none;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px}.light{background:#f2efe8;color:#111}.layout{display:grid;grid-template-columns:1fr .45fr;gap:18px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:11px;border-bottom:1px solid #eee;font-size:14px;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:#777;background:#faf9f6}.muted{color:#777;font-size:13px}pre{white-space:pre-wrap;background:#111;color:#fff;padding:16px;border-radius:12px}@media(max-width:1000px){.grid,.layout{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">Jessica Conversation Intelligence V12.15</div><div>Call transcripts, objections, outcomes, script variants, and conversion learning</div></div><main class="wrap">
<p><a class="btn" target="_blank" href="/lead-engine/seed-conversation-scripts.php?key=<?=h($cronKey)?>">Seed Scripts</a><a class="btn light" target="_blank" href="/lead-engine/build-conversation-briefing.php?key=<?=h($cronKey)?>">Build Learning Brief</a><a class="btn light" href="/dashboard/hunter-mode.php">Hunter</a><a class="btn light" href="/dashboard/daily-command-center.php">Command Center</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=h($stats['calls'])?></div>Calls</div><div class="kpi"><div class="n"><?=h($stats['appts'])?></div>Appointments</div><div class="kpi"><div class="n"><?=h($stats['followups'])?></div>Follow-Ups</div><div class="kpi"><div class="n"><?=h($stats['positive'])?></div>Positive</div><div class="kpi"><div class="n"><?=h($stats['negative'])?></div>Negative</div></section>
<div class="layout"><section class="panel"><h2>Recent Call Intelligence</h2><table><tr><th>Lead</th><th>Scores</th><th>Outcome</th><th>Next Action</th></tr><?php foreach($calls as $c):?><tr><td><strong><?=h($c['name']?:$c['phone'])?></strong><div class="muted"><?=h($c['lead_type'])?> · <?=h($c['town'])?><br><?=h($c['call_date'])?></div></td><td>Motivation <?=h($c['motivation_score'])?><br>Urgency <?=h($c['urgency_score'])?><br>Appt <?=h($c['appointment_intent_score'])?></td><td><?=h($c['outcome'])?><div class="muted"><?=h($c['sentiment'])?><br><?=h($c['objection_type'])?></div></td><td><?=h($c['recommended_next_action'])?></td></tr><?php endforeach;?></table></section>
<section class="panel"><h2>Learning Brief</h2><div style="padding:16px"><pre><?=h($brief['briefing_text']??'No briefing yet. Click Build Learning Brief.')?></pre></div><h2>Active Script Variants</h2><table><tr><th>Script</th><th>Type</th><th>Score</th></tr><?php foreach($scripts as $s):?><tr><td><strong><?=h($s['script_name'])?></strong><div class="muted"><?=h($s['audience'])?></div></td><td><?=h($s['lead_type'])?></td><td><?=h($s['performance_score'])?></td></tr><?php endforeach;?></table></section></div>
</main></body></html>