<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sb12d($ep){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPGET=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY],CURLOPT_TIMEOUT=>25]);
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$sources=sb12d('discovery_intelligence_sources?select=*&order=priority_score.desc,created_at.desc&limit=300');
$opps=sb12d('discovery_opportunity_queue?select=*&order=priority_score.desc,created_at.desc&limit=300');
$cron=sb12d('cron_schedule_registry?select=*&order=recommended_time.asc&limit=100');
$stats=['sources'=>count($sources),'opps'=>count($opps),'sellers'=>0,'buyers'=>0,'builders'=>0,'relocation'=>0,'developers'=>0];
foreach($opps as $o){$t=$o['opportunity_type']??'';if(isset($stats[$t]))$stats[$t]++;}
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>V12 Discovery Intelligence</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:36px}.wrap{max-width:1500px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:30px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{display:inline-block;background:#c8a96e;color:#111;text-decoration:none;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px}.light{background:#f2efe8;color:#111}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:11px;border-bottom:1px solid #eee;font-size:14px;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:#777;background:#faf9f6}.muted{color:#777;font-size:13px}.layout{display:grid;grid-template-columns:1fr .45fr;gap:18px}@media(max-width:1000px){.grid,.layout{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">V12 Discovery Intelligence</div><div>Jessica buyer/seller/builder/developer opportunity discovery planner</div></div><main class="wrap">
<p><a class="btn" target="_blank" href="/lead-engine/build-discovery-intelligence.php?key=<?=h($cronKey)?>">Build V12 Discovery</a><a class="btn light" href="/dashboard/overnight-lead-research.php">Overnight Research</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=h($stats['sources'])?></div>Sources</div><div class="kpi"><div class="n"><?=h($stats['opps'])?></div>Opportunities</div><div class="kpi"><div class="n"><?=h($stats['sellers'])?></div>Sellers</div><div class="kpi"><div class="n"><?=h($stats['buyers'])?></div>Buyers</div><div class="kpi"><div class="n"><?=h($stats['relocation'])?></div>Relocation</div><div class="kpi"><div class="n"><?=h($stats['builders']+$stats['developers'])?></div>Builder/Dev</div></section>
<div class="layout"><section class="panel"><h2>Discovery Opportunity Queue</h2><table><tr><th>Score</th><th>Market</th><th>Offer</th><th>Ad Angle</th><th>Compliance</th></tr><?php foreach($opps as $o):?><tr><td><strong><?=h($o['priority_score'])?></strong><div class="muted"><?=h($o['opportunity_type'])?></div></td><td><?=h($o['market'])?><div class="muted"><?=h($o['town'])?><br><?=h($o['audience'])?></div></td><td><strong><?=h($o['offer'])?></strong><div class="muted"><?=h($o['landing_page'])?></div></td><td><?=h($o['ad_angle'])?></td><td><?=h($o['compliance_status'])?><div class="muted"><?=h($o['notes'])?></div></td></tr><?php endforeach;?></table></section>
<section class="panel"><h2>Cron Schedule</h2><table><tr><th>Job</th><th>Time</th><th>URL</th></tr><?php foreach($cron as $c):?><tr><td><strong><?=h($c['job_name'])?></strong><div class="muted"><?=h($c['notes'])?></div></td><td><?=h($c['recommended_time'])?></td><td><small><?=h($c['job_url'])?></small></td></tr><?php endforeach;?></table></section></div>
</main></body></html>