<?php
session_start();
require_once __DIR__.'/../lead-engine/config.php';
require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/executive-office.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($sql,$p=[]){try{return gdb_all($sql,$p)?:[];}catch(Throwable $e){return [];}}
function one($sql,$p=[]){try{return gdb_one($sql,$p)?:[];}catch(Throwable $e){return [];}}

$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$exec=strtolower(preg_replace('/[^a-z0-9_\-]+/','',$_GET['exec']??'shakespeare'));
if($exec==='scorsese'){header('Location:/dashboard/scorsese-media-center.php');exit;}

$cfg=[
'shakespeare'=>['✒️','Shakespeare','Writing Studio','Chief Storyteller & Publishing Officer','Blogs, articles, pages, captions, newsletters, and publish-ready copy.','Create New Article','Write a publish-ready Fairfield County seller article with a strong CTA to the home valuation funnel.'],
'scout'=>['🧭','Scout','Lead Command Center','Chief Intelligence & Lead Discovery Officer','Verified leads, phone/email research, source evidence, and CRM progress.','Research Contacts','Find verified phone numbers and emails for the next high-priority homeowner batch. No fabricated data.'],
'jessica'=>['💬','Jessica','Outreach Studio','Chief Communications Officer','Warm emails, follow-ups, newsletters, venue/speaking outreach, and relationship-first messages.','Create Outreach','Write a warm human-touch email for a verified opportunity.'],
'prospector'=>['⛏️','Prospector','Opportunity Lab','Chief Opportunity & Partnerships Officer','Speaking, podcasts, press, sponsors, venues, wineries, and verified contacts.','Find Opportunities','Find verified speaking, podcast, press, sponsor, venue, or winery opportunities with URLs and contact paths.'],
'einstein'=>['📊','Einstein','SEO / AEO Lab','Chief Analytics & Optimization Officer','Schema, AEO, SEO, internal links, funnel fixes, and conversion improvements.','Run Audit','Audit MarkPires.com for SEO/AEO improvements that can generate real leads.'],
'columbo'=>['🕵️','Columbo','YouTube Growth Lab','Chief Archive & YouTube Growth Officer','Titles, hooks, descriptions, chapters, thumbnails, virality scoring, and clips.','Create YouTube Package','Create a viral title, hook, description, and thumbnail direction.'],
'rockefeller'=>['💰','Rockefeller','Revenue Lab','Chief Revenue Officer','ROI, revenue projection, high-value calls, deal priority, and monetization moves.','Prioritize Revenue','Score current opportunities by revenue potential and give Mark the first three money moves.'],
'pandora'=>['🌎','Pandora','Partnership Lab','Chief Expansion & Partnerships Officer','Expansion ideas, JV opportunities, co-marketing, sponsors, and creative revenue doors.','Package Partnership','Create a verified partnership package with pitch angle and next action.'],
'mozart'=>['🎼','Mozart','Audio Lab','Chief Music & Audio Officer','Music cues, hooks, voiceover beds, podcast audio, and sonic branding.','Create Audio Direction','Create music/audio direction for a premium social video.'],
'goliath'=>['🏛️','Goliath','Executive Council','Operating System Chairman','Executive Council, morning priorities, mission coordination, bottlenecks, and assignments.','Run Council Plan','Create tomorrow morning’s top operating plan with teams and first actions.']
];
if(!isset($cfg[$exec]))$exec='shakespeare';
[$icon,$name,$studio,$title,$sub,$promptTitle,$placeholder]=$cfg[$exec];

function legacy($a){$t=(string)($a['title']??'');$s=(string)($a['output_summary']??'');$d=(string)($a['deliverable_type']??'');$e=(string)($a['evidence_status']??'');return $e==='legacy_archive'||in_array($d,['legacy_completion','legacy_brief'],true)||stripos($t,'Production Mission:')!==false||stripos($s,'Legacy worker completion backfilled')!==false||stripos($s,'CLICKABLE_OUTPUTS')!==false;}
function bodytxt($a){foreach(['asset_html','html','body','content','output_full','output','result','output_summary'] as $k){if(isset($a[$k])&&trim((string)$a[$k])!=='')return (string)$a[$k];}return '';}
function urlx($a){foreach(['output_url','file_url','url','public_url'] as $k){if(isset($a[$k])&&trim((string)$a[$k])!=='')return trim((string)$a[$k]);}return '';}
function atype($a,$exec){$d=strtolower((string)($a['deliverable_type']??''));$t=strtolower((string)($a['title']??''));if(str_contains($d,'blog')||str_contains($d,'article')||str_contains($d,'page'))return'Article';if(str_contains($d,'email')||str_contains($t,'email'))return'Email';if(str_contains($d,'lead')||str_contains($d,'crm')||$exec==='scout')return'Lead List';if(str_contains($d,'seo')||str_contains($d,'schema'))return'SEO Fix';if(str_contains($d,'opportunity')||str_contains($d,'sponsor')||str_contains($d,'speaking'))return'Opportunity';if(str_contains($d,'revenue')||str_contains($d,'roi'))return'Revenue';if(str_contains($d,'youtube')||str_contains($d,'thumbnail'))return'YouTube';if(str_contains($d,'audio')||str_contains($d,'music'))return'Audio';return ucfirst($d?:'Asset');}

$all=rows("SELECT * FROM goliath_deliverables WHERE executive_key=? ORDER BY created_at DESC,id DESC LIMIT 180",[$exec]);
$assets=array_values(array_filter($all,fn($a)=>!legacy($a)));
$selectedId=(int)($_GET['asset_id']??0);$selected=null;foreach($assets as $a){if((int)$a['id']===$selectedId){$selected=$a;break;}}if(!$selected&&count($assets))$selected=$assets[0];

$contacts=[];if($exec==='scout')$contacts=rows("SELECT * FROM internal_crm_contacts ORDER BY updated_at DESC,id DESC LIMIT 250");
$council=[];$missions=[];if($exec==='goliath'){$council=rows("SELECT * FROM goliath_council_sessions ORDER BY created_at DESC LIMIT 20");$missions=rows("SELECT * FROM goliath_missions ORDER BY created_at DESC LIMIT 40");}
$done=count($assets);$hidden=max(0,count($all)-$done);
?>
<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($name)?> Studio</title><link rel="stylesheet" href="/dashboard/assets/goliath-v33.css?v=33"><link rel="stylesheet" href="/dashboard/assets/goliath-v45-final.css?v=456"><style>
body{background:#030712;color:#fff}.hero{background:radial-gradient(circle at 18% 0%,rgba(212,175,55,.22),transparent 32%),linear-gradient(135deg,#111827,#050816);border:1px solid rgba(212,175,55,.35);border-radius:24px;padding:22px;margin-bottom:14px}.hero h1{margin:0;font-size:42px;color:#f5d48b}.hero p{color:#cbd5e1;max-width:900px}.topGrid{display:grid;grid-template-columns:minmax(0,1.25fr) 430px;gap:14px;align-items:start}.screenBox,.promptBox,.workBox{background:#07111f;border:1px solid rgba(255,255,255,.12);border-radius:22px;padding:16px}.screen{background:#020617;border:1px solid rgba(212,175,55,.35);border-radius:18px;min-height:520px;overflow:auto}.screenInner{padding:22px}.doc{background:#fff;color:#111827;border-radius:16px;padding:28px;line-height:1.65;font-size:17px;min-height:450px}.empty{height:440px;display:flex;align-items:center;justify-content:center;text-align:center;color:#94a3b8;flex-direction:column}.empty strong{color:#f5d48b;font-size:24px}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.kpi{background:#07111f;border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:12px}.kpi b{display:block;color:#f5d48b;font-size:26px}.kpi span{color:#94a3b8;font-size:12px;text-transform:uppercase;font-weight:900}.sideStack{display:grid;gap:14px}textarea,input,select{width:100%;box-sizing:border-box;background:#020617;color:#fff;border:1px solid rgba(255,255,255,.16);border-radius:13px;padding:11px;margin:7px 0;font-family:inherit}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.btn.small{padding:8px 10px;font-size:12px}.workList{display:grid;gap:8px;max-height:520px;overflow:auto}.workItem{display:block;text-decoration:none;color:#fff;background:#020617;border:1px solid rgba(255,255,255,.12);border-radius:14px;padding:10px}.workItem:hover,.workItem.active{border-color:#d4af37}.workItem strong{display:block;color:#f5d48b}.workItem span{font-size:12px;color:#94a3b8}.badge{display:inline-block;border-radius:999px;padding:4px 8px;font-size:11px;font-weight:1000;background:#14532d;color:#dcfce7;margin-bottom:8px}.meta{color:#94a3b8;font-size:12px}.tableWrap{overflow:auto;background:#020617;border-radius:16px;border:1px solid rgba(255,255,255,.12)}table{width:100%;min-width:1000px;border-collapse:collapse}th,td{border-bottom:1px solid rgba(255,255,255,.1);padding:9px;text-align:left;font-size:13px}th{color:#d4af37;background:#0f172a}.split{display:grid;grid-template-columns:1fr 1fr;gap:10px}.result{color:#cbd5e1;margin-top:8px;white-space:pre-wrap}
@media(max-width:1050px){.topGrid{grid-template-columns:1fr}.kpis{grid-template-columns:repeat(2,1fr)}.hero h1{font-size:34px}.split{grid-template-columns:1fr}}
</style></head><body><div class="shell"><?php @require __DIR__.'/includes/goliath-sidebar-v33.php'; ?><main class="main">
<section class="hero"><h1><?=h($icon)?> <?=h($name)?> <?=h($studio)?></h1><h3><?=h($title)?></h3><p><?=h($sub)?></p><div class="actions"><a class="btn dark" href="/dashboard/goliath-mission-control.php">Mission Control</a><a class="btn" href="/dashboard/executive-home.php">Executive Home</a><a class="btn" href="/dashboard/goliath-missions.php">Team Missions</a></div></section>
<section class="kpis"><div class="kpi"><b><?=h($done)?></b><span>Usable Assets</span></div><div class="kpi"><b><?=h($hidden)?></b><span>Hidden Briefs</span></div><div class="kpi"><b><?=h($exec==='scout'?count($contacts):($exec==='goliath'?count($missions):0))?></b><span><?=h($exec==='scout'?'CRM Rows':($exec==='goliath'?'Missions':'Queue'))?></span></div><div class="kpi"><b>V81</b><span>Studio Mode</span></div></section>
<section class="topGrid"><div class="screenBox"><h2>Preview Monitor</h2><div class="screen">
<?php if($exec==='scout'): ?><div class="screenInner"><h2>Scout CRM Preview</h2><p class="meta">Speed to lead: call/email, assign Jessica, export next.</p><div class="tableWrap"><table><thead><tr><th>Owner</th><th>Property</th><th>Phone</th><th>Email</th><th>Status</th><th>Evidence</th></tr></thead><tbody><?php foreach($contacts as $c): ?><tr><td><?=h($c['owner_name']??'')?></td><td><?=h($c['property_address']??'')?></td><td><?=h($c['phone_1']??'')?></td><td><?=h($c['email_1']??'')?></td><td><?=h($c['research_status']??'')?></td><td><?=h(mb_substr((string)($c['evidence']??''),0,90))?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php elseif($exec==='goliath'&&count($council)): $s=$council[0]; ?><div class="screenInner"><div class="doc"><h1><?=h($s['title']??'Executive Council')?></h1><pre style="white-space:pre-wrap;font-family:inherit"><?=h($s['morning_brief']??'')?></pre></div></div>
<?php elseif($selected): $url=urlx($selected);$txt=bodytxt($selected); ?><div class="screenInner"><div class="badge"><?=h(atype($selected,$exec))?></div><h2><?=h($selected['title']??'Selected Asset')?></h2><p class="meta">#<?=h($selected['id'])?> · <?=h($selected['deliverable_type']??'asset')?> · <?=h($selected['created_at']??'')?></p><?php if($url): ?><?php if(preg_match('/\.(mp4|webm|mov)(\?|$)/i',$url)): ?><video controls style="width:100%;border-radius:16px;background:#000" src="<?=h($url)?>"></video><?php elseif(preg_match('/\.(png|jpg|jpeg|webp|gif|svg)(\?|$)/i',$url)): ?><img style="max-width:100%;border-radius:16px" src="<?=h($url)?>"><?php else: ?><iframe style="width:100%;height:560px;border:0;border-radius:16px;background:#fff" src="<?=h($url)?>"></iframe><?php endif; ?><?php elseif($txt): ?><div class="doc"><?= (stripos($txt,'<')!==false && stripos($txt,'**')===false) ? $txt : nl2br(h($txt)) ?></div><?php else: ?><div class="empty"><strong>No preview body found</strong><p>This asset needs real output.</p></div><?php endif; ?></div>
<?php else: ?><div class="empty"><strong>No usable assets yet</strong><p>Good: old debrief junk is hidden. Use the prompt to create actual content.</p></div><?php endif; ?>
</div><div class="actions"><?php if($selected&&urlx($selected)): ?><a class="btn small" target="_blank" href="<?=h(urlx($selected))?>">Open Actual Work</a><?php endif; ?><button class="btn small" onclick="document.getElementById('revisePrompt').focus()">Revise This</button><button class="btn small" onclick="alert('Approve/publish/scheduler handoff is next.')">Approve / Publish</button></div><div style="margin-top:12px"><h3>Revision Prompt for Current Work</h3><textarea id="revisePrompt" rows="5" placeholder="Tell <?=h($name)?> how to improve this selected work."></textarea><button class="btn small" onclick="sendStudioPrompt('revision')">Send Revision</button><div id="reviseResult" class="result"></div></div></div>
<aside class="sideStack"><div class="promptBox"><h2><?=h($promptTitle)?></h2><p class="meta">New content request for <?=h($name)?>. Actual work only, no briefs.</p><textarea id="newPrompt" rows="8" placeholder="<?=h($placeholder)?>"></textarea><div class="split"><button class="btn" onclick="sendStudioPrompt('new')">Send New Request</button><button class="btn dark" onclick="document.getElementById('newPrompt').value='Create actual finished content only. No executive summary. No evidence block. No handoff block. Give Mark the usable asset directly.'">No Briefs</button></div><div id="newResult" class="result"></div></div><div class="workBox"><h2>Finished Work</h2><div class="workList"><?php foreach($assets as $a): ?><a class="workItem <?=($selected&&(int)$selected['id']===(int)$a['id'])?'active':''?>" href="/dashboard/executive-office.php?exec=<?=h($exec)?>&asset_id=<?=h($a['id'])?>"><strong><?=h($a['title'])?></strong><span><?=h(atype($a,$exec))?> · #<?=h($a['id'])?> · <?=h($a['created_at'])?></span></a><?php endforeach; ?><?php if(!count($assets)): ?><div class="workItem"><strong>No finished work yet</strong><span>Use the prompt above to create the first real asset.</span></div><?php endif; ?></div></div></aside></section>
</main></div><script>
const KEY=<?=json_encode($key)?>, EXEC=<?=json_encode($exec)?>, ASSET_ID=<?=json_encode($selected['id']??0)?>;
async function sendStudioPrompt(mode){const isRev=mode==='revision';const el=document.getElementById(isRev?'revisePrompt':'newPrompt');const out=document.getElementById(isRev?'reviseResult':'newResult');const text=el.value.trim();if(!text){alert('Add a prompt first.');return;}out.textContent='Sending to '+EXEC+'...';try{const res=await fetch('/lead-engine/executive-studio-prompt.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:KEY,exec:EXEC,asset_id:isRev?ASSET_ID:0,mode,prompt:text})});const json=await res.json();out.textContent=(json.success||json.ok)?('Queued task #'+(json.task_id||'created')+'.'):('Error: '+(json.error||'unknown'));}catch(e){out.textContent='Error: '+e.message;}}
</script></body></html>