<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sb18d($m,$ep,$p=null){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$m,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json','Prefer: return=representation'],CURLOPT_TIMEOUT=>25]);
  if($p!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($p));
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $id=$_POST['id']??''; $status=$_POST['status']??'';
  if($id && in_array($status,['reviewed','called_back','archived','spam','new'],true)){
    sb18d('PATCH','executive_call_inbox?id=eq.'.rawurlencode($id),['status'=>$status,'updated_at'=>date('c')]);
    $msg='Call marked '.$status.'.';
  }
}
$calls=sb18d('GET','executive_call_inbox?select=*&order=call_date.desc&limit=300');
$briefs=sb18d('GET','executive_call_briefings?select=*&order=created_at.desc&limit=10');
$brief=$briefs[0]??[];
$stats=['total'=>count($calls),'new'=>0,'urgent'=>0,'callback'=>0,'lead'=>0,'appt'=>0];
foreach($calls as $c){ if(($c['status']??'')==='new')$stats['new']++; if(($c['urgency']??'')==='urgent')$stats['urgent']++; if(!empty($c['callback_needed']))$stats['callback']++; if(!empty($c['lead_related']))$stats['lead']++; if(!empty($c['appointment_requested']))$stats['appt']++; }
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jessica Executive Inbox V12.18</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:38px}.wrap{max-width:1600px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:30px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{border:0;display:inline-block;background:#c8a96e;color:#111;text-decoration:none;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px;cursor:pointer}.light{background:#f2efe8;color:#111}.layout{display:grid;grid-template-columns:1fr .42fr;gap:18px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:11px;border-bottom:1px solid #eee;font-size:14px;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:#777;background:#faf9f6}.muted{color:#777;font-size:13px}pre{white-space:pre-wrap;background:#111;color:#fff;padding:16px;border-radius:12px}.urgent{color:#9b1c1c;font-weight:900}.high{color:#9a6400;font-weight:900}.normal{color:#14783c;font-weight:900}.low{color:#777;font-weight:900}@media(max-width:1000px){.grid,.layout{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">Jessica Executive Inbox V12.18</div><div>Forwarded calls, voicemail summaries, recordings, callbacks, and Mark-only business inbox</div></div><main class="wrap"><?php if($msg):?><div class="panel" style="padding:16px"><?=h($msg)?></div><?php endif;?>
<p><a class="btn" target="_blank" href="/lead-engine/build-executive-call-briefing.php?key=<?=h($cronKey)?>">Build Executive Brief</a><a class="btn light" target="_blank" href="/lead-engine/executive-call-intake.php?key=<?=h($cronKey)?>&caller_phone=2035551212&caller_name=Demo%20Caller&transcript=I%20need%20Mark%20to%20call%20me%20back%20about%20selling%20my%20home">Demo Intake</a><a class="btn light" href="/dashboard/conversation-intelligence.php">Conversation Intel</a><a class="btn light" href="/dashboard/daily-command-center.php">Command</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=h($stats['total'])?></div>Total</div><div class="kpi"><div class="n"><?=h($stats['new'])?></div>New</div><div class="kpi"><div class="n"><?=h($stats['urgent'])?></div>Urgent</div><div class="kpi"><div class="n"><?=h($stats['callback'])?></div>Callback</div><div class="kpi"><div class="n"><?=h($stats['lead'])?></div>Lead</div><div class="kpi"><div class="n"><?=h($stats['appt'])?></div>Appt</div></section>
<div class="layout"><section class="panel"><h2>Forwarded Call Inbox</h2><table><tr><th>Caller</th><th>Category</th><th>Summary</th><th>Action</th><th>Status</th></tr><?php foreach($calls as $c):?><tr><td><strong><?=h($c['caller_name']?:$c['caller_phone'])?></strong><div class="muted"><?=h($c['caller_phone'])?><br><?=h($c['call_date'])?></div></td><td><span class="<?=h($c['urgency'])?>"><?=h($c['urgency'])?></span><div class="muted"><?=h($c['caller_category'])?><br>Lead: <?=h(!empty($c['lead_related'])?'yes':'no')?></div></td><td><?=h($c['summary'])?><div class="muted"><?=h($c['reason_for_call'])?><?php if($c['recording_url']):?><br><a target="_blank" href="<?=h($c['recording_url'])?>">Recording</a><?php endif;?></div></td><td><?=h($c['recommended_action'])?><div class="muted">Callback: <?=h(!empty($c['callback_needed'])?'yes':'no')?> · <?=h($c['callback_window'])?></div></td><td><form method="post"><input type="hidden" name="id" value="<?=h($c['id'])?>"><button class="btn" name="status" value="called_back">Called Back</button><button class="btn light" name="status" value="reviewed">Reviewed</button><button class="btn light" name="status" value="archived">Archive</button><button class="btn light" name="status" value="spam">Spam</button></form></td></tr><?php endforeach;?></table></section>
<section class="panel"><h2>Executive Brief</h2><div style="padding:16px"><pre><?=h($brief['briefing_text']??'Build Executive Brief to create summary.')?></pre></div><h2>Retell Webhook Target</h2><div style="padding:16px"><pre><?=h("https://markpires.com/lead-engine/executive-call-intake.php?key=".$cronKey)?></pre></div></section></div>
</main></body></html>