<?php
session_start();
require_once __DIR__.'/../lead-engine/config.php';
require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/executive-roster.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($s,$p=[]){try{return gdb_all($s,$p)?:[];}catch(Throwable $e){return [];}}
$execs=rows("SELECT * FROM executive_registry ORDER BY FIELD(executive_key,'goliath','scout','jessica','shakespeare','einstein','scorsese','sherlock','pandora','mozart'), executive_key ASC");
$initiatives=rows("SELECT * FROM executive_initiatives WHERE status='proposed' ORDER BY priority DESC,created_at DESC LIMIT 50");
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><title>Executive Roster</title>
<style>
body{margin:0;background:radial-gradient(circle at top left,rgba(212,175,55,.16),transparent 32%),#030712;color:#fff;font-family:Arial,sans-serif}.wrap{max-width:1280px;margin:auto;padding:14px;padding-bottom:80px}h1{color:#d4af37;margin:0}.muted{color:#94a3b8;font-size:13px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}.card,.panel{background:#07111f;border:1px solid #ffffff1a;border-radius:20px;padding:14px;margin-bottom:12px}.card h2{margin:0;color:#f5d48b}.bar{height:10px;background:#020617;border-radius:999px;overflow:hidden;margin:10px 0}.fill{height:100%;background:linear-gradient(90deg,#d4af37,#22c55e)}.btn{display:inline-block;background:#101827;color:#fff;text-decoration:none;border-radius:12px;padding:9px 12px;font-weight:900;margin:3px}.gold{background:#d4af37;color:#111}.pill{display:inline-block;border:1px solid #ffffff22;border-radius:999px;padding:3px 7px;font-size:10px;color:#cbd5e1;margin:2px}.top{position:sticky;top:0;background:rgba(3,7,18,.95);backdrop-filter:blur(14px);border-bottom:1px solid #ffffff1a;margin:-14px -14px 14px;padding:14px;z-index:10}.layout{display:grid;grid-template-columns:1fr 360px;gap:12px}@media(max-width:900px){.layout{grid-template-columns:1fr}.wrap{padding:10px}.top{margin:-10px -10px 10px}}
</style></head><body><div class="wrap"><section class="top"><h1>Executive Roster</h1><div class="muted">Every executive has a role, workspace, maturity score, and handoff path. Goal: get all to 80–85%, then fine-tune into super agents.</div><a class="btn gold" href="/dashboard/goliath-mobile-command.php">Mobile Command</a><a class="btn" href="/dashboard/shakespeare-authority-center.php">Shakespeare</a></section>
<section class="layout"><main><div class="grid"><?php foreach($execs as $e): ?><article class="card"><h2><?=h($e['display_name'])?></h2><div class="muted"><?=h($e['title'])?></div><div class="bar"><div class="fill" style="width:<?=max(1,min(100,(int)$e['maturity_score']))?>%"></div></div><span class="pill"><?=h($e['maturity_score'])?>%</span><span class="pill"><?=h($e['status'])?></span><p><?=h($e['mission'])?></p><p class="muted">Handoff: <?=h($e['handoff_to'])?></p><a class="btn gold" href="<?=h($e['workspace_url'])?>">Open Room</a></article><?php endforeach; ?></div></main><aside><section class="panel"><h2>Proposed Initiatives</h2><?php foreach($initiatives as $i): ?><div class="card"><b><?=h($i['title'])?></b><div class="muted"><?=h($i['executive_key'])?> · <?=h($i['business_goal'])?></div><p><?=h($i['recommendation'])?></p><span class="pill"><?=h($i['priority'])?></span></div><?php endforeach; ?></section></aside></section></div></body></html>