<?php
session_start(); require_once __DIR__.'/../lead-engine/config.php'; require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/executive-accountability-v108.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($s,$p=[]){try{return gdb_all($s,$p)?:[];}catch(Throwable $e){return [];}}
function one($s,$p=[]){try{return gdb_one($s,$p)?:[];}catch(Throwable $e){return [];}}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$kpis=rows("SELECT * FROM executive_kpi_daily WHERE kpi_date=CURDATE() ORDER BY operating_score DESC,id DESC LIMIT 20");
$boards=rows("SELECT * FROM executive_department_boards ORDER BY executive_key, FIELD(lane,'inbox','working','blocked','review','finished'), priority DESC LIMIT 200");
$by=[];foreach($boards as $b)$by[$b['executive_key']][$b['lane']][]=$b;
$brief=one("SELECT * FROM goliath_chairman_briefings ORDER BY id DESC LIMIT 1");
$vault=rows("SELECT * FROM scorsese_content_vault ORDER BY score DESC,id DESC LIMIT 30");
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Executive Accountability V108</title><link rel="stylesheet" href="/dashboard/assets/goliath-carbon-v105.css"></head><body><div class="wrap">
<header class="top"><div><div class="logo">📊 EXECUTIVE ACCOUNTABILITY</div><div class="muted">Department Boards · KPIs · Leaderboard · Collaboration Credits · Content Vault</div></div><div><a class="btn" href="/dashboard/executive-council-v107.php">Council</a> <a class="btn" href="/dashboard/goliath-projects-v106.php">Projects</a> <a class="btn gold" target="_blank" href="/lead-engine/executive-accountability-engine-v108.php?key=<?=h($key)?>">Run Accountability</a></div></header>
<section class="panel" style="margin-top:14px"><h2>Executive Leaderboard</h2><table><tr><th>Rank</th><th>Executive</th><th>Department</th><th>Score</th><th>Active</th><th>Blocked</th><th>Opportunities</th><th>Revenue Influenced</th></tr><?php $r=1; foreach($kpis as $k): ?><tr><td><?=h($r++)?></td><td><b><?=h(ucfirst(str_replace('_',' ',$k['executive_key'])))?></b></td><td><?=h($k['department'])?></td><td class="score"><?=h($k['operating_score'])?></td><td><?=h($k['active_count'])?></td><td><?=h($k['blocked_count'])?></td><td><?=h($k['opportunities_count'])?></td><td>$<?=h(number_format((float)$k['revenue_influenced']))?></td></tr><?php endforeach; ?></table></section>
<section class="panel" style="margin-top:14px"><h2>Department Boards</h2><?php foreach($by as $exec=>$lanes): ?><div class="item"><h3><?=h(ucfirst(str_replace('_',' ',$exec)))?></h3><div class="two"><?php foreach(['inbox','working','blocked','review','finished'] as $lane): ?><div><b><?=h(strtoupper($lane))?></b><?php foreach(($lanes[$lane]??[]) as $b): ?><div class="item"><b><?=h($b['title'])?></b><div class="muted">Priority <?=h($b['priority'])?> · Confidence <?=h($b['confidence_score'])?></div></div><?php endforeach; ?></div><?php endforeach; ?></div></div><?php endforeach; ?></section>
<section class="two"><main class="panel"><h2>Chairman Briefing</h2><p class="muted"><?=h($brief['summary']??'Run accountability engine first.')?></p><pre class="item" style="white-space:pre-wrap"><?=h(json_encode(json_decode($brief['executive_rankings_json']??'[]',true),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre></main><aside class="panel"><h2>Scorsese Content Vault</h2><div class="list"><?php foreach($vault as $v): ?><div class="item"><b><?=h($v['title'])?></b><div class="score">Score <?=h($v['score'])?></div><div class="muted"><?=h($v['brand_style'])?> · <?=h($v['asset_type'])?></div><a class="btn" target="_blank" href="<?=h($v['file_url'])?>">Open</a></div><?php endforeach; ?></div></aside></section>
</div></body></html>