<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
require_once __DIR__ . '/../lead-engine/goliath-db.php';
require_once __DIR__ . '/../lead-engine/goliath-v76-operating-system.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/goliath-executive-memory.php'));exit;}
gv76_install();
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($sql,$p=[]){try{return gdb_all($sql,$p)?:[];}catch(Throwable $e){return [];}}
$exec=strtolower($_GET['exec']??'');
$where=$exec?'WHERE executive_key=?':'';
$p=$exec?[$exec]:[];
$mem=rows("SELECT * FROM executive_memory $where ORDER BY updated_at DESC LIMIT 300",$p);
$pipe=rows("SELECT * FROM executive_pipeline_events $where ORDER BY created_at DESC LIMIT 200",$p);
$hands=rows("SELECT * FROM executive_handoffs ".($exec?'WHERE from_executive=? OR to_executive=?':'')." ORDER BY created_at DESC LIMIT 200",$exec?[$exec,$exec]:[]);
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Executive Memory</title><link rel="stylesheet" href="/dashboard/assets/goliath-v33.css?v=33"><link rel="stylesheet" href="/dashboard/assets/goliath-v45-final.css?v=456"><style>body{background:#030712;color:#fff}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:12px}.card{background:#07111f;border:1px solid rgba(255,255,255,.12);border-radius:16px;padding:12px}.card h3{color:#f5d48b;margin:0}.meta{color:#94a3b8;font-size:12px}.chips{display:flex;gap:8px;flex-wrap:wrap}.chip{color:#fff;text-decoration:none;background:#0f172a;border:1px solid rgba(255,255,255,.12);border-radius:999px;padding:8px 11px;font-weight:900}</style></head><body><div class="shell"><?php @require __DIR__.'/includes/goliath-sidebar-v33.php'; ?><main class="main"><section class="top"><div><h1>Executive Memory + Pipelines</h1><p>Persistent work memory, pipeline events, and handoffs.</p></div><div class="brandbar"><a class="btn dark" href="/dashboard/goliath-mission-control.php">Mission Control</a><a class="btn" href="/dashboard/goliath-deliverables.php">Deliverables</a></div></section><section class="panel"><div class="inner"><div class="chips"><a class="chip" href="/dashboard/goliath-executive-memory.php">All</a><?php foreach(['scout','jessica','scorsese','einstein','shakespeare','prospector','pandora','rockefeller','columbo','mozart','goliath'] as $a): ?><a class="chip" href="/dashboard/goliath-executive-memory.php?exec=<?=h($a)?>"><?=h(ucfirst($a))?></a><?php endforeach;?></div></div></section><section class="panel"><h2>Memory</h2><div class="inner"><div class="grid"><?php foreach($mem as $m): ?><div class="card"><h3><?=h(ucfirst($m['executive_key']))?> · <?=h($m['memory_type'])?></h3><p><b><?=h($m['memory_key'])?></b></p><p><?=h(mb_substr(strip_tags($m['memory_value']??''),0,260))?></p><div class="meta"><?=h($m['updated_at'])?></div></div><?php endforeach;?></div></div></section><section class="panel"><h2>Pipeline Events</h2><div class="inner"><div class="grid"><?php foreach($pipe as $p): ?><div class="card"><h3><?=h(ucfirst($p['executive_key']))?> · <?=h($p['stage'])?></h3><p><?=h($p['title'])?></p><p><?=h($p['detail'])?></p><div class="meta"><?=h($p['progress'])?>% · <?=h($p['created_at'])?></div></div><?php endforeach;?></div></div></section><section class="panel"><h2>Handoffs</h2><div class="inner"><div class="grid"><?php foreach($hands as $hnd): ?><div class="card"><h3><?=h(ucfirst($hnd['from_executive']))?> → <?=h(ucfirst($hnd['to_executive']))?></h3><p><?=h($hnd['title'])?></p><p><?=h($hnd['reason'])?></p><div class="meta"><?=h($hnd['status'])?> · <?=h($hnd['created_at'])?></div></div><?php endforeach;?></div></div></section></main></div></body></html>