<?php
session_start(); require_once __DIR__.'/../lead-engine/config.php'; require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/goliath-organization-runtime.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($s,$p=[]){try{return gdb_all($s,$p)?:[];}catch(Throwable $e){return [];}}
function one($s,$p=[]){try{return gdb_one($s,$p)?:[];}catch(Throwable $e){return [];}}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$state=one("SELECT * FROM goliath_runtime_state WHERE state_key='universal_runtime' LIMIT 1");
$missions=rows("SELECT * FROM goliath_missions ORDER BY priority DESC,updated_at DESC LIMIT 40");
$events=rows("SELECT * FROM goliath_mission_bus_events ORDER BY id DESC LIMIT 40");
$top=rows("SELECT * FROM executive_top10_boards ORDER BY executive_key,rank_no ASC");
$boards=[];foreach($top as $t){$boards[$t['executive_key']][]=$t;}
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Goliath Runtime</title><style>
body{margin:0;color:#fff;font-family:Arial;background:#05070b;background-image:radial-gradient(circle at 10% 0,#66521a44,transparent 30%),linear-gradient(45deg,rgba(255,255,255,.025) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.025) 50%,rgba(255,255,255,.025) 75%,transparent 75%);background-size:auto,18px 18px}.wrap{max-width:1500px;margin:auto;padding:14px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.logo{font-weight:1000;color:#f6d679;letter-spacing:.12em}.btn{display:inline-flex;text-decoration:none;color:#fff;background:#111827;border:1px solid #ffffff22;border-radius:12px;padding:10px 12px;font-weight:900;font-size:12px}.gold{background:linear-gradient(135deg,#f6d679,#8a650f);color:#111}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.panel{background:linear-gradient(180deg,#0d1422dd,#070b13ee);border:1px solid #253b5d;border-radius:20px;padding:14px;box-shadow:0 18px 45px #000a}.panel h2{margin:0 0 10px;color:#f6d679}.list{display:grid;gap:8px;max-height:520px;overflow:auto}.item{background:#050914;border:1px solid #ffffff18;border-radius:14px;padding:10px}.muted{color:#94a3b8;font-size:12px}.boards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.score{color:#80ffbd;font-weight:1000}.rank{color:#f6d679;font-weight:1000}@media(max-width:1100px){.grid,.boards{grid-template-columns:1fr}.top{flex-direction:column;align-items:flex-start}}
</style></head><body><div class="wrap">
<header class="top"><div><div class="logo">⚡ GOLIATH UNIVERSAL RUNTIME</div><div class="muted">One START · Mission Bus · Executive Top 10 · No idle agents</div></div><div><a class="btn" href="/dashboard/goliath-mission-control.php">Mission Control</a> <a class="btn" href="/dashboard/shakespeare-authority-architect.php">Shakespeare</a> <a class="btn gold" target="_blank" href="/lead-engine/universal-executive-runtime-v103.php?key=<?=h($key)?>">START / RUN NOW</a></div></header>
<section class="grid"><main class="panel"><h2>Active Missions</h2><div class="list"><?php foreach($missions as $m): ?><div class="item"><b><?=h($m['title'])?></b><div class="muted"><?=h($m['mission_type'])?> · <?=h($m['status'])?> · Priority <?=h($m['priority'])?> · Owner <?=h($m['owner_executive'])?></div><div class="muted"><?=h($m['next_action'])?></div></div><?php endforeach; ?></div></main>
<aside class="panel"><h2>Mission Bus Events</h2><div class="list"><?php foreach($events as $e): ?><div class="item"><b><?=h($e['title'])?></b><div class="muted"><?=h($e['event_type'])?> · <?=h($e['from_executive'])?><?=h($e['to_executive']?' → '.$e['to_executive']:'')?> · Priority <?=h($e['priority'])?></div><div class="muted"><?=h($e['details'])?></div></div><?php endforeach; ?></div></aside></section>
<section class="panel" style="margin-top:14px"><h2>Executive Top 10 Boards</h2><div class="boards"><?php foreach($boards as $exec=>$items): ?><div class="item"><h3><?=h(ucfirst($exec))?></h3><?php foreach($items as $i): ?><div class="muted"><span class="rank">#<?=h($i['rank_no'])?></span> <b><?=h($i['title'])?></b> <span class="score"><?=h($i['score'])?></span><br><?=h($i['reason'])?></div><hr style="border-color:#ffffff12"><?php endforeach; ?></div><?php endforeach; ?></div></section>
</div></body></html>