<?php
session_start(); require_once __DIR__.'/../lead-engine/config.php';
require_once __DIR__ . '/includes/goliath-ui.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next=/dashboard/goliath-communications.php');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sb($ep){$ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY],CURLOPT_TIMEOUT=>30]);$b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$leads=sb('leads?select=*&order=created_at.desc&limit=25');
$logFile=defined('LOG_PATH')?LOG_PATH.'/lead-engine-'.date('Y-m').'.log':__DIR__.'/../lead-engine/logs/lead-engine-'.date('Y-m').'.log';
$logs=[]; if(file_exists($logFile)){ $lines=array_slice(file($logFile,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES),-80); foreach($lines as $line){$j=json_decode($line,true); if(is_array($j))$logs[]=$j;} }
$adminOk=0;$userOk=0;$adminErr=0;$userErr=0;foreach($logs as $l){if(($l['service']??'')==='Resend Admin'){(($l['status']??'')==='success')?$adminOk++:$adminErr++;} if(($l['service']??'')==='Resend User'){(($l['status']??'')==='success')?$userOk++:$userErr++;}}
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Goliath Communications</title><style>
body{margin:0;background:#f5f3ef;color:#111827;font-family:Arial}.hero{background:#101827;color:white;padding:30px}.hero h1{font-family:Georgia,serif;color:#c8a96e;font-size:42px;margin:0}.wrap{max-width:1500px;margin:auto;padding:20px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card,.panel{background:white;border:1px solid #ece7dc;border-radius:18px;padding:18px;box-shadow:0 8px 24px #1018280d;margin-bottom:14px}.metric{font-size:34px;color:#c8a96e;font-weight:900}.btn{background:#c8a96e;color:#111;text-decoration:none;padding:10px 13px;border-radius:10px;font-weight:900;display:inline-block;margin:4px}.row{display:grid;grid-template-columns:160px 1fr 120px 120px;gap:10px;padding:10px;border-bottom:1px solid #eee}.head{font-size:11px;text-transform:uppercase;color:#667085;background:#fbfaf7;font-weight:900}.small{font-size:12px;color:#667085}pre{white-space:pre-wrap;background:#101827;color:white;padding:14px;border-radius:12px;max-height:380px;overflow:auto}@media(max-width:900px){.grid,.row{grid-template-columns:1fr}}
</style><link rel="stylesheet" href="/dashboard/assets/goliath-os.css?v=4"><link rel="icon" href="/dashboard/assets/goliath-ai-full-logo.png?v=4"><?php goliath_ui_head(); ?></head><body><?php goliath_ui_open(); ?><section class="hero"><h1>Goliath Communications</h1><p>Lead emails, Resend diagnostics, and incoming lead action feed.</p></section><main class="wrap">
<p><a class="btn" target="_blank" href="/lead-engine/resend-diagnostic.php?key=<?=h($key)?>">Run Resend Test</a><a class="btn" target="_blank" href="/lead-engine/capture-diagnostic.php?key=<?=h($key)?>">Run Full Capture Test</a><a class="btn" href="/dashboard/owner-research-queue.php">Owner Queue</a></p>
<section class="grid"><div class="card"><div class="metric"><?=count($leads)?></div><strong>Recent Leads</strong></div><div class="card"><div class="metric"><?=$adminOk?></div><strong>Admin Emails OK</strong></div><div class="card"><div class="metric"><?=$userOk?></div><strong>User Emails OK</strong></div><div class="card"><div class="metric"><?=($adminErr+$userErr)?></div><strong>Email Errors</strong></div></section>
<section class="panel"><h2>Recent Leads</h2><div class="row head"><div>Name</div><div>Contact / Property</div><div>Type</div><div>Score</div></div><?php foreach($leads as $l):?><div class="row"><div><strong><?=h($l['name']??'')?></strong><br><span class="small"><?=h($l['created_at']??'')?></span></div><div><?=h($l['email']??'')?> · <?=h($l['phone']??'')?><br><span class="small"><?=h($l['address']??'')?> <?=h($l['town']??'')?></span></div><div><?=h($l['type']??'')?></div><div><?=h($l['lead_score']??$l['adaptive_score']??'')?></div></div><?php endforeach;?></section>
<section class="panel"><h2>Recent Lead-Engine Email Logs</h2><pre><?php foreach(array_reverse($logs) as $l){ if(in_array($l['service']??'',['Resend Admin','Resend User','Hot Lead Alert','Capture'])) echo h(json_encode($l,JSON_PRETTY_PRINT))."\n\n"; } ?></pre></section>
</main><?php goliath_ui_close(); ?></body></html>
