<?php
session_start(); require_once __DIR__.'/../lead-engine/config.php'; require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/goliath-organization-core.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($s,$p=[]){try{return gdb_all($s,$p)?:[];}catch(Throwable $e){return [];}}
function one($s,$p=[]){try{return gdb_one($s,$p)?:[];}catch(Throwable $e){return [];}}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$charter=one("SELECT * FROM goliath_core_charter WHERE charter_key='core_v1' LIMIT 1");
$dna=rows("SELECT * FROM executive_dna_profiles ORDER BY FIELD(executive_key,'goliath','scout','jessica','shakespeare','scorsese','sherlock','einstein','pandora','mozart','rockefeller','columbo','prospector'), executive_key");
$initiatives=rows("SELECT id,executive_key,title,status,priority,reason,expected_impact,created_at FROM executive_initiatives ORDER BY created_at DESC LIMIT 40");
$reports=rows("SELECT council_date,executive_key,recommends_next,created_at FROM executive_council_reports ORDER BY council_date DESC,id DESC LIMIT 30");
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Goliath Organization Core</title><style>body{margin:0;background:#05070d;color:#fff;font-family:Arial}.wrap{max-width:1450px;margin:auto;padding:14px}.top{display:flex;justify-content:space-between;gap:12px}.logo{font-weight:1000;color:#f6d679;letter-spacing:.12em}.btn{display:inline-flex;text-decoration:none;color:#fff;background:#101827;border:1px solid #ffffff22;border-radius:12px;padding:10px 12px;font-weight:900;font-size:12px}.gold{background:linear-gradient(135deg,#f6d679,#8a650f);color:#111}.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:14px;margin-top:14px}.panel{background:#07111f;border:1px solid #22405f;border-radius:20px;padding:14px;box-shadow:0 18px 45px #0008}.panel h2{margin:0 0 10px;color:#f6d679}.charter{white-space:pre-wrap;color:#dbeafe;line-height:1.45}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.card,.item{background:#050914;border:1px solid #ffffff18;border-radius:14px;padding:12px}.list{display:grid;gap:8px;max-height:620px;overflow:auto}.muted{color:#94a3b8;font-size:12px}@media(max-width:950px){.grid,.cards{grid-template-columns:1fr}.top{flex-direction:column}}</style></head><body><div class="wrap"><header class="top"><div><div class="logo">🏛️ GOLIATH ORGANIZATION CORE</div><div class="muted">Core Charter · Executive DNA · Initiatives · Council Reports</div></div><div><a class="btn" href="/dashboard/goliath-mission-control.php">Mission Control</a> <a class="btn gold" target="_blank" href="/lead-engine/executive-initiative-engine-v101-1.php?key=<?=h($key)?>&limit=36">Generate Initiatives</a> <a class="btn gold" target="_blank" href="/lead-engine/executive-council-pulse-v101-1.php?key=<?=h($key)?>">Council Pulse</a></div></header>
<section class="grid"><main class="panel"><h2>Core Charter</h2><div class="charter"><?=h($charter['charter_text']??'Run V101.1 migration + installer first.')?></div></main><aside class="panel"><h2>Current Initiatives</h2><div class="list"><?php foreach($initiatives as $i): ?><div class="item"><b><?=h(ucfirst($i['executive_key']))?> — <?=h($i['title'])?></b><br><span class="muted"><?=h($i['status'])?> · Priority <?=h($i['priority'])?><br><?=h($i['reason'])?></span></div><?php endforeach; ?></div></aside></section>
<section class="panel" style="margin-top:14px"><h2>Executive DNA</h2><div class="cards"><?php foreach($dna as $d): ?><div class="card"><small><?=h($d['executive_key'])?></small><h3><?=h($d['executive_name'])?></h3><b><?=h($d['title'])?></b><p class="muted"><?=h($d['identity_text'])?></p></div><?php endforeach; ?></div></section>
<section class="panel" style="margin-top:14px"><h2>Council Reports</h2><div class="list"><?php foreach($reports as $r): ?><div class="item"><b><?=h($r['council_date'])?> · <?=h(ucfirst($r['executive_key']))?></b><div class="muted"><?=nl2br(h($r['recommends_next']))?></div></div><?php endforeach; ?></div></section></div></body></html>