<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/goliath-command-bus.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sbq($ep){$ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json'],CURLOPT_TIMEOUT=>25]);$b=curl_exec($ch);$http=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$d=json_decode($b,true);return ($http>=200&&$http<300&&is_array($d))?$d:[];}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$jobs=sbq('goliath_agent_jobs?select=*&order=created_at.desc&limit=80');
$runs=sbq('goliath_command_bus_runs?select=*&order=created_at.desc&limit=10');
$counts=[];foreach($jobs as $j){$counts[$j['status']??'unknown']=($counts[$j['status']??'unknown']??0)+1;}
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Goliath Command Bus</title>
<link rel="stylesheet" href="/dashboard/assets/goliath-v33.css?v=33"><style>
.busWrap{padding:22px}.busHero{border:1px solid rgba(245,197,83,.35);background:linear-gradient(135deg,rgba(12,16,28,.96),rgba(26,18,8,.92));border-radius:22px;padding:22px;margin-bottom:18px;box-shadow:0 0 35px rgba(0,0,0,.35)}.busHero h1{margin:0;color:#f5c85d}.busGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.busStat{background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.12);border-radius:16px;padding:14px}.busStat b{font-size:28px;color:#fff}.busTable{width:100%;border-collapse:separate;border-spacing:0 9px}.busTable tr{background:rgba(255,255,255,.05)}.busTable td,.busTable th{padding:12px;text-align:left}.status{font-weight:800}.queued{color:#f5c85d}.dispatched{color:#60a5fa}.completed{color:#31d38d}.failed{color:#fb7185}.btnRun{display:inline-block;padding:12px 16px;border-radius:14px;background:#f5c85d;color:#130d03;font-weight:900;text-decoration:none}@media(max-width:900px){.busGrid{grid-template-columns:1fr 1fr}.busTable{font-size:12px}}
</style></head><body><div class="shell"><?php require __DIR__.'/includes/goliath-sidebar-v33.php'; ?><main class="main busWrap">
<section class="busHero"><h1>Goliath Command Bus 1.0</h1><p>The dispatcher that gives every agent work, queues local AI tasks, and logs proof of action into Mission Control.</p><a class="btnRun" target="_blank" href="/lead-engine/goliath-command-bus.php?key=<?=h($key)?>&mode=manual&limit=20">Run Command Bus Now</a> <a class="btnRun" style="background:#111827;color:#fff;border:1px solid #334155" href="/dashboard/goliath-mission-control.php">Mission Control</a></section>
<section class="busGrid"><div class="busStat"><small>Queued</small><br><b><?=h($counts['queued']??0)?></b></div><div class="busStat"><small>Dispatched</small><br><b><?=h($counts['dispatched']??0)?></b></div><div class="busStat"><small>Completed</small><br><b><?=h($counts['completed']??0)?></b></div><div class="busStat"><small>Failed</small><br><b><?=h($counts['failed']??0)?></b></div></section>
<section class="panel"><h2>Recent Agent Jobs <span>direct work queue</span></h2><div class="inner"><table class="busTable"><thead><tr><th>Agent</th><th>Mission</th><th>Status</th><th>Priority</th><th>Created</th><th>Instruction</th></tr></thead><tbody>
<?php foreach($jobs as $j): $st=$j['status']??'queued'; ?><tr><td><?=h($j['agent']??'')?></td><td><?=h($j['mission_type']??'')?></td><td class="status <?=h($st)?>"><?=h(strtoupper($st))?></td><td><?=h($j['priority']??'')?></td><td><?=h(!empty($j['created_at'])?date('m/d h:i A',strtotime($j['created_at'])):'')?></td><td><?=h(mb_strimwidth($j['instruction']??'',0,130,'...'))?></td></tr><?php endforeach; ?>
</tbody></table></div></section>
<section class="panel"><h2>Recent Runs</h2><div class="inner"><table class="busTable"><tbody><?php foreach($runs as $r):?><tr><td><?=h(!empty($r['created_at'])?date('m/d h:i A',strtotime($r['created_at'])):'')?></td><td><?=h($r['run_type']??'')?></td><td><?=h($r['status']??'')?></td><td>Queued <?=h($r['jobs_queued']??0)?> / Dispatched <?=h($r['jobs_dispatched']??0)?></td><td><?=h($r['message']??'')?></td></tr><?php endforeach;?></tbody></table></div></section>
</main></div></body></html>
