<?php
session_start(); require_once __DIR__.'/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next=/dashboard/goliath-consolidation-runner.php');exit;}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Goliath Address-Normalized Consolidation</title><style>
body{margin:0;background:#f5f3ef;color:#111827;font-family:Arial}.hero{background:#111827;color:white;padding:30px}.hero h1{font-family:Georgia,serif;color:#c8a96e;font-size:40px;margin:0}.wrap{max-width:1300px;margin:auto;padding:20px}.panel{background:white;border-radius:18px;padding:20px;box-shadow:0 4px 18px #0001}.btn{background:#c8a96e;border:0;border-radius:10px;padding:14px 18px;font-weight:900;margin:4px;cursor:pointer;text-decoration:none;color:#111}.danger{background:#991b1b;color:white}.barwrap{height:28px;background:#ddd;border-radius:99px;overflow:hidden}.bar{height:100%;background:#c8a96e;width:0}pre{white-space:pre-wrap;background:#111827;color:white;padding:14px;border-radius:12px;max-height:520px;overflow:auto}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:14px 0}.stat{background:#faf9f6;border-radius:12px;padding:12px}.num{font-size:28px;color:#c8a96e;font-weight:900}@media(max-width:900px){.stats{grid-template-columns:1fr 1fr}}</style></head><body>
<section class="hero"><h1>Goliath Address-Normalized Consolidation</h1><p>Skips bad addresses, repairs from source records, and groups by street number + street name + town.</p></section><main class="wrap"><section class="panel">
<button class="btn danger" onclick="startOver()">Start / Restart From Zero</button><button class="btn" onclick="resumeBuild()">Resume Build</button><button class="btn" onclick="saveUnique()">Save Unique Opportunities</button><a class="btn" href="/dashboard/goliath-opportunities.php">Open Opportunities</a><a class="btn" href="/dashboard/owner-research-queue.php">Owner Research Queue</a>
<div class="stats"><div class="stat"><div class="num" id="raw">0</div><strong>Raw</strong></div><div class="stat"><div class="num" id="unique">0</div><strong>Unique</strong></div><div class="stat"><div class="num" id="dupes">0</div><strong>Dupes</strong></div><div class="stat"><div class="num" id="bad">0</div><strong>Bad skipped</strong></div><div class="stat"><div class="num" id="saved">0</div><strong>Saved</strong></div></div>
<p id="status">Waiting.</p><div class="barwrap"><div class="bar" id="bar"></div></div><pre id="out"></pre></section></main>
<script>
const KEY=<?=json_encode($key)?>, LIMIT=500;
let total=+localStorage.getItem('goliath_total_v2135')||0, offset=+localStorage.getItem('goliath_offset_v2135')||0, groups=JSON.parse(localStorage.getItem('goliath_groups_v2135')||'{}'), saved=+localStorage.getItem('goliath_saved_v2135')||0, bad=+localStorage.getItem('goliath_bad_v2135')||0, running=false;
function log(x){let o=document.getElementById('out');o.textContent+=(typeof x==='string'?x:JSON.stringify(x,null,2))+'\n';o.scrollTop=o.scrollHeight;}
function isBad(a){let s=String(a||'').trim().toLowerCase();return !s||s==='not applicable'||s==='unknown address'||s==='n/a'||s==='na'||s.length<3;}
function normAddr(a){let s=String(a||'').toLowerCase();s=s.replace(/\(.*?\)/g,' ').replace(/\baka\b.*$/g,' ').replace(/#\s*[a-z0-9-]+/g,' ').replace(/\b(unit|apt|apartment|suite|ste|floor|fl|rear|front|left|right|upper|lower)\s+[a-z0-9-]+/g,' ').replace(/[.,]/g,' ').replace(/\b(road|rd|street|st|avenue|ave|lane|ln|drive|dr|court|ct|place|pl|circle|cir|terrace|ter|boulevard|blvd|parkway|pkwy|way|hwy|highway)\b/g,' ').replace(/\s+/g,' ').trim();let m=s.match(/^(\d+[a-z]?)\s+(.+)$/);if(!m)return '';return m[1]+'|'+m[2].replace(/[^a-z0-9]/g,'');}
function town(t){return String(t||'').toLowerCase().replace(/[^a-z0-9]/g,'');}
function key(r){if(isBad(r.address))return '';let a=normAddr(r.address), t=town(r.town);return a&&t?a+'|'+t:'';}
function money(w){let m=String(w||'').match(/Last known list price:\s*\$([0-9,]+)/i);return m?+m[1].replace(/,/g,''):0;}
function owner(w){let m=String(w||'').match(/Owner:\s*([^\.]+)/i);return m?m[1].trim():'';}
function dt(w){let m=String(w||'').match(/failed activity:\s*([0-9]{4}-[0-9]{2}-[0-9]{2})/i);return m?m[1]:'';}
function ui(){let u=Object.keys(groups).length,d=Math.max(0,offset-u-bad);raw.textContent=offset;unique.textContent=u;dupes.textContent=d;document.getElementById('bad').textContent=bad;saved.textContent=saved;document.querySelector('.bar').style.width=total?Math.min(100,Math.round(offset/total*100))+'%':'0%';status.textContent=`Offset ${offset} of ${total||'unknown'}`;}
function persist(){localStorage.setItem('goliath_groups_v2135',JSON.stringify(groups));localStorage.setItem('goliath_offset_v2135',offset);localStorage.setItem('goliath_total_v2135',total);localStorage.setItem('goliath_saved_v2135',saved);localStorage.setItem('goliath_bad_v2135',bad);ui();}
async function startOver(){if(running)return;if(!confirm('Restart improved consolidation?'))return;groups={};offset=0;total=0;saved=0;bad=0;['goliath_groups_v2135','goliath_offset_v2135','goliath_total_v2135','goliath_saved_v2135','goliath_bad_v2135'].forEach(k=>localStorage.removeItem(k));out.textContent='Clearing old unique seller opportunities...\n';let c=await fetch('/lead-engine/goliath-consolidation-clear-unique.php?key='+encodeURIComponent(KEY));log(await c.json());persist();await resumeBuild();}
async function resumeBuild(){if(running)return;running=true;log('Resuming improved consolidation...');while(true){let r=await fetch('/lead-engine/goliath-consolidation-fetch-raw.php?key='+encodeURIComponent(KEY)+'&offset='+offset+'&limit='+LIMIT);let txt=await r.text(),j;try{j=JSON.parse(txt)}catch(e){log({success:false,error:txt});running=false;return;}if(!j.success){log(j);running=false;return;}if(!total&&j.total)total=j.total;let rows=j.rows||[];if(!rows.length){log('No more rows. Click Save Unique Opportunities.');persist();running=false;return;}for(const row of rows){let k=key(row);if(!k){bad++;continue;}let p=money(row.why_now),o=owner(row.why_now),date=dt(row.why_now);if(!groups[k])groups[k]={address:row.address||'',town:row.town||'',attempts:0,max_score:0,source_ids:[],last_seen:'',owner_name:'',last_price:0,highest_price:0};let g=groups[k];g.attempts++;g.max_score=Math.max(g.max_score,+row.revenue_score||0);if(row.source_id||row.id)g.source_ids.push(String(row.source_id||row.id));if(o&&!g.owner_name)g.owner_name=o;if(date&&(!g.last_seen||date>g.last_seen))g.last_seen=date;if(p){g.last_price=p;g.highest_price=Math.max(g.highest_price,p);}}offset+=rows.length;persist();log({processed_offset:offset,total,unique:Object.keys(groups).length,duplicates_removed:Math.max(0,offset-Object.keys(groups).length-bad),bad_skipped:bad});if(rows.length<LIMIT){log('All chunks read. Click Save Unique Opportunities.');running=false;return;}}}
function payload(){let arr=[];for(const g of Object.values(groups)){let ab=Math.min(20,Math.max(0,(g.attempts-1)*5)),rb=0;if(g.last_seen){let days=Math.floor((Date.now()-new Date(g.last_seen).getTime())/86400000);if(days<=90)rb=15;else if(days<=180)rb=12;else if(days<=365)rb=9;else if(days<=730)rb=5;}let lb=g.highest_price>=2000000?10:(g.highest_price>=1000000?6:0),score=Math.min(100,(+g.max_score||0)+ab+rb+lb);let why=`Unique unresolved failed-sale property. Attempts found: ${g.attempts}.`;if(g.last_seen)why+=` Last known failed activity: ${g.last_seen}.`;if(g.owner_name)why+=` Owner: ${g.owner_name}.`;if(g.last_price>0)why+=` Last known list price: $${Math.round(g.last_price).toLocaleString()}.`;if(g.highest_price>0)why+=` Highest known list price: $${Math.round(g.highest_price).toLocaleString()}.`;arr.push({opportunity_date:new Date().toISOString().slice(0,10),opportunity_type:'goliath_unique_seller',title:'Goliath Seller Opportunity: '+g.address,source_table:'browser_consolidation_v2135',source_id:g.source_ids.slice(0,10).join(','),town:g.town,address:g.address,revenue_score:score,confidence_score:97,urgency_score:Math.min(100,75+rb+ab),why_now:why,recommended_action:'Verify current MLS status and owner details. If still unsold/off-market, move to Mark review and prepare a value-first seller strategy.',content_angle:'Seller education: failed listing recovery, pricing reset, and marketing relaunch strategy.',ad_angle:'Did your home fail to sell? Get a fresh local strategy review before relisting.',followup_angle:'Create outreach list by score, recency, town, price, bedrooms, and square footage.',compliance_note:'MLS intelligence only. Mark performs human review before outreach.',status:'new',created_at:new Date().toISOString(),updated_at:new Date().toISOString()});}arr.sort((a,b)=>b.revenue_score-a.revenue_score||a.address.localeCompare(b.address));return arr;}
async function saveUnique(){if(running)return;let arr=payload();saved=0;persist();log(`Saving ${arr.length} unique opportunities in 200-row batches...`);for(let i=0;i<arr.length;i+=200){let r=await fetch('/lead-engine/goliath-consolidation-save-unique.php?key='+encodeURIComponent(KEY),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows:arr.slice(i,i+200)})});let txt=await r.text(),j;try{j=JSON.parse(txt)}catch(e){j={success:false,error:txt};}log(j);if(!j.success)return;saved+=j.inserted||0;persist();}status.textContent='Finished. Unique opportunities saved: '+saved;log('NEXT: rebuild owner research queue.');}
ui();
</script></body></html>