<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/goliath-connection-check.php'));exit;}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Goliath Connection Check</title>
<style>
:root{--bg:#05070b;--panel:#0c111b;--line:#243044;--text:#eaf1ff;--muted:#93a4bf;--green:#39ff88;--yellow:#ffd166;--red:#ff4b5c;--blue:#66d9ff;}
body{margin:0;background:radial-gradient(circle at 20% 0,#172239,#05070b 48%);color:var(--text);font-family:Inter,Arial,sans-serif}.wrap{max-width:1180px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center}.btn{background:#14233a;border:1px solid #36527a;color:#fff;border-radius:12px;padding:12px 16px;text-decoration:none;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:20px}.card{background:linear-gradient(180deg,#101827,#080d16);border:1px solid var(--line);border-radius:18px;padding:16px;box-shadow:0 12px 36px #0008}.status{font-size:34px;font-weight:900}.ok{color:var(--green)}.warn{color:var(--yellow)}.bad{color:var(--red)}pre{white-space:pre-wrap;background:#02050a;border:1px solid #1a2639;border-radius:14px;padding:14px;overflow:auto}.muted{color:var(--muted)}@media(max-width:850px){.grid{grid-template-columns:1fr}.top{display:block}.btn{display:inline-block;margin-top:10px}}
</style></head><body><div class="wrap"><div class="top"><div><h1>Goliath Connection Check</h1><p class="muted">Pre-flight check before Jessica email push and Phase B local worker connection.</p></div><button class="btn" onclick="runCheck()">Run Connection Check</button></div><div id="summary" class="card"><strong>Ready.</strong> Click Run Connection Check.</div><div id="cards" class="grid"></div><h2>Raw Diagnostic</h2><pre id="raw">Waiting...</pre></div>
<script>
async function runCheck(){const s=document.getElementById('summary'), cards=document.getElementById('cards'), raw=document.getElementById('raw');s.innerHTML='Running checks...';cards.innerHTML='';try{const r=await fetch('/lead-engine/goliath-connection-health.php?key=<?=htmlspecialchars($key,ENT_QUOTES)?>',{cache:'no-store'});const j=await r.json();raw.textContent=JSON.stringify(j,null,2);let ok=0,bad=0,warn=0;Object.entries(j.checks||{}).forEach(([name,c])=>{const good=!!c.ok; if(good)ok++; else if(c.required)bad++; else warn++; const div=document.createElement('div');div.className='card';div.innerHTML=`<div class="status ${good?'ok':(c.required?'bad':'warn')}">${good?'● ONLINE':(c.required?'● FAIL':'● WAIT')}</div><h3>${name.replaceAll('_',' ')}</h3><p class="muted">Status: ${c.status||''} ${c.note||''}</p><p>${c.error||c.sample||''}</p>`;cards.appendChild(div);});s.innerHTML=`<strong>${bad?'Needs attention':'Core ready'}</strong><br>${ok} online / ${warn} optional waiting / ${bad} required failing`; }catch(e){s.innerHTML='<span class="bad">Connection check failed.</span>';raw.textContent=e.message;}}
runCheck();
</script></body></html>
