<?php
session_start();
require_once __DIR__.'/../lead-engine/config.php';
require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/goliath-missions.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($sql,$p=[]){try{return gdb_all($sql,$p)?:[];}catch(Throwable $e){return [];}}
$missions=rows("SELECT * FROM goliath_missions ORDER BY created_at DESC LIMIT 100");
$sessions=rows("SELECT * FROM goliath_council_sessions ORDER BY created_at DESC LIMIT 10");
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
function mlink($type){if($type==='scout_contact_research')return '/dashboard/scout-contact-workspace.php';if($type==='youtube_growth')return '/dashboard/scorsese-media-center.php';if($type==='seo_aeo_lead_growth')return '/dashboard/goliath-workbench.php?view=seo';if($type==='speaking_press_sponsor_pipeline')return '/dashboard/goliath-workbench.php?view=email';return '/dashboard/goliath-workbench.php';}
function elink($e){return $e==='scorsese'?'/dashboard/scorsese-media-center.php':'/dashboard/goliath-workbench.php?exec='.$e;}
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Goliath V78 Missions</title><link rel="stylesheet" href="/dashboard/assets/goliath-v33.css?v=33"><link rel="stylesheet" href="/dashboard/assets/goliath-v45-final.css?v=456"><style>body{background:#030712;color:#fff}.grid{display:grid;grid-template-columns:1.4fr .8fr;gap:14px}.card{background:#07111f;border:1px solid #ffffff22;border-radius:18px;padding:14px;margin-bottom:12px}.card h3{margin:0;color:#f5d48b}.meta{color:#94a3b8;font-size:12px}.team{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.pill{border:1px solid #ffffff22;background:#0f172a;border-radius:999px;padding:5px 9px;font-size:12px;font-weight:900;color:#fff;text-decoration:none}.brief{white-space:pre-wrap;background:#020617;border-radius:14px;padding:12px}.actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:950px){.grid{grid-template-columns:1fr}}</style></head><body><div class="shell"><?php @require __DIR__.'/includes/goliath-sidebar-v33.php'; ?><main class="main"><section class="top"><div><h1>V78 Mission Engine</h1><p>Mission links now go directly to the relevant work area.</p></div><div class="brandbar actions"><a class="btn" target="_blank" href="/lead-engine/run-goliath-autonomous-cycle.php?key=<?=h($key)?>&mode=hourly">Run Daily Cycle</a><a class="btn" target="_blank" href="/lead-engine/run-goliath-executive-council.php?key=<?=h($key)?>&type=nightly">Run Council</a></div></section><section class="grid"><main><section class="panel"><h2>Team Missions <span><?=count($missions)?> shown</span></h2><div class="inner"><?php foreach($missions as $m): $team=json_decode($m['team']??'[]',true)?:[]; ?><div class="card"><h3><?=h($m['title'])?></h3><div class="meta">#<?=h($m['id'])?> · <?=h($m['mission_type'])?> · <?=h($m['status'])?> · Priority <?=h($m['priority'])?></div><p><?=h($m['business_goal'])?></p><div class="team"><?php foreach($team as $t): ?><a class="pill" href="<?=h(elink($t['exec']??''))?>"><?=h(ucfirst($t['exec']??''))?> — <?=h($t['asset']??'asset')?></a><?php endforeach;?></div><p><a class="btn small" href="<?=h(mlink($m['mission_type']))?>">Open This Work</a></p></div><?php endforeach;?></div></section></main><aside><section class="panel"><h2>Latest Council Brief</h2><div class="inner"><?php if(count($sessions)): $s=$sessions[0]; ?><div class="card"><h3><?=h($s['title'])?></h3><div class="meta"><?=h($s['created_at'])?></div><div class="brief"><?=h($s['morning_brief'])?></div></div><?php else:?><p>No council sessions yet.</p><?php endif;?></div></section></aside></section></main></div></body></html>