<?php
session_start();
require_once __DIR__.'/../lead-engine/config.php';
require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/goliath-mobile-command.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($s,$p=[]){try{return gdb_all($s,$p)?:[];}catch(Throwable $e){return [];}}
function one($s,$p=[]){try{return gdb_one($s,$p)?:[];}catch(Throwable $e){return [];}}

$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$brief=one("SELECT * FROM daily_briefs ORDER BY brief_date DESC,id DESC LIMIT 1");
$metrics=$brief && !empty($brief['metrics_json'])?json_decode($brief['metrics_json'],true):[];
$actions=$brief && !empty($brief['action_items_json'])?json_decode($brief['action_items_json'],true):[];
$timeline=rows("SELECT * FROM relationship_timeline ORDER BY is_new DESC, created_at DESC LIMIT 60");
$drafts=rows("SELECT ed.*, q.owner_name q_name,q.property_address q_address,q.town q_town,q.campaign FROM jessica_email_drafts ed LEFT JOIN jessica_relationship_queue q ON q.id=ed.queue_id WHERE ed.status IN ('pending_approval','approved') ORDER BY ed.created_at DESC LIMIT 12");
$contacts=rows("SELECT id,owner_name,property_address,town,completion_score,best_phone,phone_1,phone,best_email,email_1,recommended_blog,updated_at FROM scout_intel_dossiers WHERE handoff_status='ready_for_mark' ORDER BY COALESCE(completion_score,0) DESC,updated_at DESC LIMIT 12");
$appts=rows("SELECT * FROM appointment_requests WHERE status IN ('draft','pending','confirmed') ORDER BY COALESCE(start_time,created_at) ASC LIMIT 8");
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover"><title>Goliath Mobile Command</title>
<style>
:root{--gold:#d4af37;--bg:#030712;--panel:#07111f;--line:#ffffff1a;--green:#22c55e;--blue:#60a5fa;--red:#ef4444}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}html,body{margin:0;width:100%;max-width:100%;overflow-x:hidden;background:#030712;color:#fff;font-family:Arial,sans-serif}
body{background:radial-gradient(circle at 0 -8%,rgba(212,175,55,.18),transparent 32%),radial-gradient(circle at 100% 0,rgba(34,197,94,.13),transparent 30%),#030712}.wrap{padding:12px;padding-bottom:86px;max-width:980px;margin:auto}.top{position:sticky;top:0;z-index:20;margin:-12px -12px 12px;padding:calc(12px + env(safe-area-inset-top)) 12px 12px;background:rgba(3,7,18,.95);backdrop-filter:blur(16px);border-bottom:1px solid var(--line)}h1{font-size:24px;margin:0;color:var(--gold)}.muted{color:#94a3b8;font-size:12px;line-height:1.35}.actions{display:flex;gap:8px;overflow-x:auto;margin-top:10px;padding-bottom:3px}.btn{display:inline-flex;align-items:center;justify-content:center;white-space:nowrap;text-decoration:none;border:1px solid #ffffff22;background:#101827;color:#fff;border-radius:13px;padding:10px 12px;font-weight:900;font-size:13px}.gold{background:linear-gradient(135deg,#f6d679,#9f7418)!important;color:#111}.green{background:linear-gradient(135deg,#16a34a,#064e3b)!important}.blue{background:linear-gradient(135deg,#2563eb,#1e3a8a)!important}.red{background:linear-gradient(135deg,#dc2626,#7f1d1d)!important}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:12px}.stat{background:#07111f;border:1px solid var(--line);border-radius:16px;padding:10px}.stat b{font-size:20px;display:block}.stat span{font-size:8px;color:#94a3b8;text-transform:uppercase;font-weight:1000}.panel{background:linear-gradient(135deg,#07111f,#050914);border:1px solid var(--line);border-radius:20px;padding:12px;margin-bottom:12px;box-shadow:0 18px 45px #0007}.panel h2{margin:0 0 10px;color:#d4af37;font-size:16px}.brief{white-space:pre-wrap;color:#dbeafe;line-height:1.45}.card{display:block;text-decoration:none;background:#020617;border:1px solid #ffffff15;border-radius:16px;padding:11px;margin-bottom:8px;color:#fff}.card b{color:#f5d48b}.pill{display:inline-block;border:1px solid #ffffff22;border-radius:999px;padding:3px 7px;font-size:10px;color:#cbd5e1;margin:2px}.new{background:#dc2626;border:0;color:#fff}.phone{color:#86efac;font-weight:1000;font-size:18px}.email{color:#93c5fd}.bottomNav{position:fixed;left:0;right:0;bottom:0;z-index:30;background:rgba(3,7,18,.96);backdrop-filter:blur(16px);border-top:1px solid #ffffff1a;padding:8px 8px calc(8px + env(safe-area-inset-bottom));display:grid;grid-template-columns:repeat(5,1fr);gap:6px}.bottomNav a{text-decoration:none;text-align:center;background:#07111f;border:1px solid #ffffff18;border-radius:14px;padding:8px 3px;font-size:10px;font-weight:900;color:#cbd5e1}.bottomNav a.active{background:#d4af37;color:#111}@media(max-width:390px){.stats{gap:6px}.stat{padding:8px}.stat b{font-size:18px}.btn{font-size:12px;padding:9px 10px}}
</style></head><body><div class="top"><h1>Goliath Command</h1><div class="muted">Your pocket OS: brief, contacts, Jessica drafts, appointments, and live executive timeline.</div><div class="actions"><a class="btn gold" target="_blank" href="/lead-engine/morning-brief-v96-3.php?key=<?=h($key)?>">Refresh Brief</a><a class="btn green" href="/dashboard/scout-ready-contacts.php">Scout</a><a class="btn blue" href="/dashboard/jessica-relationship-center.php">Jessica</a><a class="btn" href="/dashboard/goliath-mission-control.php">Mission</a></div></div>
<div class="wrap">
<section class="stats"><div class="stat"><b><?=h($metrics['metrics']['scout_ready']??0)?></b><span>Ready</span></div><div class="stat"><b><?=h($metrics['metrics']['jessica_drafts']??0)?></b><span>Drafts</span></div><div class="stat"><b><?=h($metrics['metrics']['appointments_today']??0)?></b><span>Appts</span></div><div class="stat"><b><?=h($metrics['metrics']['browser_queue']??0)?></b><span>Browser</span></div></section>
<section class="panel"><h2>Morning Brief</h2><div class="brief"><?=h($brief['summary']??'Run Refresh Brief to generate today’s command briefing.')?></div><?php foreach((array)$actions as $a): ?><div class="card"><b>Next Action</b><div class="muted"><?=h($a)?></div></div><?php endforeach; ?></section>
<section class="panel"><h2>Call Ready</h2><?php foreach($contacts as $c): $phone=$c['best_phone']?:$c['phone_1']?:$c['phone']?:''; $email=$c['best_email']?:$c['email_1']?:''; ?><a class="card" href="/dashboard/scout-ready-contacts.php#contact-<?=h($c['id'])?>"><b><?=h($c['owner_name'])?></b><div class="muted"><?=h($c['property_address'])?> · <?=h($c['town'])?></div><?php if($phone): ?><div class="phone"><?=h($phone)?></div><?php endif; ?><?php if($email): ?><div class="email"><?=h($email)?></div><?php endif; ?><span class="pill"><?=h($c['completion_score'])?>%</span></a><?php endforeach; ?></section>
<section class="panel"><h2>Jessica Drafts</h2><?php foreach($drafts as $d): ?><a class="card" href="/dashboard/jessica-relationship-center.php#draft-<?=h($d['id'])?>"><b><?=h($d['to_name']?:$d['q_name'])?></b><div class="muted"><?=h($d['subject'])?></div><span class="pill new"><?=h($d['status'])?></span><span class="pill"><?=h($d['campaign'])?></span></a><?php endforeach; ?></section>
<section class="panel"><h2>Appointments</h2><?php foreach($appts as $a): ?><div class="card"><b><?=h($a['title'])?></b><div class="muted"><?=h($a['client_name'])?> · <?=h($a['start_time'])?></div><div><?=h($a['location'])?></div><span class="pill"><?=h($a['status'])?></span></div><?php endforeach; ?></section>
<section class="panel"><h2>Live Timeline</h2><?php foreach($timeline as $t): ?><div class="card"><b><?=!empty($t['is_new'])?'🔴 ':''?><?=h($t['title'])?></b><div class="muted"><?=h($t['executive_key'])?> · <?=h($t['event_type'])?> · <?=h($t['created_at'])?></div><div><?=h($t['details'])?></div></div><?php endforeach; ?></section>
</div><nav class="bottomNav"><a class="active" href="/dashboard/goliath-mobile-command.php">Home</a><a href="/dashboard/scout-ready-contacts.php">Scout</a><a href="/dashboard/jessica-relationship-center.php">Jessica</a><a href="/dashboard/gbi-dashboard.php">Browser</a><a href="/dashboard/goliath-mission-control.php">Mission</a></nav></body></html>