<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/goliath-lead-brain.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sbq($ep){$ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json'],CURLOPT_TIMEOUT=>25]);$b=curl_exec($ch);$http=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$d=json_decode($b,true);return ($http>=200&&$http<300&&is_array($d))?$d:[];}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$leads=sbq('goliath_lead_brain?select=*&order=heat_score.desc,created_at.desc&limit=40');
$journeyRows=sbq('goliath_lead_journey?select=*&order=stage_order.asc&limit=1200');
$artifactRows=sbq('goliath_lead_artifacts?select=*&order=created_at.desc&limit=300');
$cmdRows=sbq('goliath_command_bus?select=*&order=created_at.desc&limit=120');
$journey=[];foreach($journeyRows as $j){$journey[$j['lead_id']][]=$j;}
$artifacts=[];foreach($artifactRows as $a){$artifacts[$a['lead_id']][]=$a;}
$cmds=[];foreach($cmdRows as $c){$cmds[$c['lead_id']??'system'][]=$c;}
function progress_pct($rows){if(!$rows)return 0;$done=0;foreach($rows as $r){if(($r['status']??'')==='complete')$done++;}return min(100,round(($done/max(1,count($rows)))*100));}
function heat_class($score){return $score>=85?'hot':($score>=60?'warm':'cool');}
$hot=0;$pipeline=0;$queued=0;foreach($leads as $l){if((int)($l['heat_score']??0)>=85)$hot++;$pipeline+=(float)($l['pipeline_value']??0);}foreach($cmdRows as $c){if(($c['status']??'')==='queued')$queued++;}
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Goliath Lead Brain</title>
<link rel="stylesheet" href="/dashboard/assets/goliath-v33.css?v=33">
<link rel="stylesheet" href="/dashboard/assets/goliath-v45-final.css?v=467">
<link rel="stylesheet" href="/dashboard/assets/goliath-lead-brain-v46-9-2.css?v=4692">
<script>window.GOLIATH_KEY=<?=json_encode($key)?>;</script><script src="/dashboard/assets/goliath-lead-brain-v46-9-2.js?v=4692" defer></script></head><body><div class="shell"><?php require __DIR__.'/includes/goliath-sidebar-v33.php'; ?><main class="main leadBrainMain">
<section class="top lbTop"><div><h1>Lead Brain</h1><p>Every lead becomes a living intelligence file: evidence, content, emails, video, next action and appointment priority.</p></div><div class="brandbar"><button class="btn" id="createTestLead">Create Test Lead</button><a class="btn dark" href="/dashboard/goliath-mission-control.php">Mission Control</a></div></section>
<section class="lbPulse"><div><b><?=count($leads)?></b><span>Total Leads</span></div><div class="hot"><b><?=$hot?></b><span>Hot Leads</span></div><div><b>$<?=number_format($pipeline,0)?></b><span>Pipeline Estimate</span></div><div><b><?=$queued?></b><span>Agent Commands</span></div></section>
<section class="lbLayout"><div class="lbBoard"><div class="lbBoardHead"><h2>Lead Battlefield</h2><span>Red → Green journey proof</span></div><?php if(!$leads): ?><article class="lbEmpty"><h2>No Lead Brain files yet</h2><p>Click Create Test Lead to create Jim Anderson, Montana → Westport. Goliath will create the journey rows and queue every agent.</p></article><?php endif; ?><?php foreach($leads as $lead): $id=$lead['id'];$rows=$journey[$id]??[];$pct=progress_pct($rows);$heat=heat_class((int)($lead['heat_score']??0)); $towns=implode(', ', is_array($lead['target_towns']??null)?$lead['target_towns']:[]);?><article class="lbLeadCard <?=$heat?>" data-lead='<?=h(json_encode($lead,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?>' data-journey='<?=h(json_encode($rows,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?>' data-artifacts='<?=h(json_encode($artifacts[$id]??[],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?>' data-commands='<?=h(json_encode($cmds[$id]??[],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?>' onclick="selectLead(this)"><div class="lbLeadTop"><div><strong><?=h($lead['name']??'New Lead')?></strong><span><?=h(ucfirst($lead['lead_type']??'lead'))?> · <?=h(($lead['current_state']??'Unknown').' → '.($towns?:'Needs town'))?></span></div><em><?=h($lead['heat_score']??50)?></em></div><div class="lbPipeline"><i style="width:<?=$pct?>%"></i></div><div class="lbChips"><span><?=h($lead['budget']??'Budget ?')?></span><span><?=h($lead['timeline']??'Timeline ?')?></span><span><?=h($lead['assigned_agent']??'Jessica')?></span></div><div class="lbMiniStages"><?php foreach($rows as $r): ?><span class="<?=h($r['status']??'pending')?>" title="<?=h($r['title']??$r['stage'])?>"></span><?php endforeach;?></div></article><?php endforeach;?></div>
<aside class="lbBrainPanel" id="brainPanel"><div class="lbPanelInner"><h2>Select a Lead</h2><p>Click any lead to open the full intelligence file: evidence, stage status, artifacts, agent commands and next action.</p><div class="lbPlaceholder">🧠</div></div></aside></section>
<section class="lbAudit"><h2>Commissioning Actions</h2><div class="lbActionGrid"><button onclick="openBrainHelp()">What should happen?</button><a href="/dashboard/goliath-connection-check.php">Connection Preflight</a><a href="/dashboard/goliath-social-calendar.php">Distribution OS</a><a href="/dashboard/goliath-worker-output.php">Worker Output</a></div></section></main></div></body></html>
