<?php
session_start();
require_once __DIR__.'/../lead-engine/config.php';
require_once __DIR__.'/../lead-engine/goliath-db.php';
require_once __DIR__.'/../lead-engine/goliath-v79-asset-os.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/goliath-morning.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
gv79_build_morning_priorities(); $items=gdb_all("SELECT * FROM goliath_morning_priorities WHERE priority_date=? ORDER BY rank_order ASC LIMIT 5",[date('Y-m-d')]); $c=gv79_counts();
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Good Morning Mark</title><link rel="stylesheet" href="/dashboard/assets/goliath-v33.css?v=33"><link rel="stylesheet" href="/dashboard/assets/goliath-v45-final.css?v=456"><style>body{background:#030712;color:#fff}.hero{background:linear-gradient(135deg,#052e16,#0f172a);border:1px solid #22c55e55;border-radius:24px;padding:22px;margin-bottom:14px}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}.metric,.priority{background:#07111f;border:1px solid #ffffff22;border-radius:18px;padding:14px}.metric strong{font-size:30px;color:#f5d48b}.priority{margin-bottom:12px}.priority h3{margin:0;color:#f5d48b}.meta{color:#94a3b8;font-size:12px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}</style></head><body><div class="shell"><?php @require __DIR__.'/includes/goliath-sidebar-v33.php'; ?><main class="main"><section class="hero"><h1>Good Morning Mark</h1><p>Your top five actions, real assets, lead progress, and bottlenecks.</p><div class="actions"><a class="btn" target="_blank" href="/lead-engine/run-goliath-morning-brief.php?key=<?=h($key)?>">Refresh Brief</a><a class="btn dark" href="/dashboard/goliath-assets.php">Open Assets</a></div></section><section class="metrics"><div class="metric"><span>Assigned homeowners</span><br><strong><?=h($c['homeowner_assigned']??0)?></strong></div><div class="metric"><span>Queued homeowners</span><br><strong><?=h($c['homeowner_queued']??0)?></strong></div><div class="metric"><span>Phones found</span><br><strong><?=h($c['phones']??0)?></strong></div><div class="metric"><span>Emails found</span><br><strong><?=h($c['emails']??0)?></strong></div><div class="metric"><span>Real assets</span><br><strong><?=h($c['all']??0)?></strong></div></section><section class="panel"><h2>Top Five Actions</h2><div class="inner"><?php foreach($items as $i): ?><div class="priority"><div class="meta">#<?=h($i['rank_order'])?> · <?=h($i['estimated_value'])?></div><h3><?=h($i['title'])?></h3><p><?=h($i['business_reason'])?></p><a class="btn small" href="<?=h($i['action_url'])?>"><?=h($i['action_label'])?></a></div><?php endforeach;?></div></section></main></div></body></html>