<?php
session_start(); require_once __DIR__.'/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/goliath-command-map-v105.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$links=[
 'Headquarters'=>[['Mission Control','/dashboard/goliath-mission-control.php'],['Mission Intake','/dashboard/mission-control-intake-v105.php'],['Runtime','/dashboard/goliath-organization-runtime.php'],['Organization Kernel','/dashboard/goliath-organization-kernel.php']],
 'Executives'=>[['Scout MLS Intelligence','/dashboard/scout-mls-intelligence-v105.php'],['Jessica Relationship Center','/dashboard/jessica-relationship-center.php'],['Shakespeare Authority Architect','/dashboard/shakespeare-authority-architect.php'],['Scorsese Studio Pro','/dashboard/scorsese-studio-pro-v105.php'],['Einstein Intelligence Center','/dashboard/einstein-intelligence-center.php'],['Sherlock','/dashboard/sherlock-intelligence-center.php'],['Rockefeller','/dashboard/rockefeller-revenue-center.php']],
 'Legacy Useful Pages'=>[['Video Review Studio','/dashboard/video-review-studio.php'],['Large Media Upload','/dashboard/large-media-upload.php'],['Publishing Hub','/dashboard/goliath-publishing-hub.php'],['Deliverables','/dashboard/goliath-deliverables.php'],['Opportunities','/dashboard/goliath-opportunities.php']]
];
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Goliath Command Map</title><link rel="stylesheet" href="/dashboard/assets/goliath-carbon-v105.css"></head><body><div class="wrap"><header class="top"><div><div class="logo">🗺️ GOLIATH COMMAND MAP</div><div class="muted">No more lost pages. Important workspaces stay clickable.</div></div><a class="btn" href="/dashboard/goliath-mission-control.php">Mission Control</a></header><?php foreach($links as $section=>$items): ?><section class="panel" style="margin-top:14px"><h2><?=h($section)?></h2><?php foreach($items as $l): ?><a class="btn" href="<?=h($l[1])?>"><?=h($l[0])?></a> <?php endforeach; ?></section><?php endforeach; ?></div></body></html>