<?php
session_start(); require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
if(file_exists(__DIR__ . '/includes/goliath-nav.php')) require_once __DIR__ . '/includes/goliath-nav.php';
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sbget($ep){$ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json'],CURLOPT_TIMEOUT=>45]);$b=curl_exec($ch);$http=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$d=json_decode($b,true);return ['ok'=>$http>=200&&$http<300,'data'=>is_array($d)?$d:[],'body'=>$b];}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
?><!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><title>Hunter Dashboard</title><style>
body{margin:0;background:#f5f3ef;color:#111827;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}.hero{background:#111827;color:white;padding:30px}.hero h1{font-family:Georgia,serif;color:#c8a96e;font-size:44px;margin:0}.wrap{max-width:1900px;margin:auto;padding:20px}.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.box,.panel{background:white;border-radius:18px;box-shadow:0 4px 18px #0001}.box{padding:18px}.num{font-size:34px;font-weight:900;color:#c8a96e}.panel{overflow:hidden;margin-top:16px}.inner{padding:18px}.btn{background:#c8a96e;color:#111;text-decoration:none;border-radius:10px;padding:10px 14px;font-weight:900;display:inline-block;margin:3px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:12px;border-bottom:1px solid #eee;vertical-align:top}th{background:#faf9f6;color:#777;font-size:11px;text-transform:uppercase}.score{font-size:26px;font-weight:900;color:#c8a96e}
</style></head><body><?php $owners=sbget('municipal_owner_records?select=id&limit=5000');$enrich=sbget('owner_enrichment_queue?select=*&order=priority_score.desc&limit=10');$comp=sbget('owner_compliance_reviews?select=*&order=priority_score.desc&limit=10');$approved=sbget('approved_owner_contact_queue?select=*&order=priority_score.desc&limit=10');$streets=sbget('street_intelligence?select=*&order=street_score.desc&limit=10');$brief=sbget('jessica_briefs?select=*&order=created_at.desc&limit=1'); ?>
<section class='hero'><h1>V20.4 Hunter Intelligence OS</h1><p>Street intelligence, owner research, compliance queue, and Jessica Morning Brief.</p></section><main class='wrap'>
<div class='kpis'><div class='box'><div class='num'><?=count($owners['data'])?></div>Owners</div><div class='box'><div class='num'><?=count($enrich['data'])?></div>Research Queue</div><div class='box'><div class='num'><?=count($comp['data'])?></div>Compliance</div><div class='box'><div class='num'><?=count($approved['data'])?></div>Approved</div><div class='box'><div class='num'><?=count($streets['data'])?></div>Top Streets</div></div>
<section class='panel'><div class='inner'><a class='btn' target='_blank' href='/lead-engine/run-hunter-pipeline.php?key=<?=h($key)?>'>Run Hunter Pipeline</a><a class='btn' href='/dashboard/street-research.php'>Street Research</a><a class='btn' href='/dashboard/street-intelligence.php'>Street Intelligence</a><a class='btn' href='/dashboard/morning-brief.php'>Morning Brief</a><a class='btn' href='/dashboard/video-review-studio.php'>Video Review Studio</a></div></section>
<section class='panel'><div class='inner'><h2>Latest Brief</h2><pre><?=h($brief['data'][0]['summary']??'Run Morning Brief builder.')?></pre></div></section>
<section class='panel'><div class='inner'><h2>Top Streets</h2></div><table><tr><th>Score</th><th>Street</th><th>Signals</th><th>Action</th></tr><?php foreach($streets['data'] as $s):?><tr><td><div class='score'><?=h($s['street_score'])?></div></td><td><strong><?=h($s['street_name'])?></strong><br><?=h($s['town'])?></td><td><?=h($s['jessica_notes'])?></td><td><?=h($s['recommended_action'])?></td></tr><?php endforeach;?></table></section>
</main></body></html>