<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function money($n){return '$'.number_format((float)$n,0);}
function sb164d($m,$ep,$p=null){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$m,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json','Prefer: return=representation'],CURLOPT_TIMEOUT=>30]);
  if($p!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($p));
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$assets=sb164d('GET','internal_asset_performance?select=*&order=performance_date.desc,learning_score.desc,estimated_commission.desc&limit=400');
$briefs=sb164d('GET','internal_learning_briefings?select=*&order=created_at.desc&limit=3');
$events=sb164d('GET','internal_performance_events?select=*&order=created_at.desc&limit=100');
$brief=$briefs[0]??[];
$latest=$assets[0]['performance_date']??date('Y-m-d');
$today=array_values(array_filter($assets,fn($a)=>($a['performance_date']??'')===$latest));
$stats=['assets'=>count($today),'scale'=>0,'repeat'=>0,'improve'=>0,'leads'=>0,'calls'=>0,'commission'=>0];
foreach($today as $a){$rec=$a['recommendation']??''; if(isset($stats[$rec]))$stats[$rec]++; $stats['leads']+=(int)($a['lead_count']??0); $stats['calls']+=(int)($a['call_count']??0); $stats['commission']+=(float)($a['estimated_commission']??0);}
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>V16.4A Internal Learning Brain</title><style>
body{margin:0;background:#f5f3ef;color:#111;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:#111827;color:white;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:38px}.wrap{max-width:1900px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(7,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:26px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{border:0;background:#c8a96e;color:#111;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px;cursor:pointer;text-decoration:none;display:inline-block}.light{background:#f2efe8}.layout{display:grid;grid-template-columns:1fr .34fr;gap:18px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:12px;border-bottom:1px solid #eee;vertical-align:top;font-size:14px}th{font-size:11px;color:#777;text-transform:uppercase;background:#faf9f6}.muted{color:#777;font-size:13px}.score{font-size:30px;font-weight:900;color:#c8a96e}.scale{color:#087b30;font-weight:900}.repeat{color:#0a5ca8;font-weight:900}.improve{color:#9a6200;font-weight:900}.watch{color:#777;font-weight:900}pre{white-space:pre-wrap;background:#111;color:#fff;padding:14px;border-radius:12px;max-height:420px;overflow:auto}@media(max-width:1000px){.grid,.layout{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">V16.4A Internal Learning Brain</div><div>Jessica learns from approvals, distribution, leads, calls, seller opportunities, and revenue signals before external analytics.</div></div><main class="wrap">
<p><a class="btn" target="_blank" href="/lead-engine/build-internal-learning-brain.php?key=<?=h($cronKey)?>">Build Learning Brain</a><a class="btn light" href="/dashboard/creative-review-studio.php">Creative Review</a><a class="btn light" href="/dashboard/blotato-distribution-director.php">Blotato Queue</a><a class="btn light" href="/dashboard/seller-acquisition-director.php">Seller Acquisition</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=h($stats['assets'])?></div>Assets</div><div class="kpi"><div class="n"><?=h($stats['scale'])?></div>Scale</div><div class="kpi"><div class="n"><?=h($stats['repeat'])?></div>Repeat</div><div class="kpi"><div class="n"><?=h($stats['improve'])?></div>Improve</div><div class="kpi"><div class="n"><?=h($stats['leads'])?></div>Leads</div><div class="kpi"><div class="n"><?=h($stats['calls'])?></div>Calls</div><div class="kpi"><div class="n"><?=money($stats['commission'])?></div>Commission</div></section>
<div class="layout"><section class="panel"><h2>Internal Winners & Learning</h2><table><tr><th>Score</th><th>Asset</th><th>Signals</th><th>Revenue</th><th>Jessica Says</th></tr><?php foreach($today as $a):?><tr><td><div class="score"><?=h($a['learning_score'])?></div><div class="<?=h($a['recommendation'])?>"><?=h($a['recommendation'])?></div></td><td><strong><?=h($a['asset_title'])?></strong><div class="muted"><?=h($a['brand_pillar'])?> / <?=h($a['content_type'])?><br><?=h($a['source_table'])?><br><?=h($a['town'])?></div></td><td class="muted">Created <?=h($a['created_count'])?><br>Approved <?=h($a['approved_count'])?><br>Distributed <?=h($a['sent_to_distribution_count'])?><br>Posted <?=h($a['posted_count'])?><br>Leads <?=h($a['lead_count'])?><br>Calls <?=h($a['call_count'])?><br>Appts <?=h($a['appointment_count'])?></td><td><?=money($a['pipeline_value'])?><div class="muted">Commission <?=money($a['estimated_commission'])?><br>Expected <?=money($a['expected_value'])?></div></td><td><?=h($a['recommended_next_action'])?></td></tr><?php endforeach;?></table></section><section class="panel"><h2>Jessica Learning Brief</h2><div style="padding:16px"><pre><?=h($brief['briefing_text']??'Run Build Learning Brain to create briefing.')?></pre></div><h2>Recent Learning Events</h2><table><tr><th>Type</th><th>Asset</th><th>Weight</th></tr><?php foreach($events as $e):?><tr><td><?=h($e['event_type'])?></td><td><?=h($e['asset_title'])?><div class="muted"><?=h($e['brand_pillar'])?></div></td><td><?=h($e['performance_weight'])?></td></tr><?php endforeach;?></table></section></div>
</main></body></html>