<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sb($m,$ep,$p=null){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$m,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json','Prefer: return=representation'],CURLOPT_TIMEOUT=>45]);
  if($p!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($p));
  $b=curl_exec($ch);$h=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$d=json_decode($b,true);
  return ['ok'=>$h>=200&&$h<300,'data'=>is_array($d)?$d:[],'body'=>$b,'http'=>$h];
}
$projects=sb('GET','media_projects?select=*&order=created_at.desc&limit=100')['data'];
$hooks=sb('GET','media_hook_moments?select=*&order=viral_score.desc,created_at.desc&limit=200')['data'];
$notes=sb('GET','media_director_notes?select=*&order=priority.desc,created_at.desc&limit=200')['data'];
$renders=sb('GET','media_render_queue?select=*&order=created_at.desc&limit=200')['data'];
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>V17.1 Shorts Factory</title><style>
body{margin:0;background:#f5f3ef;color:#111;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:#111827;color:white;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:38px}.wrap{max-width:1900px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.panel,.kpi{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001;margin-top:18px;overflow:hidden}.kpi{padding:18px}.n{font-size:30px;font-weight:900;color:#c8a96e}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.inner{padding:16px}.btn{border:0;background:#c8a96e;color:#111;padding:10px 13px;border-radius:9px;font-weight:900;font-size:12px;margin:2px;text-decoration:none;display:inline-block}.light{background:#f2efe8}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:12px;border-bottom:1px solid #eee;vertical-align:top;font-size:14px}th{font-size:11px;color:#777;text-transform:uppercase;background:#faf9f6}.score{font-size:26px;font-weight:900;color:#c8a96e}.muted{color:#777;font-size:13px}pre{white-space:pre-wrap;background:#111;color:#fff;padding:12px;border-radius:10px;max-height:260px;overflow:auto}@media(max-width:1000px){.grid{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">V17.1 Jessica Shorts Factory</div><div>Opus-style hook detection, director notes, story arcs, effect stacks, and render queue.</div></div><main class="wrap">
<p><a class="btn" target="_blank" href="/lead-engine/build-shorts-factory.php?key=<?=h($key)?>">Run Shorts Factory</a><a class="btn light" href="/dashboard/jessica-media-director.php">Media Director</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=count($projects)?></div>Projects</div><div class="kpi"><div class="n"><?=count($hooks)?></div>Hook Moments</div><div class="kpi"><div class="n"><?=count($notes)?></div>Director Notes</div><div class="kpi"><div class="n"><?=count($renders)?></div>Render Queue</div></section>
<section class="panel"><h2>Top Hook Moments</h2><table><tr><th>Score</th><th>Hook</th><th>Driver</th><th>Director Note</th></tr><?php foreach($hooks as $x):?><tr><td><div class="score"><?=h($x['viral_score'])?></div><div class="muted"><?=h($x['hook_time_seconds'])?>s - <?=h($x['hook_end_seconds'])?>s</div></td><td><strong><?=h($x['hook_text'])?></strong><div class="muted"><?=h($x['hook_type'])?> / <?=h($x['audience_target'])?></div></td><td><?=h($x['emotional_driver'])?><div class="muted">Retention <?=h($x['retention_score'])?></div></td><td><?=h($x['director_note'])?></td></tr><?php endforeach;?></table></section>
<section class="panel"><h2>Jessica Director Notes / Scripts</h2><table><tr><th>Priority</th><th>Type</th><th>Note</th></tr><?php foreach($notes as $n):?><tr><td><div class="score"><?=h($n['priority'])?></div></td><td><?=h($n['note_type'])?></td><td><strong><?=h($n['note_title'])?></strong><br><?=h($n['note_body'])?></td></tr><?php endforeach;?></table></section>
<section class="panel"><h2>Render Queue / Effects Stack</h2><table><tr><th>Status</th><th>Format</th><th>Instructions</th><th>Effects</th></tr><?php foreach($renders as $r):?><tr><td><strong><?=h($r['render_status'])?></strong><div class="muted"><?=h($r['render_type'])?></div></td><td><?=h($r['output_format'])?><div class="muted"><?=h($r['caption_preset'])?><br><?=h($r['logo_preset'])?></div></td><td><?=h($r['render_instructions'])?></td><td><pre><?=h(json_encode($r['effect_stack'],JSON_PRETTY_PRINT))?></pre></td></tr><?php endforeach;?></table></section>
</main></body></html>