<?php
session_start();require_once __DIR__.'/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';$type=$_GET['lead_type']??'absentee_owner';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jessica Campaign Approval</title><style>
body{margin:0;background:#05070d;color:#fff;font-family:Arial;padding:22px}main{max-width:900px;margin:auto;background:#0b1422;border:1px solid #d4af3755;border-radius:18px;padding:20px}h1{color:#f6d679}label{display:block;margin:12px 0 5px;color:#cbd5e1;font-weight:bold}input,textarea{width:100%;box-sizing:border-box;background:#030712;color:#fff;border:1px solid #ffffff22;border-radius:10px;padding:12px}textarea{min-height:340px}.actions{display:flex;gap:10px;margin-top:14px}.btn{border:0;border-radius:10px;padding:11px 15px;font-weight:bold;cursor:pointer}.save{background:#334155;color:#fff}.approve{background:#d4af37;color:#111}.stats{background:#020617;border-radius:10px;padding:10px;margin:10px 0;color:#94a3b8}
</style></head><body><main><h1>Jessica Campaign Approval</h1><p>Jessica remains invisible. Every message is sent as Mark Pires. Approving this master campaign authorizes personalization and controlled batch sending to every eligible contact in this audience.</p><div id="stats" class="stats">Loading…</div><label>Subject</label><input id="subject"><label>Master message</label><textarea id="body"></textarea><div class="actions"><button class="btn save" onclick="save('save')">Save Edit</button><button class="btn approve" onclick="save('approve')">Approve Campaign</button></div><pre id="result"></pre></main><script>
const KEY=<?=json_encode($key)?>,TYPE=<?=json_encode($type)?>;async function call(payload){const r=await fetch('/lead-engine/jessica-campaign-api-v111.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:KEY,lead_type:TYPE,...payload})});const t=await r.text();return JSON.parse(t)}
async function load(){const d=await call({action:'get'});if(d.campaign){subject.value=d.campaign.subject_line;body.value=d.campaign.body_text;stats.textContent=`Status: ${d.campaign.approval_status} · Recipients prepared: ${d.recipient_count} · Batch size: ${d.campaign.batch_size}`}}
async function save(action){const d=await call({action,subject_line:subject.value,body_text:body.value});result.textContent=action==='approve'?'Approved. Jessica will continue sending this campaign in controlled batches through the heartbeat.':'Saved.';load()}load();
</script></body></html>