<?php
session_start();
require_once __DIR__.'/../lead-engine/config.php';
require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/jessica-relationship-center.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($s,$p=[]){try{return gdb_all($s,$p)?:[];}catch(Throwable $e){return [];}}
function one($s,$p=[]){try{return gdb_one($s,$p)?:[];}catch(Throwable $e){return [];}}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$drafts=rows("SELECT ed.*, q.owner_name q_name,q.property_address q_address,q.town q_town,q.campaign,q.lead_type,q.priority,q.relationship_stage
 FROM jessica_email_drafts ed
 LEFT JOIN jessica_relationship_queue q ON q.id=ed.queue_id
 WHERE ed.status IN ('pending_approval','approved')
 ORDER BY CASE WHEN ed.status='pending_approval' THEN 0 ELSE 1 END, q.priority DESC, ed.created_at DESC
 LIMIT 100");
$phoneOnly=rows("SELECT * FROM jessica_relationship_queue WHERE status='drafted' AND id NOT IN (SELECT COALESCE(queue_id,0) FROM jessica_email_drafts) ORDER BY priority DESC, created_at DESC LIMIT 50");
$appts=rows("SELECT * FROM appointment_requests WHERE status IN ('draft','pending','confirmed') ORDER BY COALESCE(start_time,created_at) ASC LIMIT 20");
$stats=[
 'drafts'=>(int)(one("SELECT COUNT(*) c FROM jessica_email_drafts WHERE status='pending_approval'")['c']??0),
 'approved'=>(int)(one("SELECT COUNT(*) c FROM jessica_email_drafts WHERE status='approved'")['c']??0),
 'sent'=>(int)(one("SELECT COUNT(*) c FROM jessica_email_drafts WHERE status='sent'")['c']??0),
 'queue'=>(int)(one("SELECT COUNT(*) c FROM jessica_relationship_queue WHERE status IN ('queued','drafted','approved')")['c']??0)
];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><title>Jessica Relationship Center</title>
<style>
:root{--gold:#d4af37;--bg:#030712;--panel:#07111f;--line:#ffffff1a;--green:#22c55e;--blue:#60a5fa}
*{box-sizing:border-box}html,body{margin:0;width:100%;max-width:100%;overflow-x:hidden;background:#030712;color:#fff;font-family:Arial,sans-serif}body{background:radial-gradient(circle at 0 -10%,rgba(212,175,55,.16),transparent 34%),#030712}.wrap{max-width:1280px;margin:auto;padding:14px;padding-bottom:86px}.top{position:sticky;top:0;z-index:10;background:rgba(3,7,18,.94);backdrop-filter:blur(14px);margin:-14px -14px 14px;padding:14px;border-bottom:1px solid var(--line)}h1{color:var(--gold);margin:0}.muted{color:#94a3b8;font-size:13px}.actions{display:flex;gap:8px;overflow-x:auto;margin-top:10px}.btn{border:0;border-radius:12px;padding:10px 12px;text-decoration:none;font-weight:900;color:#fff;background:#101827;cursor:pointer;white-space:nowrap}.gold{background:linear-gradient(135deg,#f6d679,#9f7418)!important;color:#111}.green{background:linear-gradient(135deg,#16a34a,#064e3b)!important}.blue{background:linear-gradient(135deg,#2563eb,#1e3a8a)!important}.red{background:linear-gradient(135deg,#dc2626,#7f1d1d)!important}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:12px}.stat{background:#07111f;border:1px solid var(--line);border-radius:16px;padding:12px}.stat b{font-size:26px}.stat span{display:block;color:#94a3b8;font-size:10px;text-transform:uppercase;font-weight:900}.grid{display:grid;grid-template-columns:1fr 360px;gap:12px}.panel{background:#07111f;border:1px solid var(--line);border-radius:20px;padding:12px;margin-bottom:12px}.draft{background:#020617;border:1px solid #ffffff18;border-radius:18px;margin-bottom:10px;overflow:hidden}.draftHead{padding:12px;display:grid;grid-template-columns:1fr auto;gap:10px;cursor:pointer}.draftHead b{color:#f5d48b}.pill{display:inline-block;border:1px solid #ffffff22;border-radius:999px;padding:3px 7px;font-size:10px;color:#cbd5e1;margin:2px}.body{display:none;border-top:1px solid #ffffff12;padding:12px}.draft.open .body{display:block}input,textarea{width:100%;background:#020617;color:#fff;border:1px solid #ffffff24;border-radius:12px;padding:10px;font-size:16px}textarea{min-height:220px}.row{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.sideCard{background:#020617;border:1px solid #ffffff15;border-radius:14px;padding:10px;margin-bottom:8px}.saveMsg{color:#86efac;display:none;font-weight:900}@media(max-width:850px){.wrap{padding:10px;padding-bottom:80px}.top{margin:-10px -10px 10px;padding:12px}.grid{grid-template-columns:1fr}.stats{grid-template-columns:repeat(4,1fr)}.stat{padding:8px}.stat b{font-size:20px}.draftHead{grid-template-columns:1fr}.desktopOnly{display:none}}
</style></head><body><div class="wrap"><section class="top"><h1>Jessica Relationship Center</h1><div class="muted">Drafts, approvals, appointments, and relationship follow-up. Jessica makes sure Mark never misses a beat.</div><div class="actions"><a class="btn gold" target="_blank" href="/lead-engine/jessica-relationship-engine-v96-2.php?key=<?=h($key)?>&limit=50">Run Jessica Engine</a><a class="btn blue" href="/dashboard/scout-ready-contacts.php">Scout Contacts</a><a class="btn" href="/dashboard/goliath-mission-control.php">Mission Control</a></div></section>
<section class="stats"><div class="stat"><b><?=h($stats['drafts'])?></b><span>Need Review</span></div><div class="stat"><b><?=h($stats['approved'])?></b><span>Approved</span></div><div class="stat"><b><?=h($stats['sent'])?></b><span>Sent</span></div><div class="stat"><b><?=h($stats['queue'])?></b><span>Queue</span></div></section>
<section class="grid"><main class="panel"><h2>Emails Waiting for Mark</h2>
<?php if(!count($drafts)): ?><p class="muted">No Jessica drafts waiting. Run the engine after Scout marks leads ready.</p><?php endif; ?>
<?php foreach($drafts as $d): ?><article class="draft" id="draft-<?=h($d['id'])?>"><div class="draftHead" onclick="this.parentNode.classList.toggle('open')"><div><b><?=h($d['to_name']?:$d['q_name']?:'Contact')?></b><div class="muted"><?=h($d['to_email'])?> · <?=h($d['q_town'])?> · <?=h($d['campaign'])?></div><span class="pill"><?=h($d['status'])?></span><span class="pill"><?=h($d['recommended_blog'])?></span></div><button class="btn">Open</button></div><div class="body"><form onsubmit="jessicaAction(event,this)"><input type="hidden" name="key" value="<?=h($key)?>"><input type="hidden" name="draft_id" value="<?=h($d['id'])?>"><label>Subject</label><input name="subject" value="<?=h($d['subject'])?>"><label>HTML Body</label><textarea name="body_html"><?=h($d['body_html'])?></textarea><label>Text Body</label><textarea name="body_text" style="min-height:120px"><?=h($d['body_text'])?></textarea><div class="row"><button class="btn" name="action" value="save">Save</button><button class="btn blue" name="action" value="approve">Approve</button><button class="btn green" name="action" value="send">Send Now</button><span class="saveMsg">Saved</span></div></form></div></article><?php endforeach; ?>
</main><aside><section class="panel"><h2>Phone-Only Leads</h2><?php foreach($phoneOnly as $p): ?><div class="sideCard"><b><?=h($p['owner_name'])?></b><div class="muted"><?=h($p['property_address'])?> · <?=h($p['town'])?></div><span class="pill"><?=h($p['campaign'])?></span></div><?php endforeach; ?></section><section class="panel"><h2>Appointments</h2><?php foreach($appts as $a): ?><div class="sideCard"><b><?=h($a['title'])?></b><div class="muted"><?=h($a['client_name'])?> · <?=h($a['start_time'])?></div><div><?=h($a['location'])?></div></div><?php endforeach; ?></section></aside></section></div>
<script>
async function jessicaAction(e,form){e.preventDefault();const fd=new FormData(form);const clicked=e.submitter;if(clicked&&clicked.name)fd.set(clicked.name,clicked.value);const res=await fetch('/lead-engine/jessica-draft-action-v96-2.php',{method:'POST',body:fd});const data=await res.json();const msg=form.querySelector('.saveMsg');msg.style.display='inline';msg.textContent=data.ok?'Done.':'Error: '+(data.error||'failed');if(data.ok&&fd.get('action')==='send')setTimeout(()=>location.reload(),800);}
</script></body></html>