<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sb($m,$ep,$p=null){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$m,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json','Prefer: return=representation'],CURLOPT_TIMEOUT=>45]);
  if($p!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($p));
  $b=curl_exec($ch);$h=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$d=json_decode($b,true);
  return ['ok'=>$h>=200&&$h<300,'data'=>is_array($d)?$d:[],'body'=>$b,'http'=>$h];
}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
$intel=sb('GET','media_content_intelligence?select=*&order=viral_score.desc,created_at.desc&limit=100')['data'];
$clips=sb('GET','media_clip_intelligence?select=*&order=viral_score.desc,clip_rank.asc&limit=200')['data'];
$episodes=sb('GET','media_storyline_episodes?select=*&order=created_at.desc&limit=100')['data'];
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>V17.4 Content Intelligence</title><style>
body{margin:0;background:#f5f3ef;color:#111;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:#111827;color:white;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:38px}.wrap{max-width:1900px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001;margin-top:18px;overflow:hidden}.kpi{padding:18px}.n{font-size:32px;font-weight:900;color:#c8a96e}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.inner{padding:16px}.btn{border:0;background:#c8a96e;color:#111;padding:10px 13px;border-radius:9px;font-weight:900;font-size:12px;margin:2px;text-decoration:none;display:inline-block}.light{background:#f2efe8}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:12px;border-bottom:1px solid #eee;vertical-align:top;font-size:14px}th{font-size:11px;color:#777;text-transform:uppercase;background:#faf9f6}.score{font-size:28px;font-weight:900;color:#c8a96e}.muted{color:#777;font-size:13px}pre{white-space:pre-wrap;background:#111;color:#fff;padding:12px;border-radius:10px;max-height:300px;overflow:auto}@media(max-width:1000px){.grid{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">V17.4 Jessica Content Intelligence Engine</div><div>Transcript → Hook → Clip → Caption → CTA → Episode storyline.</div></div><main class="wrap">
<p><a class="btn" target="_blank" href="/lead-engine/build-content-intelligence.php?key=<?=h($key)?>">Run Content Intelligence</a><a class="btn light" href="/dashboard/jessica-render-kit.php">Render Kit</a><a class="btn light" href="/dashboard/jessica-shorts-factory.php">Shorts Factory</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=count($intel)?></div>Analyzed Projects</div><div class="kpi"><div class="n"><?=count($clips)?></div>Intelligent Clips</div><div class="kpi"><div class="n"><?=count($episodes)?></div>Episode Plans</div></section>
<section class="panel"><h2>Content Intelligence</h2><table><tr><th>Score</th><th>Project</th><th>Storyline</th><th>Director Summary</th></tr><?php foreach($intel as $i):?><tr><td><div class="score"><?=h($i['viral_score'])?></div><div class="muted">Lead <?=h($i['lead_conversion_score'])?><br>Episode <?=h($i['episode_score'])?></div></td><td><strong><?=h($i['project_title'])?></strong><div class="muted"><?=h($i['brand_pillar'])?><br><?=h($i['audience_persona'])?></div></td><td><?=h($i['strongest_storyline'])?><div class="muted"><?=h($i['primary_emotion'])?></div></td><td><?=h($i['director_summary'])?></td></tr><?php endforeach;?></table></section>
<section class="panel"><h2>Ranked Clip Intelligence</h2><table><tr><th>Score</th><th>Clip</th><th>Hook / Caption</th><th>Visual Direction</th></tr><?php foreach($clips as $c):?><tr><td><div class="score"><?=h($c['viral_score'])?></div><div class="muted">Retention <?=h($c['retention_score'])?><br>Conversion <?=h($c['conversion_score'])?></div></td><td><strong>#<?=h($c['clip_rank'])?> <?=h($c['clip_title'])?></strong><div class="muted"><?=h($c['platform'])?><br><?=h($c['start_seconds'])?>s - <?=h($c['end_seconds'])?>s</div></td><td><strong><?=h($c['hook_line'])?></strong><br><?=nl2br(h($c['caption_text']))?><div class="muted"><?=h($c['hashtags'])?></div></td><td><?=h($c['edit_direction'])?><div class="muted"><?=h($c['thumbnail_prompt'])?><br><?=h($c['logo_direction'])?></div></td></tr><?php endforeach;?></table></section>
<section class="panel"><h2>Storyline Episode Plans</h2><table><tr><th>Episode</th><th>Arc</th><th>Director Notes</th></tr><?php foreach($episodes as $e):?><tr><td><strong><?=h($e['episode_title'])?></strong><div class="muted"><?=h($e['episode_length_target'])?></div></td><td><strong>Cold Open:</strong> <?=h($e['cold_open'])?><br><strong>Act 1:</strong> <?=h($e['act_one'])?><br><strong>Act 2:</strong> <?=h($e['act_two'])?><br><strong>Act 3:</strong> <?=h($e['act_three'])?><br><strong>CTA:</strong> <?=h($e['closing_cta'])?></td><td><?=h($e['director_notes'])?><div class="muted"><?=h($e['broll_notes'])?></div></td></tr><?php endforeach;?></table></section>
</main></body></html>