<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sb137d($m,$ep,$p=null){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$m,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json','Prefer: return=representation'],CURLOPT_TIMEOUT=>25]);
  if($p!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($p));
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$systems=sb137d('GET','jessica_system_registry?select=*&status=eq.active&order=display_order.asc');
$runs=sb137d('GET','jessica_master_runs?select=*&order=created_at.desc&limit=10');
$latest=$runs[0]??[];
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>V13.7 Jessica Master Control</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:38px}.wrap{max-width:1700px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:30px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{border:0;display:inline-block;background:#c8a96e;color:#111;text-decoration:none;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px;cursor:pointer}.light{background:#f2efe8;color:#111}.layout{display:grid;grid-template-columns:1fr .36fr;gap:18px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:11px;border-bottom:1px solid #eee;font-size:14px;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:#777;background:#faf9f6}.muted{color:#777;font-size:13px}pre{white-space:pre-wrap;background:#111;color:#fff;padding:16px;border-radius:12px}.ok{color:#14783c;font-weight:900}.bad{color:#b00020;font-weight:900}@media(max-width:1000px){.grid,.layout{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">V13.7 Jessica Master Control Tower</div><div>One screen to run, navigate, and verify the full Jessica system</div></div><main class="wrap">
<p><a class="btn" target="_blank" href="/lead-engine/run-master-control.php?key=<?=h($cronKey)?>">Run Full Morning Sequence</a><a class="btn light" target="_blank" href="/lead-engine/run-master-control.php?key=<?=h($cronKey)?>&mode=light">Run Light Check</a><a class="btn light" href="/dashboard/opportunity-pipeline.php">Pipeline</a><a class="btn light" href="/dashboard/voice-intelligence.php">Voice</a><a class="btn light" href="/dashboard/listing-intelligence-center.php">Listings</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=h($latest['steps_ok']??0)?></div>Steps OK</div><div class="kpi"><div class="n"><?=h($latest['steps_failed']??0)?></div>Failed</div><div class="kpi"><div class="n"><?=h(count($systems))?></div>Systems</div><div class="kpi"><div class="n"><?=h(!empty($latest['ok'])?'YES':'NO')?></div>Latest OK</div></section>
<div class="layout"><section class="panel"><h2>Jessica Systems</h2><table><tr><th>Order</th><th>System</th><th>Group</th><th>Links</th><th>Time</th></tr><?php foreach($systems as $s):?><tr><td><?=h($s['display_order'])?></td><td><strong><?=h($s['system_name'])?></strong><div class="muted"><?=h($s['notes'])?></div></td><td><?=h($s['system_group'])?></td><td><a class="btn" href="<?=h($s['dashboard_url'])?>">Dashboard</a><a class="btn light" target="_blank" href="<?=h($s['builder_url'])?>?key=<?=h($cronKey)?>">Run</a></td><td><?=h($s['recommended_time'])?></td></tr><?php endforeach;?></table></section><section class="panel"><h2>Latest Master Run</h2><div style="padding:16px"><pre><?=h($latest['briefing_text']??'Run Master Control to create briefing.')?></pre></div><h2>Run History</h2><table><tr><th>Time</th><th>OK</th><th>Steps</th></tr><?php foreach($runs as $r):?><tr><td><?=h($r['created_at'])?></td><td class="<?=!empty($r['ok'])?'ok':'bad'?>"><?=h(!empty($r['ok'])?'OK':'FAIL')?></td><td><?=h($r['steps_ok'])?> / <?=h($r['steps_attempted'])?></td></tr><?php endforeach;?></table></section></div>
</main></body></html>