<?php
session_start(); require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
if(file_exists(__DIR__.'/includes/goliath-nav.php')) require_once __DIR__.'/includes/goliath-nav.php';
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><title>Jessica Drive Mode</title><style>
body{margin:0;background:#070b14;color:white;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.hero{padding:22px;background:linear-gradient(135deg,#111827,#070b14);border-bottom:2px solid #c8a96e}.hero h1{font-family:Georgia,serif;color:#c8a96e;font-size:34px;margin:0}.wrap{max-width:760px;margin:auto;padding:18px}.panel{background:#0f172a;border:1px solid #263042;border-radius:22px;padding:18px;margin:14px 0;box-shadow:0 12px 40px #0005}.bigmic{width:180px;height:180px;border-radius:999px;border:4px solid #c8a96e;background:#c8a96e;color:#111;font-size:54px;font-weight:900;display:block;margin:20px auto;box-shadow:0 0 40px #c8a96e55}.bigmic.listening{background:#ef4444;color:white;border-color:#ef4444;animation:pulse 1s infinite}@keyframes pulse{0%{transform:scale(1)}50%{transform:scale(1.04)}100%{transform:scale(1)}}.quick{display:grid;grid-template-columns:1fr 1fr;gap:10px}.btn{border:0;background:#1f2937;color:white;border-radius:16px;padding:15px;font-weight:900;font-size:15px}.btn.gold{background:#c8a96e;color:#111}.chat{max-height:48vh;overflow:auto}.msg{padding:13px 15px;border-radius:16px;margin:10px 0;white-space:pre-wrap;line-height:1.35}.user{background:#c8a96e;color:#111;margin-left:25px}.jessica{background:#111827;color:white;margin-right:25px;border:1px solid #263042}textarea{width:100%;box-sizing:border-box;background:#070b14;color:white;border:1px solid #263042;border-radius:14px;padding:12px;font-size:16px}.small{color:#94a3b8;font-size:13px}.status{text-align:center;color:#c8a96e;font-weight:900}
</style></head><body><section class="hero"><h1>Jessica Drive Mode</h1><p>Talk to Goliath OS while you plan, drive, research, and execute.</p></section><main class="wrap"><section class="panel"><div class="status" id="status">Tap mic and speak.</div><button class="bigmic" id="mic">🎤</button><div class="quick"><button class="btn gold" data-q="Read my morning brief.">Morning Brief</button><button class="btn" data-q="What is my highest priority lead or opportunity?">Top Opportunity</button><button class="btn" data-q="What streets should I research today?">Hunter Streets</button><button class="btn" data-q="What content should I film today?">Content Plan</button><button class="btn" data-q="What ad should I focus on?">Ad Plan</button><button class="btn" data-q="What should I do next?">Next Action</button></div></section><section class="panel chat" id="chat"></section><section class="panel"><textarea id="manual" rows="3" placeholder="Type to Jessica if voice is unavailable..."></textarea><button class="btn gold" id="send" style="width:100%;margin-top:10px">Send</button><p class="small">Browser voice works now. Kokoro endpoint support is ready in settings for the next bridge step.</p></section></main><script>
const KEY=<?=json_encode($key)?>, mic=document.getElementById('mic'), chat=document.getElementById('chat'), statusEl=document.getElementById('status'), manual=document.getElementById('manual');
function add(role,text){const d=document.createElement('div');d.className='msg '+(role==='user'?'user':'jessica');d.textContent=text;chat.appendChild(d);chat.scrollTop=chat.scrollHeight;}
function speak(text){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=1;u.pitch=1;speechSynthesis.speak(u);}catch(e){}}
async function ask(text){add('user',text);statusEl.textContent='Jessica is thinking...';const res=await fetch('/lead-engine/jessica-drive-api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:KEY,action:'ask',message:text})});const data=await res.json();const reply=data.response||'I had trouble reading Goliath OS.';add('jessica',reply);statusEl.textContent='Tap mic and speak.';speak(reply);}
mic.onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){statusEl.textContent='Speech recognition unavailable. Use typed box.';return;}const rec=new SR();rec.lang='en-US';rec.interimResults=false;rec.maxAlternatives=1;mic.classList.add('listening');statusEl.textContent='Listening...';rec.onresult=e=>{mic.classList.remove('listening');ask(e.results[0][0].transcript);};rec.onerror=e=>{mic.classList.remove('listening');statusEl.textContent='Voice error: '+e.error;};rec.onend=()=>mic.classList.remove('listening');rec.start();};
document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>ask(b.dataset.q));document.getElementById('send').onclick=()=>{const t=manual.value.trim();if(t){manual.value='';ask(t);}};add('jessica','Jessica Drive Mode is ready. Ask me for your morning brief, top opportunity, strongest street, content plan, ad plan, or next action.');
</script></body></html>