<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
require_once __DIR__ . '/includes/goliath-ui.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
if(file_exists(__DIR__ . '/includes/goliath-nav.php')) require_once __DIR__ . '/includes/goliath-nav.php';
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Goliath / Jessica Core Assistant</title><style>
body{margin:0;background:#f5f3ef;color:#111827;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.hero{background:linear-gradient(135deg,#111827,#0b1020);color:white;padding:28px 24px}.hero h1{font-family:Georgia,serif;color:#c8a96e;font-size:44px;margin:0 0 8px}.wrap{max-width:1900px;margin:auto;padding:18px}.layout{display:grid;grid-template-columns:290px 1fr 340px;gap:16px}.panel{background:#fff;border-radius:18px;box-shadow:0 3px 16px #0001;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:15px 16px;border-bottom:1px solid #eee}.inner{padding:16px}.mode{display:block;width:100%;border:0;background:#f4efe5;margin:6px 0;padding:12px;border-radius:12px;text-align:left;font-weight:900;cursor:pointer}.mode.active{background:#111827;color:white}.chat{height:62vh;overflow:auto;background:#fff;padding:16px}.msg{margin:10px 0;max-width:82%;padding:12px 14px;border-radius:14px;white-space:pre-wrap;line-height:1.4}.user{margin-left:auto;background:#111827;color:white}.jessica{background:#f4efe5;color:#111}.inputbar{display:flex;gap:8px;border-top:1px solid #eee;padding:12px;background:#fff}textarea{flex:1;border:1px solid #ddd;border-radius:12px;padding:12px;font-size:15px;height:54px}.btn{border:0;background:#c8a96e;color:#111;padding:10px 14px;border-radius:10px;font-weight:900;cursor:pointer}.btn.dark{background:#111827;color:white}.kpi{display:grid;grid-template-columns:1fr 1fr;gap:10px}.box{background:#f4efe5;border-radius:14px;padding:12px}.num{font-size:26px;font-weight:900;color:#c8a96e}.priority{border-left:4px solid #c8a96e;padding:10px;background:#fffdf8;margin:8px 0;border-radius:8px}.small{font-size:12px;color:#666}.voice{display:flex;gap:8px;align-items:center;margin-top:10px}@media(max-width:1100px){.layout{grid-template-columns:1fr}.chat{height:55vh}}</style><link rel="stylesheet" href="/dashboard/assets/goliath-os.css?v=4"><link rel="icon" href="/dashboard/assets/goliath-ai-full-logo.png?v=4"><?php goliath_ui_head(); ?></head><body><?php goliath_ui_open(); ?>
<section class="hero"><h1>Goliath / Jessica Core Assistant</h1><div>Talk to Goliath OS directly. No Retell. No Twilio. Browser voice + internal intelligence.</div></section>
<main class="wrap"><div class="layout">
<aside class="panel"><h2>Modes</h2><div class="inner">
<button class="mode active" data-mode="executive">Executive</button><button class="mode" data-mode="lead">Lead Brain</button><button class="mode" data-mode="creative">Creative Brain</button><button class="mode" data-mode="advertising">Advertising</button><button class="mode" data-mode="research">Research</button><button class="mode" data-mode="revenue">Revenue</button>
<div class="voice"><button class="btn dark" id="talkBtn">🎤 Talk</button><button class="btn" id="speakBtn">🔊 Speak</button></div><p class="small">Say: “Hey Jessica, what should I focus on today?”</p></div></aside>
<section class="panel"><h2>Jessica Chat</h2><div class="chat" id="chat"></div><div class="inputbar"><textarea id="message" placeholder="Ask Jessica..."></textarea><button class="btn" id="send">Send</button></div></section>
<aside class="panel"><h2>Executive Brief</h2><div class="inner" id="brief"><p>Loading Jessica Core...</p></div></aside>
</div></main>
<script>
const KEY=<?=json_encode($key)?>;let mode='executive',lastJessica='';const chat=document.getElementById('chat'),msg=document.getElementById('message'),brief=document.getElementById('brief');
function add(role,text){const d=document.createElement('div');d.className='msg '+(role==='user'?'user':'jessica');d.textContent=text;chat.appendChild(d);chat.scrollTop=chat.scrollHeight;if(role==='jessica')lastJessica=text;}
async function api(payload){const res=await fetch('/lead-engine/jessica-core.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,key:KEY})});return await res.json();}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function renderBrief(b){if(!b||!b.summary){brief.innerHTML='<p>No brief yet.</p>';return;}let html='<div class="kpi">';html+=`<div class="box"><div class="num">${b.summary.new_leads}</div>Recent Leads</div>`;html+=`<div class="box"><div class="num">${b.summary.hot_leads}</div>Hot Leads</div>`;html+=`<div class="box"><div class="num">${b.summary.campaigns}</div>Campaigns</div>`;html+=`<div class="box"><div class="num">${b.summary.creative_items}</div>Creative Items</div>`;html+='</div><h3>Priorities</h3>';(b.priorities||[]).forEach(p=>html+=`<div class="priority">${esc(p)}</div>`);brief.innerHTML=html;}
async function loadBrief(){try{const b=await api({action:'brief'});renderBrief(b);add('jessica',(b.greeting||'Jessica Core online')+"\\n\\nAsk me what to focus on today, who to call, what to film, or which campaign to review.");}catch(e){brief.innerHTML='<p>Jessica Core API error.</p>';}}
async function send(){const text=msg.value.trim();if(!text)return;add('user',text);msg.value='';add('jessica','Thinking...');const thinking=chat.lastChild;try{const r=await api({action:'ask',message:text,mode});thinking.textContent=r.response||'No response.';lastJessica=thinking.textContent;if(r.brief)renderBrief(r.brief);}catch(e){thinking.textContent='Jessica Core had an API error.';}}
document.getElementById('send').onclick=send;msg.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}});
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;add('jessica','Switched to '+b.textContent+' mode.');});
document.getElementById('speakBtn').onclick=()=>{if(!lastJessica)return;const u=new SpeechSynthesisUtterance(lastJessica);u.rate=1;u.pitch=1;speechSynthesis.speak(u);};
document.getElementById('talkBtn').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){add('jessica','Your browser does not support SpeechRecognition. Use Chrome or Edge.');return;}const rec=new SR();rec.lang='en-US';rec.interimResults=false;rec.maxAlternatives=1;rec.onresult=e=>{msg.value=e.results[0][0].transcript;send();};rec.onerror=e=>add('jessica','Voice recognition error: '+e.error);rec.start();};
loadBrief();
</script><?php goliath_ui_close(); ?></body></html>