<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sb123d($ep){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPGET=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY],CURLOPT_TIMEOUT=>25]);
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$runs=sb123d('launch_control_runs?select=*&order=created_at.desc&limit=20');
$campaigns=sb123d('first_campaign_plan?select=*&order=priority_score.desc,created_at.desc&limit=100');
$imports=sb123d('compliant_lead_imports?select=*&order=lead_score.desc,created_at.desc&limit=50');
$appts=sb123d('appointment_requests?select=*&order=created_at.desc&limit=50');
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
$stats=['runs'=>count($runs),'campaigns'=>count($campaigns),'imports'=>count($imports),'call_eligible'=>0,'appointments'=>count($appts)];
foreach($imports as $i){if(!empty($i['call_eligible']))$stats['call_eligible']++;}
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>V12.3 Launch Control</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:36px}.wrap{max-width:1500px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:30px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{display:inline-block;background:#c8a96e;color:#111;text-decoration:none;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px}.light{background:#f2efe8;color:#111}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:11px;border-bottom:1px solid #eee;font-size:14px;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:#777;background:#faf9f6}.layout{display:grid;grid-template-columns:1fr .45fr;gap:18px}.muted{color:#777;font-size:13px}@media(max-width:1000px){.grid,.layout{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">V12.3 Launch Control</div><div>One button to wake up Jessica’s research, discovery, compliant import, appointment, and campaign systems</div></div><main class="wrap">
<p><a class="btn" target="_blank" href="/lead-engine/run-launch-control.php?key=<?=h($cronKey)?>">Run Launch Control</a><a class="btn light" href="/dashboard/safe-source-importer.php">Safe Source Importer</a><a class="btn light" href="/dashboard/appointment-automation.php">Appointments</a><a class="btn light" href="/dashboard/discovery-intelligence.php">Discovery</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=h($stats['runs'])?></div>Launch Runs</div><div class="kpi"><div class="n"><?=h($stats['campaigns'])?></div>Campaign Drafts</div><div class="kpi"><div class="n"><?=h($stats['imports'])?></div>Imports</div><div class="kpi"><div class="n"><?=h($stats['call_eligible'])?></div>Call Eligible</div><div class="kpi"><div class="n"><?=h($stats['appointments'])?></div>Appointments</div></section>
<div class="layout"><section class="panel"><h2>First Campaign Drafts</h2><table><tr><th>Score</th><th>Campaign</th><th>Offer</th><th>Ad Copy</th><th>Landing</th></tr><?php foreach($campaigns as $c):?><tr><td><strong><?=h($c['priority_score'])?></strong><br><?=h($c['status'])?></td><td><strong><?=h($c['campaign_name'])?></strong><div class="muted"><?=h($c['market'])?><br><?=h($c['town'])?><br><?=h($c['audience'])?></div></td><td><?=h($c['primary_offer'])?></td><td><strong><?=h($c['ad_headline'])?></strong><br><?=h($c['ad_body'])?><div class="muted">CTA: <?=h($c['cta'])?></div></td><td><?=h($c['landing_page'])?></td></tr><?php endforeach;?></table></section>
<section class="panel"><h2>Recent Launch Runs</h2><table><tr><th>Time</th><th>OK</th><th>Steps</th></tr><?php foreach($runs as $r):?><tr><td><?=h($r['created_at'])?></td><td><?=h(!empty($r['ok'])?'yes':'no')?></td><td><?=h($r['steps_ok'])?> ok / <?=h($r['steps_failed'])?> failed</td></tr><?php endforeach;?></table><h2>Recent Imports</h2><table><tr><th>Lead</th><th>Status</th></tr><?php foreach($imports as $i):?><tr><td><?=h($i['name'] ?: 'Research Target')?><div class="muted"><?=h($i['town'])?><br><?=h($i['lead_type'])?></div></td><td><?=h($i['approval_status'])?><br>Call <?=h(!empty($i['call_eligible'])?'yes':'no')?></td></tr><?php endforeach;?></table></section></div>
</main></body></html>