<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
require_once __DIR__ . '/includes/goliath-ui.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sb1214d($ep){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPGET=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY],CURLOPT_TIMEOUT=>25]);
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$rows=sb1214d('market_heat_snapshots?select=*&order=total_heat.desc,created_at.desc&limit=100');
$briefs=sb1214d('market_heat_daily_briefings?select=*&order=created_at.desc&limit=10');
$brief=$briefs[0]??[];
$stats=['total'=>count($rows),'fire'=>0,'hot'=>0,'warm'=>0,'cold'=>0];
foreach($rows as $r){$b=$r['heat_band']??'cold';if(isset($stats[$b]))$stats[$b]++;}
$max=1;foreach($rows as $r){$max=max($max,(int)($r['total_heat']??0));}
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Goliath Market Heat Map</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:38px}.wrap{max-width:1600px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:30px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{display:inline-block;background:#c8a96e;color:#111;text-decoration:none;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px}.light{background:#f2efe8;color:#111}.layout{display:grid;grid-template-columns:1fr .45fr;gap:18px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:11px;border-bottom:1px solid #eee;font-size:14px;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:#777;background:#faf9f6}.muted{color:#777;font-size:13px}.barbg{background:#eee;border-radius:999px;overflow:hidden;height:14px}.bar{height:14px;background:#c8a96e;border-radius:999px}.fire{color:#9b1c1c;font-weight:900}.hot{color:#9a6400;font-weight:900}.warm{color:#14783c;font-weight:900}.cold{color:#777;font-weight:900}pre{white-space:pre-wrap;background:#111;color:#fff;padding:16px;border-radius:12px}@media(max-width:1000px){.grid,.layout{grid-template-columns:1fr}.wrap{padding:14px}}</style><link rel="stylesheet" href="/dashboard/assets/goliath-os.css?v=4"><link rel="icon" href="/dashboard/assets/goliath-ai-full-logo.png?v=4"><?php goliath_ui_head(); ?></head><body><?php goliath_ui_open(); ?><div class="header"><div class="brand">Market Heat Map V12.14</div><div>Town-by-town demand signals for sellers, buyers, relocation, builders, campaigns, and SEO</div></div><main class="wrap">
<p><a class="btn" target="_blank" href="/lead-engine/build-market-heat-map.php?key=<?=h($cronKey)?>">Build Heat Map</a><a class="btn light" href="/dashboard/daily-command-center.php">Command Center</a><a class="btn light" href="/dashboard/hunter-mode.php">Hunter</a><a class="btn light" href="/dashboard/seo-aeo-engine.php">SEO/AEO</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=h($stats['total'])?></div>Markets</div><div class="kpi"><div class="n"><?=h($stats['fire'])?></div>Fire</div><div class="kpi"><div class="n"><?=h($stats['hot'])?></div>Hot</div><div class="kpi"><div class="n"><?=h($stats['warm'])?></div>Warm</div><div class="kpi"><div class="n"><?=h($stats['cold'])?></div>Cold</div></section>
<div class="layout"><section class="panel"><h2>Market Heat Ranking</h2><table><tr><th>Town</th><th>Total</th><th>Heat Mix</th><th>Action</th></tr><?php foreach($rows as $r):?><tr><td><strong><?=h($r['town'])?></strong><br><span class="<?=h($r['heat_band'])?>"><?=h($r['heat_band'])?></span><div class="muted"><?=h($r['market'])?></div></td><td><strong><?=h($r['total_heat'])?></strong><div class="barbg"><div class="bar" style="width:<?=h(round(((int)$r['total_heat']/$max)*100))?>%"></div></div><div class="muted">$<?=h($r['recommended_budget'])?> suggested test budget</div></td><td>Seller <?=h($r['seller_heat'])?><br>Buyer <?=h($r['buyer_heat'])?><br>Relocation <?=h($r['relocation_heat'])?><br>Builder <?=h($r['builder_heat'])?><br>Campaign <?=h($r['campaign_heat'])?><br>SEO <?=h($r['seo_heat'])?></td><td><?=h($r['recommended_action'])?></td></tr><?php endforeach;?></table></section>
<section class="panel"><h2>Heat Brief</h2><div style="padding:16px"><pre><?=h($brief['briefing_text']??'Run Heat Map to create briefing.')?></pre></div><h2>Brief History</h2><table><tr><th>Date</th><th>Top</th><th>Fire</th><th>Hot</th></tr><?php foreach($briefs as $b):?><tr><td><?=h($b['briefing_date'])?></td><td><?=h($b['top_town'])?></td><td><?=h($b['fire_towns'])?></td><td><?=h($b['hot_towns'])?></td></tr><?php endforeach;?></table></section></div>
</main><?php goliath_ui_close(); ?></body></html>