<?php
session_start(); require_once __DIR__.'/../lead-engine/config.php'; require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/mission-control-intake-v105.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mission Control Intake</title><link rel="stylesheet" href="/dashboard/assets/goliath-carbon-v105.css"></head><body><div class="wrap">
<header class="top"><div><div class="logo">⚡ MISSION CONTROL INTAKE</div><div class="muted">One front door: video, MLS CSV, content, projects</div></div><div><a class="btn" href="/dashboard/goliath-mission-control.php">Mission Control</a><a class="btn" href="/dashboard/goliath-command-map-v105.php">Command Map</a></div></header>
<section class="two"><main class="panel"><h2>Upload Raw Video to Scorsese</h2><form method="post" enctype="multipart/form-data" action="/lead-engine/scorsese-raw-video-upload-v105.php"><input type="hidden" name="key" value="<?=h($key)?>"><input name="title" placeholder="Title"><select name="brand_style"><option>Discover Connecticut</option><option>Mark Pires Real Estate</option><option>House Detective</option><option>BeatSeat</option><option>LegacySaved</option></select><input type="file" name="raw_video" accept=".mp4,.mov,.m4v,.webm" required><textarea name="prompt" rows="5">Find hooks, short clips, captions, titles, thumbnails, and strongest viral moments.</textarea><button class="gold">Send to Scorsese</button></form></main>
<aside class="panel"><h2>Upload MLS CSV to Scout</h2><form method="post" enctype="multipart/form-data" action="/lead-engine/scout-mls-upload-v105.php"><input type="hidden" name="key" value="<?=h($key)?>"><select name="listing_type"><option value="active">Active Listings</option><option value="closed">Closed/Sold Listings</option><option value="expired">Expired Listings</option><option value="withdrawn">Withdrawn Listings</option><option value="canceled">Canceled Listings</option></select><input type="file" name="csv_file" accept=".csv,.txt" required><button class="gold">Upload MLS Dataset</button></form><a class="btn" target="_blank" href="/lead-engine/scout-mls-reconcile-v105.php?key=<?=h($key)?>">Run Reconcile</a></aside></section>
<section class="panel" style="margin-top:14px"><h2>Core Executive Workspaces</h2><a class="btn" href="/dashboard/scorsese-studio-pro-v105.php">Scorsese Studio Pro</a> <a class="btn" href="/dashboard/scout-mls-intelligence-v105.php">Scout MLS Intelligence</a> <a class="btn" href="/dashboard/shakespeare-authority-architect.php">Shakespeare Authority</a> <a class="btn" href="/dashboard/goliath-organization-runtime.php">Universal Runtime</a> <a class="btn" href="/dashboard/goliath-organization-kernel.php">Organization Kernel</a></section>
</div></body></html>