<?php
session_start(); require_once __DIR__.'/../lead-engine/config.php';
require_once __DIR__ . '/includes/goliath-ui.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next=/dashboard/mls-intelligence-manager.php');exit;}
if(file_exists(__DIR__.'/includes/goliath-nav.php')) require_once __DIR__.'/includes/goliath-nav.php';
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Goliath MLS Intelligence Manager</title><style>
body{margin:0;background:#f5f3ef;color:#111;font-family:Arial}.hero{background:#111827;color:white;padding:30px}.hero h1{font-family:Georgia,serif;color:#c8a96e}.wrap{max-width:1400px;margin:auto;padding:20px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.panel{background:white;border-radius:18px;padding:20px;box-shadow:0 4px 18px #0001}.btn{background:#c8a96e;border:0;border-radius:10px;padding:12px 16px;font-weight:900;margin:4px;cursor:pointer;text-decoration:none;color:#111;display:inline-block}.run{background:#111827;color:#c8a96e;border:2px solid #c8a96e;font-size:22px;padding:17px 26px}input,select{width:100%;box-sizing:border-box;padding:10px;margin:6px 0 14px;border:1px solid #ddd;border-radius:8px}.prog{height:24px;background:#ddd;border-radius:99px;overflow:hidden}.bar{height:100%;background:#c8a96e;width:0}pre{white-space:pre-wrap;background:#111827;color:white;border-radius:12px;padding:14px;max-height:560px;overflow:auto}@media(max-width:900px){.grid{grid-template-columns:1fr}}</style><link rel="stylesheet" href="/dashboard/assets/goliath-os.css?v=4"><link rel="icon" href="/dashboard/assets/goliath-ai-full-logo.png?v=4"><?php goliath_ui_head(); ?></head><body><?php goliath_ui_open(); ?>
<section class="hero"><h1>Goliath MLS Intelligence Manager</h1><p>RUN GOLIATH now includes: Match → Consolidate Duplicates → Executive Assistant.</p></section>
<main class="wrap"><div class="grid"><section class="panel"><h2>Import MLS Dataset</h2><form id="f"><label>Dataset Type</label><select id="dataset"><option value="closed">Closed / Sold</option><option value="active">Active</option><option value="pending">Pending</option><option value="failed">Failed: Expired / Cancelled / Withdrawn</option></select><label>File</label><input type="file" id="file" accept=".csv,.txt,.xlsx,.XLSX" required><label>Batch Name</label><input id="batch" value="mls_<?=date('Ymd_His')?>"><label>Upload Mode</label><select id="replace"><option value="no">Upload / Add to dataset</option><option value="all">Clear this dataset type, then upload</option><option value="batch">Clear same batch, then upload</option></select><label>Rows Per Upload Save</label><input id="chunkSize" value="1000"><button class="btn">Start Upload</button></form><p id="status">Waiting.</p><div class="prog"><div class="bar" id="bar"></div></div></section><section class="panel"><h2>Run Intelligence</h2><button class="btn run" onclick="runGoliath()">RUN GOLIATH</button><button class="btn" onclick="runConsolidate()">Build Consolidated List Only</button><button class="btn" onclick="runExec()">Run Executive Only</button><a class="btn" href="/dashboard/goliath-opportunities.php">Goliath Opportunities</a><a class="btn" href="/dashboard/executive-assistant.php">Executive Assistant</a><pre id="out">Recommended order: Closed → Active → Pending → Failed → RUN GOLIATH.</pre></section></div></main><script>
const KEY=<?=json_encode($key)?>;
function parseLine(line,delim){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i],n=line[i+1];if(c==='"'&&q&&n==='"'){cur+='"';i++;continue;}if(c==='"'){q=!q;continue;}if(c===delim&&!q){out.push(cur);cur='';continue;}cur+=c;}out.push(cur);return out;}
function detectDelim(first){return first.split('\t').length>=first.split(',').length?'\t':',';}
document.getElementById('f').onsubmit=async e=>{e.preventDefault();const file=document.getElementById('file').files[0];if(!file)return;const dataset=document.getElementById('dataset').value,batch=document.getElementById('batch').value,replace=document.getElementById('replace').value;const text=await file.text();const lines=text.split(/\r?\n/).filter(x=>x.trim().length);if(lines.length<2){document.getElementById('out').textContent='No rows parsed. Export as CSV/tab-delimited text.';return;}const delim=detectDelim(lines[0]);const headers=parseLine(lines[0],delim).map(h=>h.trim());const rows=[];for(let i=1;i<lines.length;i++){const vals=parseLine(lines[i],delim);if(vals.length<2)continue;const obj={};headers.forEach((h,idx)=>obj[h]=vals[idx]??'');rows.push(obj);}const chunkSize=parseInt(document.getElementById('chunkSize').value||'1000',10);let inserted=0,total=Math.ceil(rows.length/chunkSize);document.getElementById('out').textContent=`Parsed ${rows.length} rows for ${dataset}. Headers: ${headers.slice(0,35).join(', ')}\n`;for(let start=0,idx=0;start<rows.length;start+=chunkSize,idx++){document.getElementById('status').textContent=`${dataset}: upload save ${idx+1} of ${total}`;const chunk=rows.slice(start,start+chunkSize);const res=await fetch('/lead-engine/import-mls-dataset-chunk.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:KEY,dataset,batch,replace,chunk_index:idx,rows:chunk})});const txt=await res.text();let data;try{data=JSON.parse(txt)}catch(e){data={success:false,error:txt}}document.getElementById('out').textContent+=JSON.stringify(data,null,2)+"\n";if(!data.success){document.getElementById('status').textContent='Stopped on error.';return;}inserted+=data.inserted||0;document.getElementById('bar').style.width=Math.round(((start+chunk.length)/rows.length)*100)+'%';}document.getElementById('status').textContent=`Done. Inserted ${inserted} ${dataset} rows.`;};
async function runConsolidate(){let r=await fetch('/lead-engine/build-goliath-consolidated-opportunities.php?key='+encodeURIComponent(KEY));document.getElementById('out').textContent=await r.text();}
async function runExec(){let r=await fetch('/lead-engine/build-executive-assistant.php?key='+encodeURIComponent(KEY));document.getElementById('out').textContent=await r.text();}
async function runGoliath(){
 document.getElementById('out').textContent='RUN GOLIATH started. Initializing match...';
 let init=await fetch('/lead-engine/run-goliath-start.php?key='+encodeURIComponent(KEY));let initTxt=await init.text();let initData;try{initData=JSON.parse(initTxt)}catch(e){initData={success:false,error:initTxt}}
 document.getElementById('out').textContent+='\n\nINIT:\n'+JSON.stringify(initData,null,2);if(!initData.success)return;
 let total=initData.total_failed||0,offset=0,limit=1000,agg={reviewed:0,sold_removed:0,active_removed:0,pending_removed:0,never_sold:0,opportunities_created:0};
 while(offset<total){document.getElementById('status').textContent=`Goliath matching ${offset+1}-${Math.min(offset+limit,total)} of ${total}`;let r=await fetch('/lead-engine/build-failed-listing-match-chunk.php?key='+encodeURIComponent(KEY)+'&offset='+offset+'&limit='+limit);let txt=await r.text();let d;try{d=JSON.parse(txt)}catch(e){d={success:false,error:txt}}document.getElementById('out').textContent+='\n\nMATCH CHUNK:\n'+JSON.stringify(d,null,2);if(!d.success){document.getElementById('status').textContent='Goliath stopped on match error.';return;}for(let k of Object.keys(agg))agg[k]+=d[k]||0;offset+=limit;}
 document.getElementById('out').textContent+='\n\nMATCH TOTALS:\n'+JSON.stringify(agg,null,2)+'\n\nConsolidating duplicate properties...';
 let c=await fetch('/lead-engine/build-goliath-consolidated-opportunities.php?key='+encodeURIComponent(KEY));let ct=await c.text();
 document.getElementById('out').textContent+='\n\nCONSOLIDATION:\n'+ct+'\n\nBuilding Executive Assistant...';
 let x=await fetch('/lead-engine/build-executive-assistant.php?key='+encodeURIComponent(KEY));let xt=await x.text();
 document.getElementById('out').textContent+='\n\nEXECUTIVE ASSISTANT:\n'+xt+'\n\nGOLIATH COMPLETE. Open /dashboard/goliath-opportunities.php';
 document.getElementById('status').textContent='Goliath complete.';
}
</script><?php goliath_ui_close(); ?></body></html>