<?php
session_start(); require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function c($t,$f=''){if(!defined('SUPABASE_URL'))return 0;$ep=$t.'?select=id'.($f?'&'.$f:'');$ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.$ep);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPGET=>true,CURLOPT_HEADER=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Prefer: count=exact'],CURLOPT_TIMEOUT=>10]);$r=curl_exec($ch);$hs=curl_getinfo($ch,CURLINFO_HEADER_SIZE);curl_close($ch);$h=substr($r,0,$hs);return preg_match('/content-range:\s*[^\/]+\/(\d+)/i',$h,$m)?(int)$m[1]:0;}
$today=date('Y-m-d').'T00:00:00';$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
$leadTotal=c('leads');$leadsToday=c('leads','created_at=gte.'.rawurlencode($today));$hotLeads=c('leads','lead_score=gte.75');$homeowners=c('homeowner_intelligence');$future=c('future_seller_pipeline','status=eq.active');$drips=c('lead_followup_queue','status=eq.queued');$dnc=c('homeowner_intelligence','dnc_status=eq.listed');$outcomes=c('cold_call_outcomes');
?>
<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Operations Hub</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:34px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:34px}.wrap{max-width:1400px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}.kpi,.card{background:#fff;border-radius:16px;padding:18px;box-shadow:0 2px 12px #0001}.n{font-size:30px;font-weight:900}.l{font-size:11px;color:#777;text-transform:uppercase}.sections{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:22px}.card h2{font-family:Georgia,serif}.btn{display:inline-block;text-decoration:none;background:#10101a;color:#fff;border-radius:10px;padding:10px 12px;font-size:13px;font-weight:800;margin:3px}.gold{background:#c8a96e;color:#111}.light{background:#f2efe8;color:#111}@media(max-width:900px){.grid,.sections{grid-template-columns:1fr}.wrap{padding:14px}}
</style></head><body><div class="header"><div class="brand">Operations Hub</div><div>Lead Machine · Jessica · Homeowner Intelligence · Learning · Forecast</div></div><main class="wrap">
<section class="grid"><div class="kpi"><div class="n"><?=h($leadTotal)?></div><div class="l">Total Leads</div></div><div class="kpi"><div class="n"><?=h($leadsToday)?></div><div class="l">Today</div></div><div class="kpi"><div class="n"><?=h($hotLeads)?></div><div class="l">Hot Leads</div></div><div class="kpi"><div class="n"><?=h($homeowners)?></div><div class="l">Homeowners</div></div><div class="kpi"><div class="n"><?=h($future)?></div><div class="l">Future Sellers</div></div><div class="kpi"><div class="n"><?=h($drips)?></div><div class="l">Drips</div></div></section>
<section class="sections">
<div class="card"><h2>CEO Forecast</h2><a class="btn gold" href="/dashboard/listing-forecast.php">Listing Forecast V6</a><a class="btn light" href="/dashboard/lead-velocity.php">Lead Velocity</a><a class="btn light" href="/dashboard/action-queue.php">Action Queue</a><a class="btn light" href="/dashboard/hot-lead-alerts.php">Hot Alerts</a></div>
<div class="card"><h2>Homeowner Machine</h2><a class="btn gold" href="/dashboard/homeowner-radar.php">Radar</a><a class="btn light" href="/dashboard/homeowner-intelligence.php">Homeowner Intelligence</a><a class="btn light" href="/dashboard/jessica-batch-caller.php">Batch Caller</a><a class="btn light" href="/lead-engine/intelligence/import-homeowners-v3.php">CSV Importer V3</a><p>DNC listed: <?=h($dnc)?></p></div>
<div class="card"><h2>Learning + Pipeline</h2><a class="btn gold" href="/dashboard/call-learning.php">Call Learning V4</a><a class="btn light" href="/dashboard/future-seller-pipeline.php">Future Seller Pipeline</a><a class="btn light" href="/lead-engine/process-call-outcomes.php?key=<?=h($cronKey)?>" target="_blank">Process Outcomes</a><a class="btn light" href="/lead-engine/build-future-sellers.php?key=<?=h($cronKey)?>" target="_blank">Build Future Sellers</a><p>Outcomes: <?=h($outcomes)?></p></div>
<div class="card"><h2>Jessica Follow-Up</h2><a class="btn gold" href="/dashboard/drip-control.php">Drip Control</a><a class="btn light" href="/dashboard/sequence-editor.php">Sequence Editor</a><a class="btn light" href="/lead-engine/seed-followups.php?key=<?=h($cronKey)?>" target="_blank">Seed Followups</a><a class="btn light" href="/dashboard/after-hours-manager.php">After-Hours</a></div>
<div class="card"><h2>Marketing Intelligence</h2><a class="btn gold" href="/dashboard/conversions.php">Conversions</a><a class="btn light" href="/dashboard/source-roi.php">Source ROI</a><a class="btn light" href="/dashboard/utm-builder.php">UTM Builder</a><a class="btn light" href="/towns/" target="_blank">Town Pages</a></div>
<div class="card"><h2>System</h2><a class="btn gold" href="/dashboard/system-health.php">System Health</a><a class="btn light" href="/lead-engine/cron-master.php?key=<?=h($cronKey)?>" target="_blank">Run Cron</a><a class="btn light" href="/lead-engine/build-hot-alerts.php?key=<?=h($cronKey)?>" target="_blank">Build Hot Alerts</a><a class="btn light" href="/lead-engine/dnc-test.php?phone=2035551212" target="_blank">Test DNC</a></div>
</section></main></body></html>