<?php
session_start(); require_once __DIR__ . '/../lead-engine/config.php';
require_once __DIR__ . '/includes/goliath-ui.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
if(file_exists(__DIR__.'/includes/goliath-nav.php')) require_once __DIR__.'/includes/goliath-nav.php';
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sbget($ep){$ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json'],CURLOPT_TIMEOUT=>45]);$b=curl_exec($ch);$h=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$d=json_decode($b,true);return ['ok'=>$h>=200&&$h<300,'data'=>is_array($d)?$d:[],'body'=>$b];}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$rows=sbget('jessica_opportunity_context?select=*&order=score.desc,created_at.desc&limit=300');
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jessica Opportunity Context</title><style>
body{margin:0;background:#f5f3ef;font-family:Arial;color:#111827}.hero{background:#111827;color:white;padding:30px}.hero h1{font-family:Georgia,serif;color:#c8a96e}.wrap{max-width:1700px;margin:auto;padding:20px}.panel{background:white;border-radius:18px;overflow:hidden;box-shadow:0 4px 18px #0001}.btn{background:#c8a96e;color:#111;text-decoration:none;border-radius:10px;padding:10px 14px;font-weight:900}table{width:100%;border-collapse:collapse}td,th{padding:12px;border-bottom:1px solid #eee;text-align:left;vertical-align:top}th{background:#faf9f6;color:#777;font-size:11px;text-transform:uppercase}.score{font-size:30px;color:#c8a96e;font-weight:900}</style><link rel="stylesheet" href="/dashboard/assets/goliath-os.css?v=4"><link rel="icon" href="/dashboard/assets/goliath-ai-full-logo.png?v=4"><?php goliath_ui_head(); ?></head><body><?php goliath_ui_open(); ?>
<section class="hero"><h1>V20.8 Opportunity Context</h1><p>Jessica connects Hunter, leads, content, and ads into monetization actions.</p></section><main class="wrap"><p><a class="btn" target="_blank" href="/lead-engine/build-opportunity-context.php?key=<?=h($key)?>">Build Opportunity Context</a></p><section class="panel"><table><tr><th>Score</th><th>Opportunity</th><th>Summary</th><th>Action</th><th>Content / Ad Tie-In</th></tr><?php foreach($rows['data'] as $r):?><tr><td><div class="score"><?=h($r['score'])?></div><?=h($r['opportunity_type'])?></td><td><strong><?=h($r['title'])?></strong><br><?=h($r['source_table'])?></td><td><?=h($r['summary'])?></td><td><?=h($r['recommended_action'])?></td><td><strong>Content:</strong> <?=h($r['connected_content_idea'])?><br><br><strong>Ad:</strong> <?=h($r['connected_ad_idea'])?></td></tr><?php endforeach;?></table></section></main><?php goliath_ui_close(); ?></body></html>