<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sb1111d($ep){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPGET=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY],CURLOPT_TIMEOUT=>25]);
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$missions=sb1111d('overnight_research_missions?select=*&order=created_at.desc&limit=100');
$targets=sb1111d('lead_research_targets?select=*&order=priority_score.desc,created_at.desc&limit=200');
$imports=sb1111d('data_import_queue?select=*&order=lead_score.desc,created_at.desc&limit=100');
$stats=['missions'=>count($missions),'targets'=>count($targets),'imports'=>count($imports),'seller'=>0,'buyer'=>0,'relocation'=>0,'builder'=>0];
foreach($targets as $t){$type=$t['target_type']??'';if(isset($stats[$type]))$stats[$type]++;}
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Overnight Lead Research V11.11</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:36px}.wrap{max-width:1500px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:30px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{display:inline-block;background:#c8a96e;color:#111;text-decoration:none;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px}.light{background:#f2efe8;color:#111}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:11px;border-bottom:1px solid #eee;font-size:14px;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:#777;background:#faf9f6}.muted{color:#777;font-size:13px}.layout{display:grid;grid-template-columns:1fr .45fr;gap:18px}@media(max-width:1000px){.grid,.layout{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">Overnight Lead Research V11.11</div><div>Jessica research planner: sellers · buyers · NYC/Brooklyn relocation · Westchester movers · builders</div></div><main class="wrap">
<p><a class="btn" target="_blank" href="/lead-engine/build-overnight-research.php?key=<?=h($cronKey)?>">Build Overnight Research Plan</a><a class="btn light" href="/dashboard/command-center.php">Command Center</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=h($stats['missions'])?></div>Missions</div><div class="kpi"><div class="n"><?=h($stats['targets'])?></div>Targets</div><div class="kpi"><div class="n"><?=h($stats['seller'])?></div>Sellers</div><div class="kpi"><div class="n"><?=h($stats['buyer'])?></div>Buyers</div><div class="kpi"><div class="n"><?=h($stats['relocation'])?></div>Relocation</div><div class="kpi"><div class="n"><?=h($stats['builder'])?></div>Builders</div></section>
<div class="layout"><section class="panel"><h2>Research Targets</h2><table><tr><th>Score</th><th>Market</th><th>Audience</th><th>Offer / Ad Angle</th><th>Landing</th></tr><?php foreach($targets as $t):?><tr><td><strong><?=h($t['priority_score'])?></strong><div class="muted"><?=h($t['target_type'])?><br><?=h($t['status'])?></div></td><td><?=h($t['market'])?><div class="muted"><?=h($t['town'])?></div></td><td><?=h($t['audience'])?><div class="muted"><?=h($t['search_query'])?></div></td><td><strong><?=h($t['suggested_offer'])?></strong><br><?=h($t['suggested_ad_angle'])?></td><td><?=h($t['suggested_landing_page'])?></td></tr><?php endforeach;?></table></section>
<section class="panel"><h2>Recent Missions</h2><table><tr><th>Town</th><th>Market</th><th>Status</th></tr><?php foreach($missions as $m):?><tr><td><?=h($m['town'])?></td><td><?=h($m['market'])?><div class="muted"><?=h($m['audience'])?></div></td><td><?=h($m['status'])?><br><?=h($m['run_window_start'])?>-<?=h($m['run_window_end'])?></td></tr><?php endforeach;?></table><h2>Import Queue</h2><table><tr><th>Lead</th><th>Status</th><th>Compliance</th></tr><?php foreach($imports as $i):?><tr><td><?=h($i['name'])?><div class="muted"><?=h($i['phone'])?><br><?=h($i['town'])?></div></td><td><?=h($i['status'])?></td><td><?=h($i['dnc_status'])?><div class="muted"><?=h($i['compliance_notes'])?></div></td></tr><?php endforeach;?></table></section></div>
</main></body></html>