<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sb161d($m,$ep,$p=null){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$m,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json','Prefer: return=representation'],CURLOPT_TIMEOUT=>25]);
  if($p!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($p));
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $id=$_POST['id']??''; $status=$_POST['status']??'';
  if($id && in_array($status,['completed','skipped','deferred','open'],true)){
    sb161d('PATCH','daily_action_queue?id=eq.'.rawurlencode($id),['status'=>$status,'updated_at'=>date('c')]);
    $msg='Action marked '.$status.'.';
  }
}
$rows=sb161d('GET','daily_action_queue?select=*&status=eq.open&order=priority_rank.asc,priority_score.desc,created_at.desc&limit=300');
$briefs=sb161d('GET','queue_intelligence_briefings?select=*&order=created_at.desc&limit=10');
$brief=$briefs[0]??[];
$stats=['total'=>count($rows),'call'=>0,'review'=>0,'ad_launch'=>0,'content'=>0,'watch'=>0];
foreach($rows as $r){$t=$r['queue_type']??'watch'; if(isset($stats[$t]))$stats[$t]++;}
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Queue Intelligence V12.16</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:38px}.wrap{max-width:1600px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:30px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{border:0;display:inline-block;background:#c8a96e;color:#111;text-decoration:none;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px;cursor:pointer}.light{background:#f2efe8;color:#111}.layout{display:grid;grid-template-columns:1fr .42fr;gap:18px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:11px;border-bottom:1px solid #eee;font-size:14px;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:#777;background:#faf9f6}.muted{color:#777;font-size:13px}pre{white-space:pre-wrap;background:#111;color:#fff;padding:16px;border-radius:12px}.call{color:#14783c;font-weight:900}.review{color:#9a6400;font-weight:900}.ad_launch{color:#174ea6;font-weight:900}.content{color:#5a2ca0;font-weight:900}.watch{color:#777;font-weight:900}@media(max-width:1000px){.grid,.layout{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">Queue Intelligence V12.16</div><div>Turns Jessica’s work into today’s safe action list</div></div><main class="wrap"><?php if($msg):?><div class="panel" style="padding:16px"><?=h($msg)?></div><?php endif;?>
<p><a class="btn" target="_blank" href="/lead-engine/build-queue-intelligence.php?key=<?=h($cronKey)?>">Build Queue</a><a class="btn light" href="/dashboard/daily-command-center.php">Command</a><a class="btn light" href="/dashboard/live-ad-launch.php">Live Ads</a><a class="btn light" href="/dashboard/compliant-lead-imports.php">Imports</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=h($stats['total'])?></div>Total</div><div class="kpi"><div class="n"><?=h($stats['call'])?></div>Call</div><div class="kpi"><div class="n"><?=h($stats['review'])?></div>Review</div><div class="kpi"><div class="n"><?=h($stats['ad_launch'])?></div>Ads</div><div class="kpi"><div class="n"><?=h($stats['content'])?></div>Content</div><div class="kpi"><div class="n"><?=h($stats['watch'])?></div>Watch</div></section>
<div class="layout"><section class="panel"><h2>Today’s Action Queue</h2><table><tr><th>Type</th><th>Action</th><th>Contact/Item</th><th>Compliance</th><th>Status</th></tr><?php foreach($rows as $r):?><tr><td class="<?=h($r['queue_type'])?>"><?=h($r['queue_type'])?><div class="muted">Score <?=h($r['priority_score'])?><br>Rank <?=h($r['priority_rank'])?></div></td><td><strong><?=h($r['action_title'])?></strong><div class="muted"><?=h($r['action_reason'])?></div></td><td><strong><?=h($r['name'])?></strong><div class="muted"><?=h($r['phone'])?><br><?=h($r['email'])?><br><?=h($r['town'])?> <?=h($r['market'])?></div></td><td><?=h($r['compliance_status'])?><div class="muted">Call eligible: <?=h(!empty($r['call_eligible'])?'yes':'no')?></div></td><td><form method="post"><input type="hidden" name="id" value="<?=h($r['id'])?>"><button class="btn" name="status" value="completed">Done</button><button class="btn light" name="status" value="deferred">Defer</button><button class="btn light" name="status" value="skipped">Skip</button></form></td></tr><?php endforeach;?></table></section>
<section class="panel"><h2>Queue Brief</h2><div style="padding:16px"><pre><?=h($brief['briefing_text']??'Build queue to create briefing.')?></pre></div><h2>Seller Cold/Warm Script</h2><div style="padding:16px"><pre><?=h("Hi, this is Jessica calling on behalf of Mark Pires. We are checking in with local homeowners because Fairfield County is still showing unusually strong seller conditions. Many homeowners have more equity and financial flexibility than they realize, especially if they are considering downsizing, relocating, or making a move out of state. Mark has watched this market for 20 years, and this cycle has created a rare window for sellers. I am not calling to pressure you to sell. I am calling to see if it would be helpful for Mark to prepare a quick, no-obligation market position review so you know what your options look like before conditions change.")?></pre></div></section></div>
</main></body></html>