<?php
session_start(); require_once __DIR__.'/../lead-engine/config.php'; require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/scorsese-studio-pro-v105.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($s,$p=[]){try{return gdb_all($s,$p)?:[];}catch(Throwable $e){return [];}}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$raw=rows("SELECT * FROM scorsese_raw_projects ORDER BY id DESC LIMIT 30");
$top=rows("SELECT * FROM executive_top10_boards WHERE executive_key='scorsese' ORDER BY rank_no ASC LIMIT 10");
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Scorsese Studio Pro V105</title><link rel="stylesheet" href="/dashboard/assets/goliath-carbon-v105.css"></head><body><div class="wrap">
<header class="top"><div><div class="logo">🎬 SCORSESE STUDIO PRO</div><div class="muted">Create new media · Repurpose existing video · Top 10 productions</div></div><div><a class="btn" href="/dashboard/mission-control-intake-v105.php">Mission Intake</a><a class="btn" href="/dashboard/goliath-organization-runtime.php">Runtime</a></div></header>
<section class="grid"><aside class="panel"><h2>Create New Media</h2><form method="post" action="/lead-engine/scorsese-comfy-direct-queue.php?key=<?=h($key)?>"><input name="title" placeholder="Video title"><textarea name="prompt" rows="7" placeholder="Prompt for Scorsese to create new video"></textarea><button class="gold">Queue New Video</button></form></aside>
<main class="panel"><h2>Repurpose Existing Content</h2><form method="post" enctype="multipart/form-data" action="/lead-engine/scorsese-raw-video-upload-v105.php"><input type="hidden" name="key" value="<?=h($key)?>"><input name="title" placeholder="Project title, e.g. Discover CT street interview"><select name="brand_style"><option>Discover Connecticut</option><option>Mark Pires Real Estate</option><option>House Detective</option><option>BeatSeat</option><option>LegacySaved</option><option>Speaking / Mark insPires</option></select><input type="file" name="raw_video" accept=".mp4,.mov,.m4v,.webm" required><textarea name="prompt" rows="6">Find the strongest hooks, viral moments, emotional beats, clean entry/exit points, shorts, reels, captions, titles, and thumbnails. Score the content and recommend the best 5 clips.</textarea><button class="gold">Upload Raw Video to Scorsese</button></form><hr><?php foreach($raw as $r): ?><div class="item"><b><?=h($r['title'])?></b><div class="muted"><?=h($r['brand_style'])?> · <?=h($r['status'])?> · <?=h($r['created_at'])?></div><a class="btn" href="<?=h($r['file_url'])?>" target="_blank">Open Source Video</a></div><?php endforeach; ?></main>
<aside class="panel"><h2>Scorsese Top 10</h2><?php foreach($top as $t): ?><div class="item"><b>#<?=h($t['rank_no'])?> <?=h($t['title'])?></b><div class="score"><?=h($t['score'])?></div><div class="muted"><?=h($t['reason'])?></div></div><?php endforeach; ?></aside></section>
</div></body></html>