<?php
session_start(); require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/scorsese-media-vault.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sbq($ep){$ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json'],CURLOPT_TIMEOUT=>25]);$b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$rows=sbq('scorsese_media_vault?select=*&order=created_at.desc&limit=120');
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Scorsese Media Vault</title>
<style>body{margin:0;background:#070b14;color:#eaf2ff;font-family:Inter,system-ui,Segoe UI,Arial}.wrap{max-width:1400px;margin:auto;padding:20px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.btn{display:inline-block;background:#101a2b;color:#eaf2ff;border:1px solid #263751;text-decoration:none;border-radius:12px;padding:10px 13px;font-weight:900}.gold{background:#f5c85d;color:#111827;border-color:#f5c85d}.panel{border:1px solid #263751;background:#0b1220;border-radius:18px;padding:16px;margin-top:16px}.upload{display:grid;grid-template-columns:1fr 1fr;gap:10px}.upload input,.upload textarea,.upload select{background:#050b16;color:#fff;border:1px solid #263751;border-radius:12px;padding:10px}.upload textarea{grid-column:1/-1;min-height:90px}.bar{height:14px;background:#162033;border-radius:999px;overflow:hidden;margin-top:12px}.fill{height:100%;width:0;background:linear-gradient(90deg,#ef4444,#f59e0b,#22c55e);transition:.2s}.status{font-size:13px;color:#cbd5e1;margin-top:8px}.table{width:100%;border-collapse:collapse;margin-top:14px}.table th,.table td{border-bottom:1px solid #1f2f46;padding:8px 8px;text-align:left;font-size:13px}.table th{color:#f5c85d;text-transform:uppercase;font-size:11px;letter-spacing:.08em}.actions a{margin-right:6px}.pill{border:1px solid #36506d;border-radius:999px;padding:4px 8px;color:#dce8ff;text-decoration:none;font-size:12px}.videoCell{max-width:360px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:800px){.top,.upload{display:block}.upload input,.upload textarea,.upload select{width:100%;margin:6px 0}}</style>
</head><body><div class="wrap"><div class="top"><div><h1>🎬 Scorsese Media Vault</h1><p style="color:#9fb0ca">Upload raw footage, store it safely, then commission Scorsese for multiple cuts.</p></div><div><a class="btn" href="/dashboard/goliath-agent-detail.php?department=Scorsese">Scorsese Office</a> <a class="btn" href="/dashboard/goliath-mission-control.php">Mission Control</a></div></div>
<div class="panel"><h2>Upload Raw Media</h2><form id="up" class="upload"><input name="project_name" placeholder="Project name e.g. Discover CT 7/1" required><select name="brand"><option value="mark_pires">Mark Pires</option><option value="discover_ct">Discover CT</option><option value="house_detective">House Detective</option><option value="beatseat">BeatSeat</option><option value="legacysaved">LegacySaved</option></select><input type="file" name="media" accept="video/*,image/*,audio/*" required><input name="priority" value="95" placeholder="Priority"><textarea name="director_notes" placeholder="Director notes: Create 3 shorts, find the strongest story, title/description ideas, no dead air..."></textarea><button class="btn gold" type="submit">Upload & Commission Scorsese</button></form><div class="bar"><div id="fill" class="fill"></div></div><div id="status" class="status">For very large files, use File Manager/SFTP into /public_html/data/scorsese_raw then add to vault later.</div></div>
<div class="panel"><h2>Raw Media Library</h2><table class="table"><thead><tr><th>Project</th><th>File</th><th>Kind</th><th>Size</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=h($r['project_name']??'')?></td><td class="videoCell"><?=h($r['original_filename']??$r['stored_filename']??'')?></td><td><?=h($r['kind']??'')?></td><td><?=number_format((float)($r['file_size_bytes']??0)/1048576,1)?> MB</td><td><?=h($r['status']??'stored')?></td><td><?=h(!empty($r['created_at'])?date('M j g:i A',strtotime($r['created_at'])):'')?></td><td class="actions"><?php if(!empty($r['file_url'])):?><a class="pill" target="_blank" href="<?=h($r['file_url'])?>">Open</a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div>
<script>
const KEY=<?=json_encode($key)?>, form=document.getElementById('up'), fill=document.getElementById('fill'), status=document.getElementById('status');
form.addEventListener('submit', e=>{e.preventDefault(); const fd=new FormData(form); fd.append('key',KEY); const xhr=new XMLHttpRequest(); xhr.open('POST','/lead-engine/scorsese-media-upload.php'); xhr.upload.onprogress=(ev)=>{ if(ev.lengthComputable){ const p=Math.round(ev.loaded/ev.total*100); fill.style.width=p+'%'; status.textContent='Uploading... '+p+'%'; }}; xhr.onload=()=>{ try{ const j=JSON.parse(xhr.responseText); if(j.success){fill.style.width='100%'; status.textContent='Stored and commissioned: '+j.file_url+' ('+j.file_size_mb+' MB)'; setTimeout(()=>location.reload(),1200);} else {status.textContent='Upload issue: '+(j.error||xhr.responseText);} }catch(err){status.textContent='Server response issue: '+xhr.responseText.slice(0,200);} }; xhr.onerror=()=>{status.textContent='Network disconnected during upload. Try smaller file or File Manager/SFTP.'}; xhr.send(fd);});
</script></body></html>
