<?php
session_start();require_once __DIR__ . '/../lead-engine/config.php';require_once __DIR__ . '/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/scorsese-media-center.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function st_table($t){try{$r=gdb_one("SELECT COUNT(*) c FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?",[$t]);return ((int)($r['c']??0))>0;}catch(Throwable $e){return false;}}
function st_all($sql,$p=[]){try{return gdb_all($sql,$p)?:[];}catch(Throwable $e){return [];}}
function st_json($v){if(is_array($v))return $v;if(is_string($v)){ $j=json_decode($v,true); return is_array($j)?$j:[];} return [];}
$items=st_table('goliath_worker_completions')?st_all("SELECT * FROM goliath_worker_completions WHERE LOWER(executive)='scorsese' ORDER BY created_at DESC,id DESC LIMIT 50"):[];
$review=st_table('goliath_review_queue')?st_all("SELECT * FROM goliath_review_queue WHERE LOWER(executive)='scorsese' ORDER BY created_at DESC,id DESC LIMIT 50"):[];
$commissions=st_table('executive_commissions')?st_all("SELECT * FROM executive_commissions WHERE executive_key='scorsese' ORDER BY updated_at DESC LIMIT 30"):[];
$id=$_GET['id']??'';$selected=null;if($id){foreach($items as $m){if((string)$m['id']===(string)$id){$selected=$m;break;}}}if(!$selected&&count($items))$selected=$items[0];
$output=$selected['output']??''; $parsed=st_json($selected['parsed']??null);
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Scorsese Media Center</title>
<link rel="stylesheet" href="/dashboard/assets/goliath-v33.css?v=33"><link rel="stylesheet" href="/dashboard/assets/goliath-v45-final.css?v=456"><link rel="stylesheet" href="/dashboard/assets/scorsese-media-center-v58-6.css?v=586"><style>.screenWork{padding:24px;min-height:520px;overflow:auto;white-space:pre-wrap;line-height:1.55;color:#e5e7eb}.workCard{display:block;color:#fff;text-decoration:none;padding:12px;border-radius:14px;border:1px solid rgba(255,255,255,.1);background:#020617;margin-bottom:10px}.workCard:hover,.workCard.active{border-color:#f5c85d;background:#111827}.workCard strong{display:block}.workCard small{color:#94a3b8}.newBadge{background:#22c55e;color:#03120a;border-radius:999px;padding:2px 8px;font-size:11px;font-weight:1000;margin-right:6px}.scmKpis a{color:#fff;text-decoration:none}</style></head><body><div class="shell"><?php @require __DIR__.'/includes/goliath-sidebar-v33.php'; ?><main class="main scm">
<section class="scmHero"><div><p class="eyebrow">Scorsese Production Department</p><h1>🎬 Scorsese Media Center</h1><p>One click to completed media work. Finished outputs, review-ready productions, and director notes appear here first.</p></div><div class="scmHeroBtns"><a class="btn" href="/dashboard/goliath-mission-control.php">Mission Control</a><a class="btn dark" href="/dashboard/goliath-worker-output.php">Worker Output</a></div></section>
<section class="scmKpis"><a href="#completed"><b><?=count($items)?></b><span>Completed Outputs</span></a><a href="#review"><b><?=count($review)?></b><span>Ready for Review</span></a><a href="#queue"><b><?=count($commissions)?></b><span>Total Commissions</span></a><a target="_blank" href="/lead-engine/local-ai-task-debug.php?key=<?=h($key)?>"><b>LIVE</b><span>Truth Check</span></a></section>
<section class="scmStageGrid"><section class="scmCinema"><div class="screen"><div class="screenWork"><?php if($selected): ?><h2><?=h($selected['title']??'Scorsese deliverable')?></h2><p style="color:#94a3b8"><?=h($selected['created_at']??'')?></p><?=h($output ?: json_encode($parsed,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?><?php else: ?><div class="screenEmpty">🎬<strong>No completed Scorsese media yet</strong><span>When the local worker completes Scorsese's commission, the finished output appears here.</span></div><?php endif;?></div></div>
<section class="promptPanel"><div class="scmCardHead"><div><p>Director Notes</p><h2>Send Scorsese a Revision or New Job</h2></div><span>One prompt creates the next commission</span></div><textarea id="videoPrompt" placeholder="Scorsese, create 3 shorts from this idea... revise this with a stronger hook... build a video from this blog..."></textarea><button class="commission" onclick="sendScorsesePrompt()">🎬 Send to Scorsese</button><div id="promptResult" class="result"></div></section></section>
<aside class="scmControlRail"><section class="scmQueue"><div class="scmCardHead"><div><p id="completed">Completed Work</p><h2>Latest Scorsese Outputs</h2></div><a class="btn" href="/dashboard/executive-office.php?exec=scorsese">Studio View</a></div><div class="queueList"><?php foreach($items as $i=>$p): ?><a class="workCard <?=($selected&&$selected['id']==$p['id'])?'active':''?>" href="/dashboard/scorsese-media-center.php?id=<?=h($p['id'])?>"><?php if($i<3):?><span class="newBadge">NEW</span><?php endif;?><strong><?=h($p['title']??'Scorsese Production')?></strong><small><?=h($p['created_at']??'')?> · completion #<?=h($p['id']??'')?></small></a><?php endforeach;?><?php if(!count($items)):?><div class="empty">No completed Scorsese outputs yet.</div><?php endif;?></div></section>
<section class="scmQueue"><div class="scmCardHead"><div><p id="queue">Commission Queue</p><h2>Recent Status</h2></div></div><div class="queueList"><?php foreach($commissions as $p): ?><div class="workCard"><strong><?=h($p['title']??'Commission')?></strong><small><?=h($p['status']??'')?> · <?=h($p['progress']??0)?>% · <?=h($p['updated_at']??'')?></small></div><?php endforeach;?></div></section></aside></section>
<script>async function sendScorsesePrompt(){const txt=document.getElementById('videoPrompt').value.trim(); if(!txt){alert('Add director notes first.');return;} document.getElementById('promptResult').textContent='Sending...'; try{const r=await fetch('/lead-engine/goliath-agent-command.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:<?=json_encode($key)?>,agent:'Scorsese',command:txt,source:'scorsese_media_center',completion_id:'<?=h($selected['id']??'')?>'})}); const j=await r.json(); document.getElementById('promptResult').textContent=j.success?'Queued for Scorsese.':(j.error||'Queued/fallback.');}catch(e){document.getElementById('promptResult').textContent='Queued/fallback.';}}</script></main></div></body></html>
