<?php
declare(strict_types=1);session_start();require_once __DIR__.'/../lead-engine/config.php';require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
$id=(int)($_GET['project_id']??0);$project=$id?gdb_one("SELECT * FROM scorsese_director_projects WHERE id=? LIMIT 1",[$id]):[];
$projects=gdb_all("SELECT * FROM scorsese_director_projects ORDER BY id DESC LIMIT 30")?:[];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Scorsese Director Workstation</title>
<style>*{box-sizing:border-box}body{margin:0;background:#05060a;color:#fff;font-family:Arial}.shell{display:grid;grid-template-columns:260px 1fr;min-height:100vh}.rail{background:#0a0d14;border-right:1px solid #4b1b1b;padding:12px}.rail h1{color:#ff5252}.project{display:block;color:#fff;text-decoration:none;padding:10px;border:1px solid #34202a;border-radius:9px;margin:7px 0}.project.active{background:#311018;border-color:#ff5252}.main{padding:16px}.hero{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.hero h2{font-size:30px;margin:0;color:#ff6666}.status{background:#181c25;border:1px solid #444;padding:10px;border-radius:10px}.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:12px;margin-top:14px}.panel{background:#0c111b;border:1px solid #343d4e;border-radius:14px;overflow:hidden}.panel h3{margin:0;padding:11px;background:#121a28;color:#ffb0b0}.body{padding:12px}.monitor{aspect-ratio:16/9;background:#000;border-radius:10px;display:grid;place-items:center;color:#777}.fields{display:grid;gap:8px}.fields input,.fields textarea,.fields select{width:100%;padding:10px;background:#070b12;border:1px solid #3b465a;color:#fff;border-radius:8px}.btn{background:#a21d2d;color:#fff;border:0;padding:10px 14px;border-radius:9px;font-weight:900;cursor:pointer}.tabs{display:flex;gap:7px;flex-wrap:wrap}.tab{background:#202838;padding:8px 10px;border-radius:8px}.empty{color:#8996aa;padding:12px}@media(max-width:760px){.shell{grid-template-columns:1fr}.rail{max-height:220px;overflow:auto}.grid{grid-template-columns:1fr}.hero{display:block}}</style></head><body><div class="shell"><aside class="rail"><h1>SCORSESE</h1><a class="project" href="/dashboard/scorsese-director-workstation-v118-3.php">+ New Project</a><?php foreach($projects as $p):?><a class="project <?=$id===(int)$p['id']?'active':''?>" href="?project_id=<?=(int)$p['id']?>"><b><?=htmlspecialchars($p['title'])?></b><br><small><?=htmlspecialchars($p['production_mode'])?> · <?=htmlspecialchars($p['status'])?></small></a><?php endforeach;?></aside><main class="main">
<?php if(!$project):?><div class="hero"><div><h2>Ultimate AI Director</h2><p>Automatic Director or Human Director. Ingest long-form footage, align it to a script, choose takes, preserve director notes and render an editable review cut.</p></div></div><div class="panel"><h3>Create Director Project</h3><div class="body"><form id="create" class="fields"><input name="title" placeholder="Project title" required><select name="production_mode"><option value="automatic_director">Automatic Director</option><option value="human_director">Human Director</option></select><select name="production_type"><option>episode</option><option>documentary</option><option>interview</option><option>music_video</option><option>legacy_film</option></select><textarea name="source_goal" placeholder="Goal and audience"></textarea><textarea name="supplied_script" placeholder="Optional script"></textarea><button class="btn">Create Project</button></form></div></div><script>document.getElementById('create').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));const r=await fetch('/lead-engine/scorsese-director-create-v118-3.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(o)});const d=await r.json();if(d.ok)location=d.url;else alert(d.error)}</script>
<?php else:?><div class="hero"><div><h2><?=htmlspecialchars($project['title'])?></h2><p><?=htmlspecialchars($project['production_type'])?> · <?=htmlspecialchars($project['production_mode'])?></p></div><div class="status"><b><?=htmlspecialchars($project['status'])?></b><br><?=htmlspecialchars($project['current_phase']??'')?> · <?=(int)$project['progress']?>%</div></div>
<div class="tabs"><span class="tab">Sources</span><span class="tab">Transcript</span><span class="tab">Scenes</span><span class="tab">Takes</span><span class="tab">Director Notes</span><span class="tab">EDL Timeline</span><span class="tab">Renders</span></div>
<div class="grid"><section class="panel"><h3>Program Monitor</h3><div class="body"><div class="monitor">Review cut appears here</div></div></section><section class="panel"><h3>Director Notes</h3><div class="body"><textarea style="width:100%;height:180px;background:#070b12;color:#fff;border:1px solid #3b465a;border-radius:8px" placeholder="Use Take C until 00:17, cut to Take B for the reaction, then return to Take C."></textarea><button class="btn" disabled>Save Note — processing API next</button></div></section></div>
<div class="grid"><section class="panel"><h3>Script / Story</h3><div class="body"><pre style="white-space:pre-wrap"><?=htmlspecialchars($project['supplied_script']?:'No supplied script yet. WhisperX and Story Architect will build or align one after ingest.')?></pre></div></section><section class="panel"><h3>Pipeline</h3><div class="body">Ingest → WhisperX → scene detection → take scoring → script alignment → EDL → review cut → director revision → final render → shorts/social.</div></section></div><?php endif;?></main></div></body></html>