<?php
session_start(); require_once __DIR__.'/../lead-engine/config.php'; require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/scout-mls-intelligence-v105.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($s,$p=[]){try{return gdb_all($s,$p)?:[];}catch(Throwable $e){return [];}}
function one($s,$p=[]){try{return gdb_one($s,$p)?:[];}catch(Throwable $e){return [];}}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$counts=rows("SELECT listing_type,COUNT(*) c FROM mls_property_events GROUP BY listing_type ORDER BY listing_type");
$opps=rows("SELECT * FROM mls_scout_opportunities WHERE status='open' ORDER BY opportunity_score DESC,town,property_address LIMIT 300");
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Scout MLS Intelligence</title><link rel="stylesheet" href="/dashboard/assets/goliath-carbon-v105.css"></head><body><div class="wrap">
<header class="top"><div><div class="logo">🕵️ SCOUT MLS INTELLIGENCE</div><div class="muted">Active · Closed · Expired · Withdrawn · Canceled cross-checking</div></div><div><a class="btn" href="/dashboard/mission-control-intake-v105.php">Mission Intake</a> <a class="btn gold" target="_blank" href="/lead-engine/scout-mls-reconcile-v105.php?key=<?=h($key)?>">Reconcile Now</a></div></header>
<section class="two"><main class="panel"><h2>Upload MLS Datasets</h2><form method="post" enctype="multipart/form-data" action="/lead-engine/scout-mls-upload-v105.php"><input type="hidden" name="key" value="<?=h($key)?>"><select name="listing_type"><option value="active">Active Listings</option><option value="closed">Closed/Sold Listings</option><option value="expired">Expired Listings</option><option value="withdrawn">Withdrawn Listings</option><option value="canceled">Canceled Listings</option></select><input type="file" name="csv_file" accept=".csv,.txt" required><button class="gold">Upload to Scout</button></form><p class="muted">Rule: keep only expired/withdrawn/canceled properties that do not match closed/sold and are not currently active.</p></main><aside class="panel"><h2>Dataset Counts</h2><?php foreach($counts as $c): ?><div class="item"><b><?=h(ucfirst($c['listing_type']))?></b><span class="score"> <?=h($c['c'])?></span></div><?php endforeach; ?></aside></section>
<section class="panel" style="margin-top:14px"><h2>Real Opportunities: Never Sold / Not Active</h2><table class="compact"><tr><th>Score</th><th>Address</th><th>Town</th><th>Status</th><th>Reason</th></tr><?php foreach($opps as $o): ?><tr><td class="score"><?=h($o['opportunity_score'])?></td><td><?=h($o['property_address'])?></td><td><?=h($o['town'])?></td><td><?=h($o['last_status'])?></td><td><?=h($o['reason'])?></td></tr><?php endforeach; ?></table></section>
</div></body></html>