<?php
session_start();
require_once __DIR__.'/../lead-engine/config.php';
require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/scout-contact-workspace.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($sql,$p=[]){try{return gdb_all($sql,$p)?:[];}catch(Throwable $e){return [];}}
$batch=(int)($_GET['batch_id']??0);
$where=$batch?'WHERE id IN (SELECT CAST(j.contact_id AS UNSIGNED) FROM scout_research_batches b JOIN JSON_TABLE(b.metadata, "$.contact_ids[*]" COLUMNS(contact_id INT PATH "$")) j WHERE b.id=?)':'';
$contacts=$batch?rows("SELECT * FROM internal_crm_contacts WHERE id IN (SELECT jt.cid FROM scout_research_batches b, JSON_TABLE(b.metadata, '$.contact_ids[*]' COLUMNS(cid INT PATH '$')) jt WHERE b.id=?) ORDER BY id ASC",[$batch]):rows("SELECT * FROM internal_crm_contacts ORDER BY updated_at DESC LIMIT 300");
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Scout Contact Workspace</title><link rel="stylesheet" href="/dashboard/assets/goliath-v33.css?v=33"><link rel="stylesheet" href="/dashboard/assets/goliath-v45-final.css?v=456"><style>
body{background:#030712;color:#fff}.tableWrap{overflow:auto;background:#07111f;border:1px solid rgba(255,255,255,.12);border-radius:18px}table{width:100%;border-collapse:collapse;min-width:1100px}th,td{padding:9px;border-bottom:1px solid rgba(255,255,255,.1);text-align:left;font-size:13px}th{color:#d4af37;background:#0f172a;position:sticky;top:0}.badge{border-radius:999px;padding:4px 8px;font-weight:900;font-size:11px;background:#334155;color:#cbd5e1}.ok{background:#14532d;color:#dcfce7}.warn{background:#451a03;color:#fed7aa}</style></head><body><div class="shell"><?php @require __DIR__.'/includes/goliath-sidebar-v33.php'; ?><main class="main"><section class="top"><div><h1>Scout Contact Workspace</h1><p>Internal CRM only. /data imports, expired/never-sold homeowners, phone/email enrichment, evidence, and compliance review.</p></div><div class="brandbar"><a class="btn dark" href="/dashboard/goliath-workbench.php">Workbench</a><a class="btn" target="_blank" href="/lead-engine/run-scout-data-cycle.php?key=<?=h(defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts')?>">Run Scout Cycle</a></div></section><section class="panel"><h2>Contacts <span><?=count($contacts)?> shown</span></h2><div class="inner tableWrap"><table><thead><tr><th>ID</th><th>Owner</th><th>Property</th><th>Town</th><th>Phone</th><th>Email</th><th>Status</th><th>Compliance</th><th>Evidence</th><th>Source</th></tr></thead><tbody><?php foreach($contacts as $c): ?><tr><td><?=h($c['id'])?></td><td><?=h($c['owner_name'])?></td><td><?=h($c['property_address'])?></td><td><?=h($c['town'])?></td><td><?=h($c['phone_1'])?></td><td><?=h($c['email_1'])?></td><td><span class="badge <?=($c['research_status']==='complete'?'ok':'warn')?>"><?=h($c['research_status'])?></span></td><td><?=h($c['compliance_status'])?></td><td><?=h(mb_substr($c['evidence']??'',0,90))?></td><td><?=h($c['source_file'])?> row <?=h($c['source_row'])?></td></tr><?php endforeach;?></tbody></table></div></section></main></div></body></html>