<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function money($n){return '$'.number_format((float)$n,0);}
function sb145d($m,$ep,$p=null){
  $ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$m,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json','Prefer: return=representation'],CURLOPT_TIMEOUT=>25]);
  if($p!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($p));
  $b=curl_exec($ch);curl_close($ch);$d=json_decode($b,true);return is_array($d)?$d:[];
}
$msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $id=$_POST['id']??''; $stage=$_POST['stage']??'';
  if($id && in_array($stage,['call','enrich','nurture','review','ignore','archived'],true)){
    sb145d('PATCH','seller_acquisition_director?id=eq.'.rawurlencode($id),['acquisition_stage'=>$stage,'status'=>$stage==='archived'?'archived':'active','updated_at'=>date('c')]);
    $msg='Acquisition item updated.';
  }
}
$rows=sb145d('GET','seller_acquisition_director?select=*&status=eq.active&order=mark_priority.desc,acquisition_score.desc,created_at.desc&limit=400');
$briefs=sb145d('GET','seller_acquisition_briefings?select=*&order=created_at.desc&limit=5');
$brief=$briefs[0]??[];
$stats=['total'=>count($rows),'ready'=>0,'enrich'=>0,'review'=>0,'mark'=>0,'luxury'=>0,'commission'=>0];
foreach($rows as $r){if(!empty($r['ready_to_contact']))$stats['ready']++;if(!empty($r['needs_enrichment']))$stats['enrich']++;if(!empty($r['needs_review']))$stats['review']++;if(!empty($r['mark_priority']))$stats['mark']++;if((int)($r['luxury_score']??0)>=90)$stats['luxury']++;$stats['commission']+=(float)($r['estimated_commission']??0);}
$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>V14.5 Seller Acquisition Director</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:linear-gradient(135deg,#10101a,#1a1a2e);color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:38px}.wrap{max-width:1800px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(7,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:26px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}.btn{border:0;display:inline-block;background:#c8a96e;color:#111;text-decoration:none;padding:9px 11px;border-radius:9px;font-weight:900;font-size:12px;margin:2px;cursor:pointer}.light{background:#f2efe8;color:#111}.layout{display:grid;grid-template-columns:1fr .34fr;gap:18px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:11px;border-bottom:1px solid #eee;font-size:14px;vertical-align:top}th{font-size:11px;text-transform:uppercase;color:#777;background:#faf9f6}.muted{color:#777;font-size:13px}pre{white-space:pre-wrap;background:#111;color:#fff;padding:16px;border-radius:12px}.score{font-size:28px;font-weight:900;color:#c8a96e}.mark{background:#111;color:#fff;border-radius:999px;padding:3px 7px;font-size:11px}@media(max-width:1000px){.grid,.layout{grid-template-columns:1fr}.wrap{padding:14px}}</style></head><body><div class="header"><div class="brand">V14.5 Seller Acquisition Director</div><div>Unified seller board: FSBO, expired, withdrawn, valuation, voice, listing intelligence, enrichment, and pipeline priority</div></div><main class="wrap"><?php if($msg):?><div class="panel" style="padding:16px"><?=h($msg)?></div><?php endif;?>
<p><a class="btn" target="_blank" href="/lead-engine/build-seller-acquisition-director.php?key=<?=h($cronKey)?>">Build Seller Director</a><a class="btn light" href="/dashboard/seller-opportunity-engine.php">Seller Engine</a><a class="btn light" href="/dashboard/contact-enrichment-center.php">Enrichment</a><a class="btn light" href="/dashboard/realtor-exclusion-center.php">Realtor Filter</a><a class="btn light" href="/dashboard/opportunity-pipeline.php">Pipeline</a></p>
<section class="grid"><div class="kpi"><div class="n"><?=h($stats['total'])?></div>Total</div><div class="kpi"><div class="n"><?=h($stats['ready'])?></div>Ready</div><div class="kpi"><div class="n"><?=h($stats['enrich'])?></div>Enrich</div><div class="kpi"><div class="n"><?=h($stats['review'])?></div>Review</div><div class="kpi"><div class="n"><?=h($stats['mark'])?></div>Mark</div><div class="kpi"><div class="n"><?=h($stats['luxury'])?></div>Luxury</div><div class="kpi"><div class="n"><?=money($stats['commission'])?></div>2.5%</div></section>
<div class="layout"><section class="panel"><h2>Top Seller Opportunities</h2><table><tr><th>Score</th><th>Opportunity</th><th>Source</th><th>Value</th><th>Action</th></tr><?php foreach($rows as $r):?><tr><td><div class="score"><?=h($r['acquisition_score'])?></div><div class="muted"><?=h($r['acquisition_stage'])?></div></td><td><strong><?=h($r['address']?:$r['name'])?></strong> <?php if(!empty($r['mark_priority'])):?><span class="mark">MARK</span><?php endif;?><div class="muted"><?=h($r['town'])?><br><?=h($r['phone'])?> <?=h($r['email'])?></div></td><td><?=h($r['source_type'])?><div class="muted">DNC: <?=h($r['dnc_status'])?><br>Realtor: <?=h($r['realtor_status'])?></div></td><td><?=money($r['estimated_sale_price'])?><div class="muted">Commission <?=money($r['estimated_commission'])?><br>Expected <?=money($r['expected_value'])?></div></td><td><?=h($r['recommended_action'])?><div class="muted"><?=h($r['recommended_script'])?></div><form method="post"><input type="hidden" name="id" value="<?=h($r['id'])?>"><button class="btn" name="stage" value="call">Call</button><button class="btn light" name="stage" value="enrich">Enrich</button><button class="btn light" name="stage" value="review">Review</button><button class="btn light" name="stage" value="nurture">Nurture</button><button class="btn light" name="stage" value="archived">Archive</button></form></td></tr><?php endforeach;?></table></section><section class="panel"><h2>Jessica Acquisition Brief</h2><div style="padding:16px"><pre><?=h($brief['briefing_text']??'Build Seller Director to create briefing.')?></pre></div></section></div>
</main></body></html>