<?php
session_start();
require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/shakespeare-site-health.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$canonical='https://www.markpires.com/';
$gone=['/_api/v2/dynamicmodel','/user-videos/','/video-tag/','/video-category/','/search-videos/','/buddyforms-submissions-page/','/buddyforms-preview-page/','/player-embed/','/register/','/es/product-page/*','/hi/product-page/*','/wp-login.php','/wp-admin/*'];
$redirects=['/services/'=>'/#services','/oggi-gelato-grand-opening-party/'=>'/blog/'];
$files=['/.htaccess'=>file_exists(__DIR__.'/../.htaccess'),'/robots.txt'=>file_exists(__DIR__.'/../robots.txt'),'/sitemap.xml'=>file_exists(__DIR__.'/../sitemap.xml'),'/about/index.html'=>file_exists(__DIR__.'/../about/index.html')];
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Shakespeare Site Health</title><style>
body{margin:0;background:#f8f5ef;color:#111827;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}.wrap{max-width:1200px;margin:auto;padding:28px}.hero{background:linear-gradient(135deg,#0B1C36,#111827);color:#fff;padding:32px;border-radius:24px;margin-bottom:18px}.hero h1{font-family:Georgia,serif;font-size:42px;margin:0 0 8px;color:#fff}.hero p{color:#d9d2bd}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card,.panel{background:#fff;border:1px solid #eadfca;border-radius:18px;padding:18px;box-shadow:0 12px 32px #0b1c3610}.n{font-size:28px;font-weight:900;color:#0B1C36}.label{font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:#667085;font-weight:800}.panel{margin-top:16px}table{width:100%;border-collapse:collapse}td,th{padding:12px;border-bottom:1px solid #eee;text-align:left}th{font-size:12px;text-transform:uppercase;color:#667085}.ok{color:#16803a;font-weight:900}.bad{color:#b42318;font-weight:900}.btn{display:inline-block;background:#C9A227;color:#0B1C36;padding:10px 14px;border-radius:999px;text-decoration:none;font-weight:900;font-size:12px;text-transform:uppercase;letter-spacing:.08em}@media(max-width:900px){.grid{grid-template-columns:1fr}.wrap{padding:14px}}
</style></head><body><main class="wrap"><section class="hero"><div class="label" style="color:#C9A227">Shakespeare · Site Health Department</div><h1>Google Cleanup Command Center</h1><p>Legacy URL cleanup, canonical hygiene, sitemap quality, and ongoing SEO/AEO maintenance.</p><p><a class="btn" href="/lead-engine/goliath-seo-cleanup-health.php?key=<?=h(defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts')?>" target="_blank">Run Health Check</a> <a class="btn" href="/about/" target="_blank">Open About Page</a></p></section><section class="grid"><div class="card"><div class="n"><?=count($gone)?></div><div class="label">Legacy Gone Rules</div></div><div class="card"><div class="n"><?=count($redirects)?></div><div class="label">301 Redirects</div></div><div class="card"><div class="n"><?=count(array_filter($files))?> / <?=count($files)?></div><div class="label">Cleanup Files Installed</div></div><div class="card"><div class="n">WWW</div><div class="label">Canonical Host</div></div></section><section class="panel"><h2>Install Verification</h2><table><tr><th>File</th><th>Status</th></tr><?php foreach($files as $f=>$ok):?><tr><td><?=h($f)?></td><td class="<?=$ok?'ok':'bad'?>"><?=$ok?'Installed':'Missing'?></td></tr><?php endforeach;?></table></section><section class="panel"><h2>Legacy URL Rules</h2><table><tr><th>Legacy URL</th><th>Action</th></tr><?php foreach($gone as $u):?><tr><td><code><?=h($u)?></code></td><td>410 Gone</td></tr><?php endforeach;?><?php foreach($redirects as $from=>$to):?><tr><td><code><?=h($from)?></code></td><td>301 → <code><?=h($to)?></code></td></tr><?php endforeach;?></table></section><section class="panel"><h2>Shakespeare Permanent Site Health Playbook</h2><p>Every week, Shakespeare should review Google Search Console, reduce 404s, strengthen internal links, refresh thin content, request Scorsese images for blogs, verify canonical rules, update sitemap, and submit the highest-value fixes to Goliath for approval.</p></section></main></body></html>
