<?php
session_start();
require_once __DIR__.'/../lead-engine/config.php';
require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/shakespeare-workspace.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($sql,$p=[]){try{return gdb_all($sql,$p)?:[];}catch(Throwable $e){return [];}}
$blogs=rows("SELECT * FROM goliath_deliverables WHERE executive_key='shakespeare' OR deliverable_type IN ('publish_ready_blog','blog_article','landing_page') ORDER BY created_at DESC, id DESC LIMIT 100");
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Shakespeare Workspace</title><link rel="stylesheet" href="/dashboard/assets/goliath-v33.css?v=33"><link rel="stylesheet" href="/dashboard/assets/goliath-v45-final.css?v=456"><style>
body{background:#030712;color:#fff}.hero{background:linear-gradient(135deg,#3b0a0a,#0f172a);border:1px solid #7f1d1d;border-radius:22px;padding:20px;margin-bottom:14px}.grid{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:14px}.card,.prompt{background:#07111f;border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:14px}.blog{display:block;color:#fff;text-decoration:none;border-bottom:1px solid rgba(255,255,255,.12);padding:12px 0}.blog h3{color:#f5d48b;margin:0}.meta{color:#94a3b8;font-size:12px}textarea{width:100%;min-height:170px;background:#020617;color:#fff;border:1px solid #ffffff22;border-radius:14px;padding:12px}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}@media(max-width:900px){.grid{grid-template-columns:1fr}}</style></head><body><div class="shell"><?php @require __DIR__.'/includes/goliath-sidebar-v33.php'; ?><main class="main"><section class="hero"><h1>✒️ Shakespeare Workspace</h1><p>Publish-ready blogs, landing pages, local authority content, and conversion copy. Use the prompt window to request exact improvements.</p><div class="actions"><a class="btn dark" href="/dashboard/goliath-workbench.php">Workbench</a><a class="btn" href="/dashboard/goliath-deliverables.php?exec=shakespeare">All Shakespeare Deliverables</a></div></section>
<section class="grid"><main class="card"><h2>New Blog / Page Assets</h2><?php foreach($blogs as $b): ?><a class="blog" href="/dashboard/goliath-deliverables.php?deliverable_id=<?=h($b['id'])?>"><h3><?=h($b['title'])?></h3><p><?=h(mb_substr(strip_tags($b['output_summary']??''),0,260))?></p><div class="meta">#<?=h($b['id'])?> · <?=h($b['deliverable_type'])?> · <?=h($b['created_at'])?></div></a><?php endforeach; ?><?php if(!count($blogs)):?><p>No Shakespeare blog/page assets yet.</p><?php endif;?></main>
<aside class="prompt"><h2>Prompt Shakespeare</h2><p class="meta">Use this for blog revisions, town pages, CT market reports, valuation funnel copy, or requests for Scorsese imagery.</p><textarea id="cmd" placeholder="Example: Shakespeare, create a publish-ready Westport luxury seller blog using the blog template, include FAQ schema, CTA to the valuation funnel, and ask Scorsese for a hero image and Discover CT town visual."></textarea><div class="actions"><button class="btn" onclick="send()">Send to Shakespeare</button><button class="btn dark" onclick="market()">Weekly Market Report Prompt</button></div><p id="status" class="meta"></p></aside></section></main></div>
<script>
const key=<?=json_encode($key)?>;
function market(){document.getElementById('cmd').value='Shakespeare, prepare the weekly Fairfield County town-by-town market report package. Use uploaded MLS data if available. If MLS data is missing, return NEEDS_MLS_EXPORT. Output must include publish-ready blog HTML, FAQ schema, CTA to valuation funnel, and Scorsese image/video requests for Ken Burns market report visuals.';}
async function send(){const prompt=document.getElementById('cmd').value.trim(); if(!prompt){alert('Add a prompt.');return;} document.getElementById('status').textContent='Queuing...'; const body=new URLSearchParams({key,prompt}); try{await fetch('/lead-engine/goliath-executive-prompt.php',{method:'POST',body}); document.getElementById('status').textContent='Queued for Shakespeare.';}catch(e){document.getElementById('status').textContent='Could not queue.';}}
</script></body></html>