<?php
session_start(); require_once __DIR__.'/../lead-engine/config.php'; require_once __DIR__.'/../lead-engine/goliath-db.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/?next='.rawurlencode($_SERVER['REQUEST_URI']??'/dashboard/shakespeare-authority-architect.php'));exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function rows($s,$p=[]){try{return gdb_all($s,$p)?:[];}catch(Throwable $e){return [];}}
function one($s,$p=[]){try{return gdb_one($s,$p)?:[];}catch(Throwable $e){return [];}}
$key=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'timetomakethedonuts';
$packages=rows("SELECT id,title,slug,audience,scenario,town,status,authority_score,article_summary,updated_at FROM shakespeare_campaign_packages ORDER BY authority_score DESC,id DESC LIMIT 60");
$clusters=rows("SELECT * FROM shakespeare_authority_clusters ORDER BY town ASC LIMIT 50");
$pkgId=(int)($_GET['package']??($packages[0]['id']??0));
$pkg=$pkgId?one("SELECT * FROM shakespeare_campaign_packages WHERE id=?",[$pkgId]):null;
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Shakespeare Authority Architect</title>
<style>
body{margin:0;background:#07060d;color:#fff;font-family:Arial}.wrap{max-width:1500px;margin:auto;padding:14px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.logo{font-weight:1000;color:#f6d679;letter-spacing:.12em}.btn{display:inline-flex;text-decoration:none;color:#fff;background:#111827;border:1px solid #ffffff22;border-radius:12px;padding:10px 12px;font-weight:900;font-size:12px}.gold{background:linear-gradient(135deg,#f6d679,#8a650f);color:#111}.grid{display:grid;grid-template-columns:340px 1fr 340px;gap:14px;margin-top:14px}.panel{background:#0b1120;border:1px solid #243b60;border-radius:20px;padding:14px;box-shadow:0 18px 45px #0008}.panel h2{margin:0 0 10px;color:#f6d679}.list{display:grid;gap:8px;max-height:78vh;overflow:auto}.item{background:#050914;border:1px solid #ffffff18;border-radius:14px;padding:10px}.item a{color:#fff;text-decoration:none;font-weight:900}.muted{color:#94a3b8;font-size:12px}.score{font-weight:1000;color:#80ffbd}.viewer{background:#fff;color:#111;border-radius:14px;padding:18px;line-height:1.5;max-height:70vh;overflow:auto}.chips{display:flex;flex-wrap:wrap;gap:8px}.chip{border:1px solid #ffffff22;background:#050914;border-radius:999px;padding:7px 9px;font-size:12px}.json{white-space:pre-wrap;background:#050914;border:1px solid #ffffff18;border-radius:12px;padding:10px;color:#dbeafe;font-size:12px;max-height:210px;overflow:auto}@media(max-width:1050px){.grid{grid-template-columns:1fr}.top{flex-direction:column;align-items:flex-start}.list{max-height:none}}
</style></head><body><div class="wrap">
<header class="top"><div><div class="logo">✒️ SHAKESPEARE AUTHORITY ARCHITECT</div><div class="muted">Campaign packages · authority clusters · visual requests · executive handoffs</div></div><div><a class="btn" href="/dashboard/goliath-organization-core.php">Org Core</a> <a class="btn" href="/dashboard/goliath-mission-control.php">Mission Control</a> <a class="btn gold" target="_blank" href="/lead-engine/shakespeare-authority-architect-v102.php?key=<?=h($key)?>&limit=12">Build Packages</a></div></header>
<section class="grid">
<aside class="panel"><h2>Packages</h2><div class="list"><?php foreach($packages as $p): ?><div class="item"><a href="?package=<?=h($p['id'])?>"><?=h($p['title'])?></a><div class="muted"><?=h($p['scenario'])?> <?=h($p['town']?'· '.$p['town']:'')?> · <span class="score"><?=h($p['authority_score'])?></span></div><div class="muted"><?=h($p['status'])?></div></div><?php endforeach; ?></div></aside>
<main class="panel"><h2><?=h($pkg['title']??'No Package Yet')?></h2><?php if($pkg): ?><div class="chips"><span class="chip">Score <?=h($pkg['authority_score'])?></span><span class="chip"><?=h($pkg['status'])?></span><span class="chip"><?=h($pkg['audience'])?></span></div><br><div class="viewer"><?=$pkg['article_html']?></div><?php endif; ?></main>
<aside class="panel"><h2>Executive Handoffs</h2><?php if($pkg): ?><div class="muted">Scorsese Video Brief</div><div class="json"><?=h(json_encode(json_decode($pkg['video_brief_json']??'[]',true),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></div><div class="muted">Visual Requests</div><div class="json"><?=h(json_encode(json_decode($pkg['visual_requests_json']??'[]',true),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></div><div class="muted">Next Opportunities</div><div class="json"><?=h(json_encode(json_decode($pkg['next_opportunities_json']??'[]',true),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></div><?php endif; ?></aside>
</section>
<section class="panel" style="margin-top:14px"><h2>Authority Clusters</h2><div class="chips"><?php foreach($clusters as $c): ?><span class="chip"><?=h($c['town']?:$c['cluster_name'])?> · Score <?=h($c['authority_score'])?></span><?php endforeach; ?></div></section>
</div></body></html>