<?php
session_start(); require_once __DIR__ . '/../lead-engine/config.php';
if(empty($_SESSION['mp_dashboard_auth'])){header('Location:/dashboard/');exit;}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function okc($n){return defined($n)&&constant($n)!==''&&!str_contains((string)constant($n),'PUT_')&&!str_contains((string)constant($n),'YOUR_');}
function mask($v){$v=(string)$v;return strlen($v)>8?substr($v,0,4).'...'.substr($v,-4):'set';}
function fileok($p){return file_exists($_SERVER['DOCUMENT_ROOT'].$p);}
function tableok($t){$ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.$t.'?select=id&limit=1');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPGET=>true,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY],CURLOPT_TIMEOUT=>8]);curl_exec($ch);$http=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);return $http>=200&&$http<300;}
$checks=['MARK_EMAIL','MARK_DASHBOARD_PASSWORD','RESEND_API_KEY','RESEND_FROM_EMAIL','SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','RETELL_API_KEY','RETELL_AGENT_ID_MARK_PRIORITY','RETELL_FROM_NUMBER','TWILIO_ACCOUNT_SID','TWILIO_AUTH_TOKEN','TWILIO_SMS_FROM','AFTER_HOURS_CRON_KEY'];
$files=['/lead-engine/capture.php','/lead-engine/cron-master.php','/lead-engine/seed-followups.php','/lead-engine/dnc-check.php','/lead-engine/track.php','/lead-engine/conversion-tracker.js','/lead-engine/process-call-outcomes.php','/lead-engine/build-future-sellers.php','/lead-engine/intelligence/import-homeowners-v3.php','/dashboard/operations.php','/dashboard/system-health.php','/dashboard/listing-forecast.php','/dashboard/future-seller-pipeline.php','/dashboard/call-learning.php','/dashboard/homeowner-radar.php','/dashboard/jessica-batch-caller.php','/dashboard/conversions.php','/dashboard/source-roi.php','/dashboard/utm-builder.php','/dashboard/drip-control.php'];
$tables=['leads','homeowner_intelligence','call_intelligence','lead_followup_queue','drip_sequence_templates','mark_action_queue','hot_lead_alerts','conversion_events','cold_call_outcomes','future_seller_pipeline'];
$okChecks=count(array_filter($checks,'okc'));$okFiles=count(array_filter($files,'fileok'));$okTables=0;foreach($tables as $t)if(tableok($t))$okTables++;$cronKey=defined('AFTER_HOURS_CRON_KEY')?AFTER_HOURS_CRON_KEY:'YOUR_KEY';
?>
<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>System Health</title><style>
body{margin:0;background:#f5f3ef;color:#10101a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.header{background:#10101a;color:#fff;padding:30px}.brand{font-family:Georgia,serif;color:#c8a96e;font-size:34px}.wrap{max-width:1400px;margin:auto;padding:26px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.kpi,.panel{background:#fff;border-radius:16px;box-shadow:0 2px 12px #0001}.kpi{padding:18px}.n{font-size:32px;font-weight:900}.panel{margin-top:18px;overflow:hidden}.panel h2{font-family:Georgia,serif;margin:0;padding:18px;border-bottom:1px solid #eee}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:11px;border-bottom:1px solid #eee}.ok{background:#e6f7ec;color:#14783c}.bad{background:#ffeaea;color:#9b1c1c}.badge{border-radius:999px;padding:5px 8px;font-size:11px}.btn{display:inline-block;background:#10101a;color:#fff;text-decoration:none;padding:9px 11px;border-radius:9px;margin:4px}.gold{background:#c8a96e;color:#111}@media(max-width:900px){.grid{grid-template-columns:1fr}.wrap{padding:14px}}
</style></head><body><div class="header"><div class="brand">System Health</div><div>Full machine checker restored with V6 modules · <a style="color:#c8a96e" href="/dashboard/operations.php">Operations</a></div></div><main class="wrap">
<section class="grid"><div class="kpi"><div class="n"><?=h($okChecks)?> / <?=h(count($checks))?></div>Config</div><div class="kpi"><div class="n"><?=h($okFiles)?> / <?=h(count($files))?></div>Files</div><div class="kpi"><div class="n"><?=h($okTables)?> / <?=h(count($tables))?></div>Tables</div></section>
<section class="panel"><h2>Quick Tests</h2><div style="padding:16px"><a class="btn gold" href="/dashboard/listing-forecast.php">Listing Forecast</a><a class="btn" href="/lead-engine/cron-master.php?key=<?=h($cronKey)?>" target="_blank">Run Cron</a><a class="btn" href="/lead-engine/seed-followups.php?key=<?=h($cronKey)?>&limit=1" target="_blank">Seed 1 Lead</a><a class="btn" href="/lead-engine/process-call-outcomes.php?key=<?=h($cronKey)?>" target="_blank">Process Outcomes</a><a class="btn" href="/lead-engine/build-future-sellers.php?key=<?=h($cronKey)?>" target="_blank">Build Future Sellers</a></div></section>
<section class="panel"><h2>Config</h2><table><tr><th>Constant</th><th>Status</th><th>Value</th></tr><?php foreach($checks as $c):?><tr><td><?=h($c)?></td><td><span class="badge <?=okc($c)?'ok':'bad'?>"><?=okc($c)?'OK':'Missing'?></span></td><td><?=defined($c)?h(mask(constant($c))):'missing'?></td></tr><?php endforeach;?></table></section>
<section class="panel"><h2>Files</h2><table><tr><th>File</th><th>Status</th></tr><?php foreach($files as $f):?><tr><td><?=h($f)?></td><td><span class="badge <?=fileok($f)?'ok':'bad'?>"><?=fileok($f)?'Installed':'Missing'?></span></td></tr><?php endforeach;?></table></section>
<section class="panel"><h2>Tables</h2><table><tr><th>Table</th><th>Status</th></tr><?php foreach($tables as $t):?><tr><td><?=h($t)?></td><td><span class="badge <?=tableok($t)?'ok':'bad'?>"><?=tableok($t)?'OK':'Error'?></span></td></tr><?php endforeach;?></table></section>
</main></body></html>