<?php
ini_set('display_errors',0); error_reporting(E_ALL);
require_once __DIR__ . '/../config.php';
header('Content-Type: application/json; charset=utf-8');
try{
$key=$_GET['key']??($_POST['key']??'');
if(!defined('AFTER_HOURS_CRON_KEY')||!hash_equals(AFTER_HOURS_CRON_KEY,$key)){http_response_code(403);echo json_encode(['success'=>false,'error'=>'Invalid key']);exit;}
function in165(){ $raw=file_get_contents('php://input'); $j=json_decode($raw,true); return is_array($j)?$j:array_merge($_GET,$_POST); }
function ph165($p){$p=preg_replace('/[^0-9+]/','',(string)$p); if(strlen($p)===10)return '+1'.$p; if(strlen($p)===11&&$p[0]==='1')return '+'.$p; return $p;}
function sb165($m,$ep,$p=null){$ch=curl_init(rtrim(SUPABASE_URL,'/').'/rest/v1/'.ltrim($ep,'/'));curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$m,CURLOPT_HTTPHEADER=>['apikey: '.SUPABASE_SERVICE_ROLE_KEY,'Authorization: Bearer '.SUPABASE_SERVICE_ROLE_KEY,'Content-Type: application/json','Prefer: return=representation'],CURLOPT_TIMEOUT=>35]);if($p!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($p));$b=curl_exec($ch);$h=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$d=json_decode($b,true);return ['ok'=>$h>=200&&$h<300,'http'=>$h,'body'=>$b,'data'=>is_array($d)?$d:[]];}
function rows165($t,$q){$r=sb165('GET',$t.'?'.$q);return $r['ok']?$r['data']:[];}
function town165($a){foreach(['Greenwich','Stamford','Darien','New Canaan','Norwalk','Westport','Weston','Wilton','Fairfield','Ridgefield','Trumbull','Stratford','Bridgeport'] as $t){if(stripos($a,$t)!==false)return $t;}return '';}
function mode165($lead){$b=strtolower(($lead['source']??'').' '.($lead['type']??'').' '.($lead['lead_type']??'').' '.($lead['intent']??'').' '.($lead['message']??'')); if(str_contains($b,'valuation')||str_contains($b,'home value'))return 'valuation'; if(str_contains($b,'seller')||str_contains($b,'sell'))return 'seller'; if(str_contains($b,'buyer')||str_contains($b,'buy'))return 'buyer'; if(str_contains($b,'referral'))return 'referral'; return 'unknown';}
function open165($c){$name=!empty($c['lead_name'])?' '.$c['lead_name']:''; $addr=$c['lead_address']??''; if(($c['mode']??'')==='executive')return "Mark, executive mode is active. I’m connected to Jessica’s intelligence layer and ready to review leads, traffic, creative, campaigns, learning signals, and today’s highest-value actions."; if(($c['mode']??'')==='valuation'){ $ap=$addr?' for your property at '.$addr:''; return "Hi{$name}, this is Jessica, Mark Pires’ personal assistant. Thanks for requesting a home value review{$ap}. I’m here to gather a few quick details so Mark can give you a more accurate local read than a basic online estimate. Is this for a home you own now, or a home you’re thinking about buying?";} if(($c['mode']??'')==='seller')return "Hi{$name}, this is Jessica, Mark Pires’ personal assistant. Thanks for reaching out. I’m here to help Mark understand your selling plans and the details that matter most. Are you thinking about selling soon, or just starting to explore your options?"; if(($c['mode']??'')==='buyer')return "Hi{$name}, this is Jessica, Mark Pires’ personal assistant. Thanks for reaching out. I’m here to help Mark understand what you’re looking for and make sure he has the right details. What towns or areas are you most interested in?"; return "Hi{$name}, this is Jessica, Mark Pires’ personal assistant. Thanks for reaching out. I’m here to help and make sure Mark gets the right details from you. What’s the main reason you connected with Mark today?";}
function execPayload165(){return ['seller_top'=>rows165('seller_acquisition_director','select=*&status=eq.active&order=acquisition_score.desc&limit=10'),'traffic_top'=>rows165('traffic_performance','select=*&order=traffic_date.desc,traffic_score.desc&limit=10'),'learning_top'=>rows165('internal_asset_performance','select=*&order=performance_date.desc,learning_score.desc&limit=10'),'campaign_top'=>rows165('campaign_command_center','select=*&status=eq.active&order=command_score.desc&limit=10')];}
$in=in165(); $phone=ph165($in['phone']??$in['from_number']??$in['from']??$in['caller']??''); $from=ph165($in['from_number']??$in['from']??$phone); $to=ph165($in['to_number']??$in['to']??''); $call=$in['call_id']??$in['retell_call_id']??($in['call']['call_id']??''); $utt=strtolower($in['utterance']??$in['transcript']??$in['message']??$in['text']??'');
$secret='timetomakethedonuts'; $isMark=in_array($phone,['+12032472655','2032472655'],true)||in_array($from,['+12032472655','2032472655'],true);
if($isMark && str_contains(str_replace(' ','',$utt),$secret)){ $payload=execPayload165(); $ctx=['mode'=>'executive','phone'=>$phone,'lead_name'=>'Mark','context_summary'=>'Executive mode activated by Mark secret phrase.','opening_script'=>open165(['mode'=>'executive'])]; sb165('POST','jessica_executive_voice_commands',[['phone'=>$phone,'secret_phrase'=>$secret,'command_text'=>$utt,'detected_mode'=>'executive','response_summary'=>$ctx['opening_script'],'executive_payload'=>$payload,'created_at'=>date('c')]]); echo json_encode(['success'=>true,'context'=>$ctx,'intelligence'=>$payload],JSON_PRETTY_PRINT); exit; }
$lead=null; if($phone){$vars=[$phone]; if(str_starts_with($phone,'+1'))$vars[]=substr($phone,2); if(str_starts_with($phone,'+'))$vars[]=substr($phone,1); foreach($vars as $v){$f=rows165('leads','select=*&phone=eq.'.rawurlencode($v).'&order=created_at.desc&limit=1'); if($f){$lead=$f[0];break;}}}
if(!$lead&&!empty($in['email'])){$f=rows165('leads','select=*&email=eq.'.rawurlencode($in['email']).'&order=created_at.desc&limit=1'); if($f)$lead=$f[0];}
$ctx=['call_id'=>$call,'retell_call_id'=>$call,'phone'=>$phone,'from_number'=>$from,'to_number'=>$to,'lead_id'=>'','lead_source'=>$in['lead_source']??'','lead_type'=>$in['lead_type']??'','lead_name'=>$in['name']??'','lead_email'=>$in['email']??'','lead_address'=>$in['address']??'','town'=>$in['town']??'','intent'=>$in['intent']??'','mode'=>'unknown','route'=>'','lead_score'=>0,'opportunity_score'=>0,'estimated_value'=>(float)($in['estimated_value']??$in['value']??0),'estimated_commission'=>0];
if($lead){$ctx['lead_id']=(string)($lead['id']??'');$ctx['lead_source']=$lead['source']??$lead['type']??$ctx['lead_source'];$ctx['lead_type']=$lead['lead_type']??$lead['type']??$ctx['lead_type'];$ctx['lead_name']=$lead['name']??$ctx['lead_name'];$ctx['lead_email']=$lead['email']??$ctx['lead_email'];$ctx['lead_address']=$lead['address']??$ctx['lead_address'];$ctx['town']=$lead['town']??town165($ctx['lead_address']);$ctx['intent']=$lead['intent']??$ctx['intent'];$ctx['mode']=mode165($lead);$ctx['route']=$lead['route']??'';$ctx['lead_score']=(int)($lead['lead_score']??0);$ctx['estimated_value']=(float)($lead['budget']??$lead['value']??$lead['estimated_value']??$ctx['estimated_value']);}else{$b=strtolower($ctx['lead_source'].' '.$ctx['lead_type'].' '.$ctx['intent'].' '.$ctx['lead_address']); if(str_contains($b,'valuation')||str_contains($b,'home value'))$ctx['mode']='valuation'; elseif(str_contains($b,'seller'))$ctx['mode']='seller'; elseif(str_contains($b,'buyer'))$ctx['mode']='buyer';}
if(!$ctx['town']&&$ctx['lead_address'])$ctx['town']=town165($ctx['lead_address']); if($ctx['estimated_value']>0)$ctx['estimated_commission']=$ctx['estimated_value']*.025;
$opp=[]; if($phone)$opp=rows165('seller_acquisition_director','select=*&phone=eq.'.rawurlencode($phone).'&order=acquisition_score.desc&limit=1'); if($opp){$o=$opp[0];$ctx['opportunity_score']=(int)($o['acquisition_score']??0); if(!$ctx['estimated_value'])$ctx['estimated_value']=(float)($o['estimated_sale_price']??0); if(!$ctx['estimated_commission'])$ctx['estimated_commission']=(float)($o['estimated_commission']??0);}
$ctx['opening_script']=open165($ctx); $ctx['context_summary']="Mode: {$ctx['mode']}. Source: {$ctx['lead_source']}. Name: {$ctx['lead_name']}. Address: {$ctx['lead_address']}. Town: {$ctx['town']}. Lead score: {$ctx['lead_score']}. Opportunity score: {$ctx['opportunity_score']}.";
$intel=['lead'=>$lead,'opportunity'=>$opp[0]??null,'seller_director_top'=>rows165('seller_acquisition_director','select=property_address,town,acquisition_score,recommended_action,estimated_commission&status=eq.active&order=acquisition_score.desc&limit=5'),'traffic_top'=>rows165('traffic_performance','select=source_name,traffic_score,scale_recommendation,recommended_action&order=traffic_date.desc,traffic_score.desc&limit=5'),'learning_top'=>rows165('internal_asset_performance','select=asset_title,brand_pillar,learning_score,recommendation,recommended_next_action&order=performance_date.desc,learning_score.desc&limit=5')];
sb165('POST','jessica_voice_context_sessions',[['call_id'=>$call,'retell_call_id'=>$call,'phone'=>$phone,'from_number'=>$from,'to_number'=>$to,'lead_id'=>$ctx['lead_id'],'lead_source'=>$ctx['lead_source'],'lead_type'=>$ctx['lead_type'],'lead_name'=>$ctx['lead_name'],'lead_email'=>$ctx['lead_email'],'lead_address'=>$ctx['lead_address'],'town'=>$ctx['town'],'intent'=>$ctx['intent'],'mode'=>$ctx['mode'],'route'=>$ctx['route'],'lead_score'=>$ctx['lead_score'],'opportunity_score'=>$ctx['opportunity_score'],'estimated_value'=>$ctx['estimated_value'],'estimated_commission'=>$ctx['estimated_commission'],'context_summary'=>$ctx['context_summary'],'opening_script'=>$ctx['opening_script'],'intelligence_payload'=>$intel,'status'=>'active','created_at'=>date('c'),'updated_at'=>date('c')]]);
echo json_encode(['success'=>true,'context'=>$ctx,'retell_instructions'=>['opening_script'=>$ctx['opening_script'],'mode'=>$ctx['mode'],'do_not_say'=>'Do not say thanks for calling Mark’s office unless this is a generic inbound phone call with no lead context.'],'intelligence'=>$intel],JSON_PRETTY_PRINT);
}catch(Throwable $e){http_response_code(500);echo json_encode(['success'=>false,'error'=>'PHP exception','message'=>$e->getMessage(),'line'=>$e->getLine()],JSON_PRETTY_PRINT);} ?>
